### ISSUE TITLE
Invalid attempt to remove node: NAME path 3 [..] of IMPORT 3 [..]

### ISSUE THREAD

**Issue by RdeWilde** [google/closure-compiler#1067]
I have no idea what it means, but it says: `Please report this problem.` so here it goes:

```
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -jar /home/dewilde/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js app.js --language_in=ECMASCRIPT6_STRICT
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

app.js:2: WARNING - unreachable code
import path           from "path";
       ^
// .. more like this

app.js:80: WARNING - unreachable code
import users    from "./control/users";
       ^

0 error(s), 14 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME path 3 [source_file: app.js] of IMPORT 3 [source_file: app.js]
  Node(NAME path): app.js:3:7
import path           from "path";
  Parent(IMPORT): app.js:3:0
import path           from "path";

	at com.google.javascript.jscomp.NodeUtil.removeChild(NodeUtil.java:2227)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeNode(UnreachableCodeElimination.java:261)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeDeadExprStatementSafely(UnreachableCodeElimination.java:251)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.visit(UnreachableCodeElimination.java:104)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:594)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:588)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:588)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:588)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:295)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:545)
	at com.google.javascript.jscomp.UnreachableCodeElimination$1.visit(UnreachableCodeElimination.java:81)
	at com.google.javascript.jscomp.NodeTraversal$1.shouldTraverse(NodeTraversal.java:532)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:575)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:295)
	at com.google.javascript.jscomp.NodeTraversal.traverseChangedFunctions(NodeTraversal.java:537)
	at com.google.javascript.jscomp.UnreachableCodeElimination.process(UnreachableCodeElimination.java:66)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:458)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1978)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:764)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME path 3 [source_file: app.js] of IMPORT 3 [source_file: app.js]
  Node(NAME path): app.js:3:7
import path           from "path";
  Parent(IMPORT): app.js:3:0
import path           from "path";

	... 29 more
Caused by: java.lang.IllegalStateException: Invalid attempt to remove node: NAME path 3 [source_file: app.js] of IMPORT 3 [source_file: app.js]
	... 29 more

Process finished with exit code 254
```

Source code:
```javascript
"use strict";

import path           from "path";
import fs             from "fs";
import http           from "http";
import spdy           from 'spdy';
import compress       from "compression";
import express        from "express";
import cookieParser   from "cookie-parser";
import bodyParser     from "body-parser";
// .. etc
```

**Comment by MatrixFrog** [comment]
I vaguely recall fixing something like this a while back. Can you check what version of the compiler you're using?

**Comment by RdeWilde** [comment]
@MatrixFrog This info?
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.3
Created-By: 1.8.0-google-v7-98803751-98873050 (Oracle Corporation)
Main-Class: com.google.javascript.jscomp.CommandLineRunner

**Comment by MatrixFrog** [comment]
Sorry:

`java -jar /home/dewilde/compiler.jar --version`

**Comment by RdeWilde** [comment]
@MatrixFrog 
There you go
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150729
Built on: 2015/08/03 09:56

**Comment by MatrixFrog** [comment]
Okay, thanks. Try adding `--language_out=ES3`. I'm not able to repro your exact issue but I do get a few interesting errors if I don't include that, which go away if I do.

**Comment by herrernst** [comment]
I also get a similar error if I just want to compile a simple ES6 module, --language_out=ES3 fixes it. Maybe a better error message would help.

**Comment by MatrixFrog** [comment]
It used to be that if your input language was ES6 then your output language had to be ES3 or ES5. Now, we do support ES6 as an output language, but (many parts of) the compiler don't actually understand the full ES6 language. We handle this by transpiling from ES6 to ES3/5, and then converting "back to ES6" at the very end. It's possible that when running in this way, we're failing to transpile modules correctly.

**Comment by MatrixFrog** [comment]
I don't remember whether we allow --language_out=ES6 now but it sounds like --language_out=ES3 fixes this? Can you open a new bug if you're still seeing this with the latest release?
