### ISSUE TITLE
ES6 destructuring - NullPointerException in NodeUtil.getRValueOfLValue 

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1082]
``` javascript
goog.module("test");

const obj = {a: 5, b: 7};

{
    let {a, b} = obj;
    console.log(a);
}
```
Result:
```
java.lang.NullPointerException
	at com.google.javascript.jscomp.NodeUtil.getRValueOfLValue(NodeUtil.java:3722)
	at com.google.javascript.jscomp.Var.getInitialValue(Var.java:144)
	at com.google.javascript.jscomp.ScopedAliases$AliasUsage.referencesOtherAlias(ScopedAliases.java:213)
	at com.google.javascript.jscomp.ScopedAliases.hotSwapScript(ScopedAliases.java:156)
	at com.google.javascript.jscomp.ScopedAliases.process(ScopedAliases.java:140)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:852)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:768)
...
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522test%2522)%253B%250A%250Aconst%2520obj%2520%253D%2520%257Ba%253A%25205%252C%2520b%253A%25207%257D%253B%250A%250A%257B%250A%2520%2520%2520%2520let%2520%257Ba%252C%2520b%257D%2520%253D%2520obj%253B%250A%2520%2520%2520%2520console.log(a)%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1

**Comment by concavelenz** [comment]
We could do better with a separate pass for goog.module.  Where we only inline the goog.require aliases or some such.

**Comment by supersteves** [comment]
Seems fixed now - link above appears to work - but unsure why.
