### ISSUE TITLE
Internal error with super method call

### ISSUE THREAD

**Issue by ochafik** [google/closure-compiler#1125]
The following code compiled with `--language_in=ECMASCRIPT6_STRICT -O SIMPLE`:
```javascript
class Foo {
  m() {}
}
class Bar extends Foo {
  m() {
    super.m(); // `super['m']()` also crashes
  }
}
```

Crashes with the following trace:
```
INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable arguments
  Node(NAME arguments): bug_closure.js:5:0
class Bar extends Foo {
  Parent(CALL): bug_closure.js:5:0
class Bar extends Foo {

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:652)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:597)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:643)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:595)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:314)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
```

**Comment by concavelenz** [comment]
The ES6 to ES6 complication is still experimental, please use --language_out=ECMASCRIPT5_STRICT for the time being.

**Comment by ochafik** [comment]
> The ES6 to ES6 compilation is still experimental, please use --language_out=ECMASCRIPT5_STRICT for the time being.

Will do, thanks, but doesn't fix this crash unfortunately.

**Comment by MatrixFrog** [comment]
I'm actually seeing this for an even simpler case:

    class Foo {}
    class Bar extends Foo {}

Maybe something to do with one of the recent changes from `NodeTraversal.traverse` to `NodeTraversal.traverseEs6`

**Comment by MatrixFrog** [comment]
`git bisect` says 30433568c712a3846947faef5bb6bc4465680bf3 is to blame.

**Comment by MatrixFrog** [comment]
So it seems to be failing on the synthetic constructor that is inserted by the compiler, which looks like

    class Bar extends Foo {
      constructor() {
        Foo.apply(this, arguments);
      }
    }

But if you add that constructor explicitly then it doesn't fail. What's strange is, it's crashing in the *second* checkVars pass (the "sanity check" that happens at the end) not the one that was moved in 3043356.

**Comment by ochafik** [comment]
Yay, thanks guys!
