### ISSUE TITLE
INTERNAL COMPILER ERROR - Unexpected variable Array

### ISSUE THREAD

**Issue by GregDomjan** [google/closure-compiler#1181]
*Background*
Using maven the samaxes minify-maven-plugin uses an older ```<version>v20140814</version>``` of closure compiler that didn't work well for us - having gotten an INTERNAL COMPILER ERROR and seeing newer versions of Closure available, tried to upgrade.
Found that ```<version>v20150729</version>``` worked with our source, however trying to use the minified js in firefox extension complained of missing semicolon(s) ```";"```

Novice with js and closure.

*Configuration*
Tried using latest version in maven central with config like

			<plugin>
				<groupId>com.samaxes.maven</groupId>
				<artifactId>minify-maven-plugin</artifactId>
				<version>1.7.4</version>
				<dependencies>
					<dependency>
						<groupId>com.google.javascript</groupId>
						<artifactId>closure-compiler</artifactId>
						<version>v20150920</version>
					</dependency>
				</dependencies>
				<configuration>
					<jsEngine>CLOSURE</jsEngine>
					<closureLanguage>ECMASCRIPT6_STRICT</closureLanguage>
				</configuration>

Get the following ouput 

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.4:minify (minify-content) on project webextension-shared: java.lang
.RuntimeException: INTERNAL COMPILER ERROR.
[ERROR] Please report this problem.
[ERROR]
[ERROR] Unexpected variable Array
[ERROR] Node(NAME Array):  [synthetic:2] :94:28
[ERROR] if (!(iterable instanceof Array) && typeof iterable != 'string') {
[ERROR] Parent(INSTANCEOF):  [synthetic:2] :94:8
[ERROR] if (!(iterable instanceof Array) && typeof iterable != 'string') {
```
[snip]
```
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable Array
  Node(NAME Array):  [synthetic:2] :94:28
  if (!(iterable instanceof Array) && typeof iterable != 'string') {
  Parent(INSTANCEOF):  [synthetic:2] :94:8
  if (!(iterable instanceof Array) && typeof iterable != 'string') {

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.samaxes.maven.minify.plugin.MinifyMojo.execute(MinifyMojo.java:473)
        ... 22 more
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable Array
  Node(NAME Array):  [synthetic:2] :94:28
  if (!(iterable instanceof Array) && typeof iterable != 'string') {
  Parent(INSTANCEOF):  [synthetic:2] :94:8
  if (!(iterable instanceof Array) && typeof iterable != 'string') {

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:652)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:597)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:643)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:595)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:314)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1901)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:681)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:632)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:629)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable Array
        ... 28 more
```

Our input files are content.js background.js lib.js
The usage of 'instanceof' is not present in our files
  - I assume from the error that synthetic is something internal to closure.

**Comment by concavelenz** [comment]
Using languageIn=ES6 without externs?

**Comment by GregDomjan** [comment]
Learning more by the minute,  using ```<closureUseDefaultExterns>true</closureUseDefaultExterns>```   and the issue goes away.  Thanks for the pointer @concavelenz

**Comment by Dominator008** [comment]
I **think** the crash is now handled properly after 6d7cbea52dc1a7647a6ec9ca523337eca41fc35c.
