### ISSUE TITLE
[ES6] URISyntaxException if absolute path to input has a space

### ISSUE THREAD

**Issue by jleyba** [google/closure-compiler#1219]
This can be reproduced with empty files, you just need to use a directory that contains a space somewhere in the path.

```
$ java -jar compiler.jar --js=one.js --js="$(pwd)/two.js" --language_in=ECMASCRIPT6 --language_out=ECMASCRIPT5
java.lang.IllegalArgumentException: Illegal character in path at index 27: /Users/jleyba/Development/a b/two.js
	at java.net.URI.create(URI.java:852)
	at com.google.javascript.jscomp.ES6ModuleLoader.createUri(ES6ModuleLoader.java:140)
	at com.google.javascript.jscomp.ES6ModuleLoader.normalizeInputAddress(ES6ModuleLoader.java:119)
	at com.google.javascript.jscomp.ES6ModuleLoader.<init>(ES6ModuleLoader.java:67)
	at com.google.javascript.jscomp.Compiler.processEs6Modules(Compiler.java:1458)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1294)
	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:704)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:636)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:633)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 27: /Users/jleyba/Development/a b/two.js
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 15 more
```

**Comment by dimvar** [comment]
Hey Martin, do you have time to take a look at this? Are module names allowed to have spaces? If so, how are spaces escaped in the module name? I looked at ES6ModuleLoader.java and backward slashes are replaced.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ES6ModuleLoader.java#L139

The javadoc of the class mentions section 26.3.3.18.2 of the spec, but I couldn't find such a section here:
http://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-objects

**Comment by dimvar** [comment]
If you can give me some pointers about what's the desired behavior, I can do the fix.

**Comment by jleyba** [comment]
For the URI, could you just encode the space (`%20`)?

In [toModuleName(URI)](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ES6ModuleLoader.java#L160), you could convert the `%20` to a `_`

**Comment by mprobst** [comment]
Sorry, I've been traveling, only saw this now. The solutions LGTMs.

**Comment by dimvar** [comment]
Np, the resolution turned out to be simple.
