### ISSUE TITLE
[NTI] Internal Compiler Error when redefining a global constant object and adding a constructor property

### ISSUE THREAD

**Issue by abrobston** [google/closure-compiler#1235]
Using Closure built from source at commit [6d54578](https://github.com/google/closure-compiler/commit/6d54578bf7730fa72b6ad832d1fb5ad25ccd7d5e).  Creating a file `nti-bad-type-annotation.js`:

    /**
     * @const
     */
    var outer = {};
    
    (function() {
        var outer = outer || {};
        /**
         * @constructor
         */
        outer.someClass = function() {
        };
        return outer.someClass;
    })();

and using the command line:

    java -jar closure-compiler.jar --js nti-bad-type-annotation.js --js_output_file output.js --compilation_level ADVANCED_OPTIMIZATION --language_in ECMASCRIPT5 --new_type_inf

yields the stack trace:

    java.lang.RuntimeException: INTERNAL COMPILER ERROR.
    Please report this problem.
    
    Null declared type@GETPROP 11 [source_file: nti-bad-type-annotation.js] : function(new:outer.someClass):?
    In scope: null() with root: FUNCTION  6 [source_file: nti-bad-type-annotation.js]
            at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
            at com.google.javascript.jscomp.NewTypeInference.markAndGetTypeOfPreanalyzedNode(NewTypeInference.java:3542)
            at com.google.javascript.jscomp.NewTypeInference.analyzeAssignFwd(NewTypeInference.java:1644)
            at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1267)
            at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1171)
            at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:838)
            at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:696)
            at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:370)
            at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
            at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
            at com.google.javascript.jscomp.Compiler.check(Compiler.java:768)
            at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:684)
            at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
            at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
            at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:639)
            at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
            at java.util.concurrent.FutureTask.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
            at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NullPointerException: Null declared type@GETPROP 11 [source_file: nti-bad-type-annotation.js] : function(new:outer.someClass):?
            ... 20 more

Expected result would perhaps be a warning about redefining the variable, or some other suitable warning.  Actual result is the stack trace above.

**Comment by dimvar** [comment]
Thanks for the report. Slightly simpler repro:

    /** @const */
    var ns = {};
    function f() {
      var ns = ns || {};
      /** @constructor */
      ns.Foo = function() {};
    }

And a similar program that gives a different crash.

    /** @const */
    var ns = {};
    function f() {
      /** @const */
      var ns = ns || {};
      /** @constructor */
      ns.Foo = function() {};
    }

**Comment by concavelenz** [comment]
Note that this doesn't do what you expect. "ns" in the inner function never refers to the outer "ns".
