### ISSUE TITLE
[NTI] Crash on function type union when additional property is added

### ISSUE THREAD

**Issue by abrobston** [google/closure-compiler#1239]
Using Closure built from source at commit [64b0eb4](https://github.com/google/closure-compiler/commit/64b0eb4dad012a9b8ec5a5215ad87c4d2338b904).

With file `nti-function-crash.js`:

    /**
     * @type {(function(Object)|function(string))}
     */
    var a = function() {};
    a.b = {};

running the command line:

    java -jar closure-compiler.jar --js nti-function-crash.js --js_output_file output.js --new_type_inf

yields the stack trace:

    java.lang.IllegalStateException
            at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
            at com.google.javascript.jscomp.newtypes.ObjectType.withFunction(ObjectType.java:226)
            at com.google.javascript.jscomp.newtypes.JSType.withFunction(JSType.java:987)
            at com.google.javascript.jscomp.NTIScope.finalizeScope(NTIScope.java:650)
            at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:402)
            at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
            at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
            at com.google.javascript.jscomp.Compiler.check(Compiler.java:768)
            at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:684)
            at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
            at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
            at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:639)
            at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
            at java.util.concurrent.FutureTask.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
            at java.lang.Thread.run(Unknown Source)

Expected result is... well, not crashing.

**Comment by dimvar** [comment]
Thanks for the report. There is a type error in this program because there is no supertype of the two functions (because there is no common subtype of Object and string). You can see the warning by omitting the a.b assignment. The code that handles functions as namespaces chokes if it gets the wrong function type. I'll fix it.

**Comment by dimvar** [comment]
(Also, you could change either Object or string  to ? as a quick workaround to continue the compilation.)

**Comment by abrobston** [comment]
The test case is contrived, certainly.  I ran across the issue when trying to define externs for the AMD portion of a universal module definition, so I was trying something in the externs file like:

    /**
     * @type {(function(Function)|function(Array<string>, Function)|function(string, Function)|function(string, Array<string>, Function))}
     */
    var define = function(name, modules, factory) {};
    define.amd = {};

so that, in the actual module, this code:

    if (typeof define === 'function' && define.amd) {}

might avoid warnings.
