### ISSUE TITLE
Internal compiler error compiling Chromium WebUI using Polymer

### ISSUE THREAD

**Issue by mgiuffrida** [google/closure-compiler#1241]
I'm working on `chrome/browser/resources/settings/languages.js` and ran into this crash:

```
FAILED: cd ../../chrome/browser/resources/settings/languages_page; python ../../../../../third_party/closure_compiler/compile.py languages.js --depends ../prefs/prefs_types.js ../prefs/compiled_re
sources.gyp:prefs ../../../../../ui/webui/resources/js/compiled_resources.gyp:assert ../../../../../ui/webui/resources/js/compiled_resources.gyp:cr languages_types.js --externs ../../../../../thir
d_party/closure_compiler/externs/chrome_send.js ../../../../../third_party/closure_compiler/externs/language_settings_private.js ../../../../../third_party/closure_compiler/externs/input_method_pr
ivate.js --out-file ../../../../../out/Default/gen/closure/chrome/browser/resources/settings/languages_page/languages.js --closure-args "compilation_level=SIMPLE_OPTIMIZATIONS" "extra_annotation_n
ame=attribute" "extra_annotation_name=demo" "extra_annotation_name=element" "extra_annotation_name=group" "extra_annotation_name=homepage" "extra_annotation_name=status" "extra_annotation_name=sub
module" "jscomp_error=accessControls" "jscomp_error=ambiguousFunctionDecl" "jscomp_error=checkTypes" "jscomp_error=checkVars" "jscomp_error=constantProperty" "jscomp_error=deprecated" "jscomp_erro
r=externsValidation" "jscomp_error=globalThis" "jscomp_error=invalidCasts" "jscomp_error=missingProperties" "jscomp_error=missingReturn" "jscomp_error=nonStandardJsDocs" "jscomp_error=suspiciousCo
de" "jscomp_error=undefinedNames" "jscomp_error=undefinedVars" "jscomp_error=unknownDefines" "jscomp_error=uselessCode" "jscomp_error=visibility" "language_in=ECMASCRIPT6_STRICT" "language_out=ECM
ASCRIPT5_STRICT" polymer_pass "source_map_format=V3" "summary_detail_level=3" "jscomp_off=duplicate" "jscomp_off=misplacedTypeAnnotation"
(ERROR) java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(RETURN): /tmp/tmpg5UC5g:1639:6
      return;
  Parent(BLOCK): /tmp/tmpg5UC5g:1639:6
      return;

        at com.google.javascript.jscomp.TypeCheck.getJSType(TypeCheck.java:1959)
        at com.google.javascript.jscomp.TypeCheck.visitReturn(TypeCheck.java:1825)
        at com.google.javascript.jscomp.TypeCheck.visit(TypeCheck.java:560)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:603)
        at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:352)
        at com.google.javascript.jscomp.TypeCheck.check(TypeCheck.java:422)
        at com.google.javascript.jscomp.TypeCheck.process(TypeCheck.java:393)
        at com.google.javascript.jscomp.DefaultPassConfig$51$1.process(DefaultPassConfig.java:1545)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:761)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:677)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:635)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:632)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        ... 25 more
/tmp/tmpg5UC5g:1283: WARNING - The argument to Polymer() is not an obj lit (perhaps because this is a pre-Polymer-1.0 call). Ignoring this call.
Polymer({
^
```

[File: languages.js](http://pastebin.com/zzYaqtsG)

**Comment by mgiuffrida** [comment]
btw, the offending line is 461. adding another close paren stops the crash and resolves the warnings/errors.

**Comment by dimvar** [comment]
The attached file is not valid JS; it contains these lines:

    <if expr="chromeos">

Can you provide a repro that is only the JS and the command-line that you use for the compiler?

**Comment by MatrixFrog** [comment]
Reopen or re-file if we have a smaller repro case. It sounds like it might be a crash that only happens in IDE mode but it's hard to say for sure.
