### ISSUE TITLE
INTERNAL COMPILER ERROR.

### ISSUE THREAD

**Issue by KOLANICH** [google/closure-compiler#1339]
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(ASSIGN): stdin:2074:403
var _Wv2=0;var _Xv2=0;var _9s=0;var _Yv2=0;var _xM1=60;var _Zv2;var __v2=new Date().getTime();var _0w2;var _1w2=null;var _nL=-1;var _0Q=-1;var _1Q=-1;
var _9p2=!0;var _2w2=!0;var __P=!0;var _3w2=-1;var _4w2=-1;var _pL=-1;var _qL=-1;var _oL=!1;var _ZP=!0;var _2Q={_O2:0,_P2:0,_Q2:0,_R2:0};var _jp2=!1;i
f(window.chrome&&window.chrome.app){_J92=!0;try{if(window&&window['localStorage']){_J92=!1}}catch(e){}}window.onload=_5w2;window.requestAnimFrame=(fun
ction(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||windo
w.msRequestAnimationFrame||function(_TV,
  Parent(EXPR_RESULT): stdin:2074:403
var _Wv2=0;var _Xv2=0;var _9s=0;var _Yv2=0;var _xM1=60;var _Zv2;var __v2=new Date().getTime();var _0w2;var _1w2=null;var _nL=-1;var _0Q=-1;var _1Q=-1;
var _9p2=!0;var _2w2=!0;var __P=!0;var _3w2=-1;var _4w2=-1;var _pL=-1;var _qL=-1;var _oL=!1;var _ZP=!0;var _2Q={_O2:0,_P2:0,_Q2:0,_R2:0};var _jp2=!1;i
f(window.chrome&&window.chrome.app){_J92=!0;try{if(window&&window['localStorage']){_J92=!1}}catch(e){}}window.onload=_5w2;window.requestAnimFrame=(fun
ction(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||windo
w.msRequestAnimationFrame||function(_TV,

        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.simpleInferDeclaration(GlobalTypeInfo.java:1707)
        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.simpleInferExprType(GlobalTypeInfo.java:1622)
        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visitNamespacePropertyDeclaration(GlobalTypeInfo.java:1418)
        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visitNamespacePropertyDeclaration(GlobalTypeInfo.java:1380)
        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visitPropertyDeclaration(GlobalTypeInfo.java:1242)
        at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visit(GlobalTypeInfo.java:1133)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
        at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:377)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:777)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:693)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        ... 25 more
```

**Comment by KOLANICH** [comment]
Also
```
java.lang.RuntimeException: node is not a child
        at com.google.javascript.rhino.Node.getChildBefore(Node.java:667)
        at com.google.javascript.rhino.Node.replaceChild(Node.java:837)
        at com.google.javascript.jscomp.CollapseProperties.inlineGlobalAliasIfPossible(CollapseProperties.java:255)
        at com.google.javascript.jscomp.CollapseProperties.inlineAliases(CollapseProperties.java:177)
        at com.google.javascript.jscomp.CollapseProperties.process(CollapseProperties.java:113)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1943)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:700)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by ChadKillingsworth** [comment]
How did you run the compiler? What flags or options did you use?

**Comment by KOLANICH** [comment]
1 --language_in ECMASCRIPT6 --language_out ECMASCRIPT5_STRICT --new_type_inf -O ADVANCED
2 --language_in ECMASCRIPT6 --language_out ECMASCRIPT5_STRICT -O ADVANCED

**Comment by dimvar** [comment]
This does not contain enough information to reproduce. Please provide a code snippet that causes the crash and I'll reopen.

**Comment by mfikes** [comment]
One way to provoke the "node is not a child" error described above is captured in #1899
