### ISSUE TITLE
Can't use goog.provide and ES6 import in the same file.

### ISSUE THREAD

**Issue by adityavohra7** [google/closure-compiler#1352]
This might be related to https://github.com/google/closure-compiler/issues/880, but I get a different stack trace:
```
~/Desktop/myapp$java -jar tools/closure_compiler.jar assets/js/foo.js  --compilation_level=ADVANCED
assets/js/foo.js:2: WARNING - unreachable code
import {shape} from 'assets/js/square';
^

0 error(s), 1 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME shape 2 [source_file: assets/js/foo.js] of IMPORT_SPEC 2 [source_file: assets/js/foo.js]
  Node(NAME shape): assets/js/foo.js:2:8
import {shape} from 'assets/js/square';
  Parent(IMPORT_SPEC): assets/js/foo.js:2:8
import {shape} from 'assets/js/square';

	at com.google.javascript.jscomp.NodeUtil.removeChild(NodeUtil.java:2350)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeNode(UnreachableCodeElimination.java:261)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeDeadExprStatementSafely(UnreachableCodeElimination.java:251)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.visit(UnreachableCodeElimination.java:104)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
	at com.google.javascript.jscomp.UnreachableCodeElimination$1.enterFunction(UnreachableCodeElimination.java:81)
	at com.google.javascript.jscomp.NodeTraversal$1.shouldTraverse(NodeTraversal.java:541)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:602)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
	at com.google.javascript.jscomp.NodeTraversal.traverseChangedFunctions(NodeTraversal.java:536)
	at com.google.javascript.jscomp.UnreachableCodeElimination.process(UnreachableCodeElimination.java:66)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:458)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1943)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:700)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME shape 2 [source_file: assets/js/foo.js] of IMPORT_SPEC 2 [source_file: assets/js/foo.js]
  Node(NAME shape): assets/js/foo.js:2:8
import {shape} from 'assets/js/square';
  Parent(IMPORT_SPEC): assets/js/foo.js:2:8
import {shape} from 'assets/js/square';

	... 32 more
Caused by: java.lang.IllegalStateException: Invalid attempt to remove node: NAME shape 2 [source_file: assets/js/foo.js] of IMPORT_SPEC 2 [source_file: assets/js/foo.js]
	... 32 more
```

Here are the files I'm using:

```javascript
// assets/js/main.js

goog.require('foo.bar');

import {shape} from 'assets/js/square';
import {Square} from 'assets/js/square';

var square = new Square(5)
console.log(square.speak());
console.log(shape);
console.log(foo.bar());
```

```javascript
// assets/js/foo.js

goog.provide('foo.bar');
import {hey} from 'assets/js/square';

foo.bar = function () {
    console.log(hey);
    return 42;
};
```

```javascript
// assets/js/square.js

export const hey = 'SQUARE';

export class Square {
    constructor(side) {
        this.side = side;
    }

    area() {
        return this.side * this.side;
    }

    speak() {
        console.log('I AM A SQUARE!');
    }
}
```

I'm using the latest version of the closure compiler from https://github.com/google/closure-compiler/wiki/Binary-Downloads.

**Comment by dimvar** [comment]
Using goog.provide and ES6 import in the same file is not allowed. The fix will be to get a compiler warning instead of crashing.

**Comment by adityavohra7** [comment]
@dimvar Thanks for replying promptly! 

Out of curiosity, what is the reasoning behind disallowing goog.provide's and ES6 imports in the same file? Are there plans of supporting this in the future? Or are there workarounds that I'm missing which allow importing an ES6 modules in a "traditional Closure" javascript file (or doing something similar)?

**Comment by ChadKillingsworth** [comment]
Anything with an ES6 import statement is considered an ES6 module and will automatically have `goog.provide` statements created for it.

While there is a strong desire to use ES6 imports in non-module code, that's just not valid JS. The missing piece is the as-yet-to-be-completed module loader.

**Comment by dimvar** [comment]
As I understand it, ES6 modules don't get evaluated in the global scope, whereas a file with a goog.provide gets evaluated in the global scope. So it's an error to have both in the same file.

**Comment by adityavohra7** [comment]
@ChadKillingsworth @dimvar Thanks for explaining! That makes sense to me. I'll close this issue.
