### ISSUE TITLE
Crash in NTI when misdeclaring override function params

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1372]
Here I have a method which overrides a superclass method and forgets to declare the same args:
``` javascript
class A {  someMethod(x) {}  }
class B extends A {  /** @override */ someMethod() {}  }
```

This crashes NTI:
```
Index: 0, Size: 0
In scope: B.prototype.someMethod() with root: FUNCTION  2 [source_file: input0]
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.google.javascript.jscomp.NewTypeInference.createSummary(NewTypeInference.java:978)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:699)
	at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:371)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:788)
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520A%2520%257B%2520%2520someMethod(x)%2520%257B%257D%2520%2520%257D%250Aclass%2520B%2520extends%2520A%2520%257B%2520%2520%252F**%2520%2540override%2520*%252F%2520someMethod()%2520%257B%257D%2520%2520%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

(Presumably you must declare the same args, even if the overridden method doesn't use them)

**Comment by dimvar** [comment]
Thanks for the report, I'll look into it.

**Comment by supersteves** [comment]
Thanks!
