### ISSUE TITLE
[NTI] Crash after making interfaces inherit from Object

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1440]
The following code:
```javascript
var goog = {};

goog.abstractMethod = function() {};

/**
 * @interface
 */
function Foo() {}

Foo.prototype.toString = goog.abstractMethod;
```
crashes NTI with
```
java.lang.NullPointerException
	at com.google.javascript.jscomp.GlobalTypeInfo.checkSuperProperty(GlobalTypeInfo.java:606)
	at com.google.javascript.jscomp.GlobalTypeInfo.checkAndFinalizeNominalType(GlobalTypeInfo.java:504)
	at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:403)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:771)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:687)
	at com.google.javascript.jscomp.Compiler.access$1(Compiler.java:671)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:645)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:1)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

git bisect indicates that d091caa582bd0fbfaa46eb305dc049ace654cd1e is the culprit.

**Comment by Dominator008** [comment]
Fixed by 8edc042cf752dbf23dec3bdbb4ba37352d6adf7d
