### ISSUE TITLE
ICE when using --new_type_inf

### ISSUE THREAD

**Issue by rx80** [google/closure-compiler#1513]
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20160208
Built on: 2016/02/08 16:23
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
In scope: <TOP SCOPE> with root: BLOCK [synthetic: 1]
        at com.google.javascript.jscomp.NewTypeInference.analyzeLooseCallNodeFwd(NewTypeInference.java:2947)
        at com.google.javascript.jscomp.NewTypeInference.analyzeCallNewFwd(NewTypeInference.java:1791)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1318)
        at com.google.javascript.jscomp.NewTypeInference.analyzePropAccessFwd(NewTypeInference.java:2789)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1308)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1172)
        at com.google.javascript.jscomp.NewTypeInference.analyzeCallNewFwd(NewTypeInference.java:1777)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1318)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1172)
        at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:839)
        at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:697)
        at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:371)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:771)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:687)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        ... 24 more
```

**Comment by Dominator008** [comment]
Can you provide the source code that can reproduce this?

**Comment by rx80** [comment]
The problem with providing the source is that it's a massive combined JS file... Is there a way to get more details from the compiler where in the source or what token this is?

**Comment by dimvar** [comment]
If you are comfortable building the compiler from head, then you can edit the compiler source to print out more information. Closing this until we get a repro.

**Comment by Dominator008** [comment]
@dimvar https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/NewTypeInference.java#L2947 seems problematic, `calleePair.type.getFunTypeIfSingletonObj()` can be null, but it's unchecked.

**Comment by dimvar** [comment]
This is intentional; `analyzeLooseCallNodeFwd` is only called after we've established that the callee is a function:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/NewTypeInference.java#L1790
So, we expect a non-null answer there; if there is a null deref, we need to figure out why it happens.

**Comment by Dominator008** [comment]
@rx80 Not sure if this has been fixed by the recent changes in NTI. Would you like to give it another try?

**Comment by rx80** [comment]
@Dominator008 error persists
`
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
In scope: this.activate_action(evt) with root: FUNCTION  12348 [source_file: plain.js]
        at com.google.javascript.jscomp.NewTypeInference.getTypeEnvFromDeclaredTypes(NewTypeInference.java:532)
        at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:655)
        at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:385)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:777)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:693)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        ... 15 more
`

**Comment by rx80** [comment]
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20160315
Built on: 2016/03/25 11:43

Code to trigger:
```
a = {};
a.prototype.b = function () {
        var _this = this;
        this.c = function (evt) {
                return _this.c(evt);
        };
};
```

**Comment by dimvar** [comment]
Thank you for the very small repro! I'll look into this.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/68437e8434233aa5844602083feeed675c0e3737.
