### ISSUE TITLE
java.lang.RuntimeException: INTERNAL COMPILER ERROR.

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#1520]
When I compile my app I get this error:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Null declared type@GETPROP 1542 [source_file: filevision/net/API.js]
In scope: <TOP SCOPE> with root: BLOCK [synthetic: 1]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:251)
	at com.google.javascript.jscomp.NewTypeInference.markAndGetTypeOfPreanalyzedNode(NewTypeInference.java:3629)
	at com.google.javascript.jscomp.NewTypeInference.analyzeAssignFwd(NewTypeInference.java:1646)
	at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1268)
	at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1172)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:839)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:697)
	at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:371)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:771)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:687)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Null declared type@GETPROP 1542 [source_file: filevision/net/API.js]
	... 20 more
```

**Comment by Dominator008** [comment]
Can you extract a minimal repro case?

**Comment by ghosttie** [comment]
I'll try, but I don't really have any idea why it started happening

**Comment by dimvar** [comment]
Without a repro, we can't really do anything here. If you can provide a repro, comment here and I'll reopen.

**Comment by ghosttie** [comment]
I figured it out - it happens if you try to provide a child namespace without providing its parent, for example

```
goog.provide('filevision.net.API.DataSourceGetRequest');
```

without

```
goog.provide('filevision.net.API');
```

If I do that with OTI I get

```
filevision/net/API.js:6: WARNING - assignment to property API of filevision.net
found   : {}
required: function (new:filevision.net.API): undefined
goog.provide('filevision.net.API.DataSourceGetRequest');
```

and in NTI it crashes the compiler.

**Comment by dimvar** [comment]
This works without issues. See:
http://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('a.b.c')%253B%250A%26input1%26conformanceConfig%26externs%3Dvar%2520goog%253B%250Agoog.provide%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Can you dig a little more? Providing a repro in the debugger would be most useful. Check to see if you have duplicate definitions in your code, I've seen them cause bugs like this in some cases.

**Comment by ghosttie** [comment]
Got it - for whatever reason it only crashes if a.b is defined but not provided

http://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('a.b.c')%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A*%252F%250Aa.b%2520%253D%2520function()%2520%257B%257D%26input1%26conformanceConfig%26externs%3Dvar%2520goog%253B%250Agoog.provide%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment]
Great, thanks for the very short repro!
