### ISSUE TITLE
Crash in ObjectType.withPropertyHelper (NTI)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1521]
This came up in our codebase. It's pretty weird... 

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please email js-compiler@google.com with this stack trace and repro steps (a CL# and a build target).

Trying to update property structure.x on type {items:Object} (loose), but sub-property structure does not exist
In scope: f(m) with root: FUNCTION  13 [source_file: input0]
    at com.google.common.base.Preconditions.checkState(Preconditions.java:204)
    at com.google.javascript.jscomp.newtypes.ObjectType.withPropertyHelper(ObjectType.java:296)
    at com.google.javascript.jscomp.newtypes.ObjectType.withProperty(ObjectType.java:317)
    at com.google.javascript.jscomp.newtypes.ObjectType.withProperty(ObjectType.java:324)
    at com.google.javascript.jscomp.newtypes.JSType.withProperty(JSType.java:1173)
    at com.google.javascript.jscomp.NewTypeInference.updateLvalueTypeInEnv(NewTypeInference.java:2888)
    at com.google.javascript.jscomp.NewTypeInference.mayWarnAboutNullableReferenceAndTighten(NewTypeInference.java:3765)
    at com.google.javascript.jscomp.NewTypeInference.analyzePropAccessFwd(NewTypeInference.java:2790)
    at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1308)
    at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1172)
    at com.google.javascript.jscomp.NewTypeInference.analyzeCallNewFwd(NewTypeInference.java:1777)
    at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1318)
    at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1172)
    at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:839)
    at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:697)
    at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:371)
```

https://closure-compiler-debugger.appspot.com/#input0%3D%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520key%250A%2520*%2520%2540param%2520%257BOD%257D%2520option%250A%2520*%252F%250Avar%2520g%2520%253D%2520function(key%252C%2520option)%2520%257B%250A%2520%2520%2520%2520console.log(key%252C%2520option)%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BM%257D%2520m%250A%2520*%252F%250Avar%2520f%2520%253D%2520function(m)%2520%257B%250A%2520%2520%2520%2520if%2520(!m)%2520return%253B%250A%250A%2520%2520%2520%2520let%2520options%2520%253D%2520m.options%253B%250A%250A%2520%2520%2520%2520options.structure.toolbar.forEach(function(key)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520g(key%252C%2520options.items%255Bkey%255D)%253B%250A%2520%2520%2520%2520%257D.bind(this))%253B%250A%250A%2520%2520%2520%2520options.structure.x.forEach(function(key)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520g(key%252C%2520options.items%255Bkey%255D)%253B%250A%2520%2520%2520%2520%257D.bind(this))%253B%250A%257D%26input1%26conformanceConfig%26externs%3D%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520TS%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BArray%253Cstring%253E%257D%2520*%252F%250ATS.prototype.toolbar%2520%253D%2520%255B%255D%253B%250A%250A%252F**%2520%2540type%2520%257BArray%253Cstring%253E%257D%2520*%252F%250ATS.prototype.x%2520%253D%2520%255B%255D%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520OD%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520ODS%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BObject%253Cstring%252C%2520OD%253E%257D%2520*%252F%250AODS.prototype.items%253D%2520null%253B%250A%250A%252F**%2520%2540type%2520%257BTS%257D%2520*%252F%250AODS.prototype.structure%253D%2520null%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520M%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BODS%257D%2520*%252F%250AM.prototype.options%2520%253D%2520null%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
It might help to know the workaround I found... adding an explicit type annotation to 'let options':

https://closure-compiler-debugger.appspot.com/#input0%3D%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520key%250A%2520*%2520%2540param%2520%257BOD%257D%2520option%250A%2520*%252F%250Avar%2520g%2520%253D%2520function(key%252C%2520option)%2520%257B%250A%2520%2520%2520%2520console.log(key%252C%2520option)%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BM%257D%2520m%250A%2520*%252F%250Avar%2520f%2520%253D%2520function(m)%2520%257B%250A%2520%2520%2520%2520if%2520(!m)%2520return%253B%250A%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257BODS%257D%2520*%252F%250A%2520%2520%2520%2520let%2520options%2520%253D%2520m.options%253B%250A%250A%2520%2520%2520%2520options.structure.toolbar.forEach(function(key)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520g(key%252C%2520options.items%255Bkey%255D)%253B%250A%2520%2520%2520%2520%257D.bind(this))%253B%250A%250A%2520%2520%2520%2520options.structure.x.forEach(function(key)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520g(key%252C%2520options.items%255Bkey%255D)%253B%250A%2520%2520%2520%2520%257D.bind(this))%253B%250A%257D%26input1%26conformanceConfig%26externs%3D%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520TS%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BArray%253Cstring%253E%257D%2520*%252F%250ATS.prototype.toolbar%2520%253D%2520%255B%255D%253B%250A%250A%252F**%2520%2540type%2520%257BArray%253Cstring%253E%257D%2520*%252F%250ATS.prototype.x%2520%253D%2520%255B%255D%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520OD%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520ODS%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BObject%253Cstring%252C%2520OD%253E%257D%2520*%252F%250AODS.prototype.items%253D%2520null%253B%250A%250A%252F**%2520%2540type%2520%257BTS%257D%2520*%252F%250AODS.prototype.structure%253D%2520null%253B%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520M%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257BODS%257D%2520*%252F%250AM.prototype.options%2520%253D%2520null%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
