### ISSUE TITLE
Internal compiler error when CommonJS module exports with object literal short-hand

### ISSUE THREAD

**Issue by jleyba** [google/closure-compiler#1592]
```javascript
// a.js
exports.x = 1;

// b.js
var a = require('./a');
module.exports = {a};  // Also triggers with exports.y = {a};
```

```
$ java -jar compiler.jar --dependency_mode STRICT --js a.js --js b.js --entry_point b --process_common_js_modules
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable a
  Node(NAME a): b.js:2:18
module.exports = {a};
  Parent(STRING_KEY a): b.js:2:18
module.exports = {a};

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1875)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:694)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable a
	... 22 more
```

**Comment by Dominator008** [comment]
With #1593 this compiles to
```js
var module$a={x:1};var a$$module$b=module$a,module$b={a:a$$module$b};
```
which seems correct to me.
