### ISSUE TITLE
Object literal short-hand in ES6 modules not handled correctly.

### ISSUE THREAD

**Issue by tSte** [google/closure-compiler#1636]
I have this:
```js
const obj = { prop: 1 };
const {prop} = obj;
console.log(prop);
```
and get this:
```
ERROR - variable prop$$module$$src is undeclared
console.log(prop);
```
It is strange, because I have been using destructuring syntax with GCC for a few months. Recently I moved to 20160208.5.0

**Comment by Dominator008** [comment]
Seems like you are using ES6 modules. Can you show a more complete repo case?

**Comment by tSte** [comment]
Sorry, I can't... :(

But it's easy to get it done:

- bar.js -
```
export default function getObj(spec) {
    return { a: 1, b: 2 };
}
```

- foo.js -
```
import getBar from './bar';
const barArg = 1;
const { a, b } = getBar({ barArg });
console.log(a, b);
export const App = { a };
```

GCC produces this error:
/src2/foo.js:5: ERROR - variable a$$module$$src2$foo is undeclared
console.log(a, b);
/src2/foo.js:5: ERROR - variable b$$module$$src2$foo is undeclared
console.log(a, b);

If you change it to:
```
const bar = getBar({ barArg });
const a = bar.a;
const b = bar.b;
```
it will compile

However try to do some "tricky" stuff like:

- bar.js -
```
export default function getObj(spec) {
    const barArg = spec.barArg;
    return { a: 1, b: barArg };
}
```

- foo.js -
```
import getBar from './bar';

const barArg = 1;
const bar = getBar({ barArg });
const a = bar.a;
const b = bar.b;
console.log(a, b);

export const App = { a };
```

And GCC produces
/src2/foo.js:4: ERROR - variable barArg is undeclared
const bar = getBar({ barArg });
                     ^

1 error(s), 0 warning(s), 65.7% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable barArg
  Node(NAME barArg): /src2/foo.js:4:21
const bar = getBar({ barArg });
  Parent(STRING_KEY b): /src2/bar.js:3:19
    return { a: 1, b: barArg };

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1875)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:694)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Unexpected variable barArg
        ... 22 more

I will experiment more with this, because there seem to be more bugs and... I would reeeally like to have this fixed :)

**Comment by tSte** [comment]
I would also like to ask what to put into entry_point in this case, because I can't figure it out. I am running gulp I have tried:
- App
- foo.App
- src2.App
- src2.foo.App
- foo
- src2.foo
- foo/App
- src2/App
- src2/foo/App
- src2/foo
- ./foo
- ./foo/App
- ./src2/foo
- ./src2/foo/App

What am I missing? :(

**Comment by Dominator008** [comment]
Ok so it wasn't destructuring that was causing the problem, it was the object literal shorthand syntax. This is essentially the same as https://github.com/google/closure-compiler/issues/1592 and the fix is identical.

**Comment by Dominator008** [comment]
For the `entry_point`, I **think** `--entry_point=src2/foo` should work.

**Comment by tSte** [comment]
Nope :( it doesn't... but` --entry_point=/src2/foo` does...

**Comment by Dominator008** [comment]
With a Compiler built from #1637, I tried your "tricky" example with
```
java -jar build/compiler.jar --dependency_mode=STRICT --entry_point=foo -W VERBOSE foo.js bar.js
```
and got
```
var module$bar={};function getObj$$module$bar(a){return{a:1,b:a.barArg}}module$bar["default"]=getObj$$module$bar;var module$foo={},barArg$$module$foo=1,bar$$module$foo=module$bar["default"]({barArg:barArg$$module$foo}),a$$module$foo=bar$$module$foo.a,b$$module$foo=bar$$module$foo.b;console.log(a$$module$foo,b$$module$foo);var App$$module$foo={a:a$$module$foo};module$foo.App=App$$module$foo;
```
without crash / error / warning.

**Comment by tSte** [comment]
Are you sure it is caused by object shorthand syntax? I tried this:
```
var obj = {
    a: 1
};
var {a} = obj;
console.log(a);

export default function() { }
```
and result was
```
/src2/foo.js:5: ERROR - variable a$$module$$src2$foo is undeclared
console.log(a);
```

About that "ticky" one, I tried your flags and get this result:
```
java -jar c:\_gccTEST\node_modules\google-closure-compiler\compiler.jar --j
s_output_file=app.min.js --dependency_mode=STRICT --entry_point=/src2/foo --json
_streams BOTH

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable barArg
  Node(NAME barArg): /src2/foo.js:4:21
const bar = getBar({ barArg });
  Parent(STRING_KEY barArg): /src2/foo.js:4:21
const bar = getBar({ barArg });
```

**Comment by Dominator008** [comment]
I see your confusion. Your examples all works on a custom built with PR #1637, not on version v20160208 which is used by google-closure-compiler 20160208.5.0.

I've attached my custom build. Rename it to `compiler.jar` and extract it to your `node_modules\google-closure-compiler\` directory. It should work from there.
![compiler](https://cloud.githubusercontent.com/assets/1403453/13704186/957c2ec4-e768-11e5-94a2-5f604f4f2609.jpg)

**Comment by ChadKillingsworth** [comment]
If your entry point uses ES6 `import` statements, but doesn't actually export anything, then you'll need PR #1628. That allows entry points that don't `goog.provide` anything.

**Comment by ChadKillingsworth** [comment]
Sorry - wrong PR. As long as the build from @Dominator008 contains 2abe1d4995e7eb604093b8b0f7d5240d5c317ac2 it should work.
