### ISSUE TITLE
Misspelled flag name

### ISSUE THREAD

**Issue by anonymousandrew** [google/closure-compiler#1659]
While running the compiler, I received the following error:

```
com.google.javascript.jscomp.CompilerOptionsPreprocessor$InvalidOptionsException: remove_unused_prototype_properties_in_externs requires remove_unused_prototype_properties to be turned on.
        at com.google.javascript.jscomp.CompilerOptionsPreprocessor.preprocess(CompilerOptionsPreprocessor.java:45)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:686)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:85)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:658)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:655)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Target //geo/gestalt/playground/javascript:playground_js failed to build

```
And so I added: "--remove_unused_prototype_properties_in_externs=False" to my compiler flags, and I got the following error:

```
Exception in thread "main" com.google.common.flags.InvalidFlagsException: Unrecognized flag(s): [remove_unused_prototype_properties_in_externs]
        at com.google.common.flags.Flags.parseAndReturnLeftovers(Flags.java:733)
        at com.google.common.flags.Flags.parse(Flags.java:695)
        at com.google.javascript.jscomp.JSCompilerRunner.initConfigFromFlags(JSCompilerRunner.java:352)
        at com.google.javascript.jscomp.JSCompilerRunner.<init>(JSCompilerRunner.java:343)
        at com.google.javascript.jscomp.JSCompilerRunner.main(JSCompilerRunner.java:338)
Caused by: com.google.common.flags.UnrecognizedFlagException: Unrecognized flag(s): [remove_unused_prototype_properties_in_externs]
        at com.google.common.flags.Flags.parseInternal(Flags.java:926)
        at com.google.common.flags.Flags.parseAndReturnLeftovers(Flags.java:727)
        ... 4 more
```

I solved this by updating the flag to "--remove_unused_prototype_props_in_externs=False". Note **properties** vs **props**. Seems like a flag or warning message got misspelled somewhere.

**Comment by dimvar** [comment]
Thanks for the report. Will fix.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/94af3e147606fc7a029cc0c42fbf53bb238f1404.
