### ISSUE TITLE
StackOverflowError occurs when thousands of strings are concatenated in a single expression

### ISSUE THREAD

**Issue by ispringer** [google/closure-compiler#1661]
Here's the repeating portion of the stack trace:

```
$ java -jar compiler.jar test.js
java.lang.StackOverflowError
	at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931) 
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:734)
	at com.google.javascript.jscomp.parsing.IRFactory.access$300(IRFactory.java:163)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression(IRFactory.java:1322)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2517)
	at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931)
```

test.js is attached. Note it's a concatenation of 2,000 strings in a single expression.

There are two workarounds for this issue that I have found:

1. Break the string concatenation up into multiple statements
2. Increase JVM stack size, e.g. -Xss8M

[test.js.zip](https://github.com/google/closure-compiler/files/174985/test.js.zip)

**Comment by Dominator008** [comment]
There's nothing we can really do here as we are using a recursive descent parser. This should happen rarely and when it does, both workarounds are relatively simple.

**Comment by concavelenz** [comment]
@Dominator008 That isn't completely true, minimizing the amount of stack used can help a lot.  There used to be a test for this specifically.

**Comment by Dominator008** [comment]
@concavelenz Yes, I recall the test was either deleted or reduced to a few hundred binary operations. @MatrixFrog

**Comment by nicks** [comment]
fwiw, there's a trick to handle this in a recursive descent parser. You can basically unroll the recursion for simple cases, like a tail-call optimizer would. (I think the old parser used to do this)

**Comment by concavelenz** [comment]
This is actually failing in the post parse processing of the AST (to convert it to the internal AST).  The actual parse is fine (which doesn't recurse for this case)

**Comment by concavelenz** [comment]
I'm landing a change to reduce the stack space usage (for another issues), so the stack will go from:

```
    at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931) 
    at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:734)
    at com.google.javascript.jscomp.parsing.IRFactory.access$300(IRFactory.java:163)
    at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression(IRFactory.java:1322)
    at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2517)
    at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931)

```

to 

```
    at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:734)
    at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression(IRFactory.java:1322)
    at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2517)
    at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:734)

```

which will help in some cases.

**Comment by Dominator008** [comment]
https://github.com/google/closure-compiler/commit/069e6378f8ba41372c9a1a38d4f4ebbbb4328fe1 fixed this for most cases.
