### ISSUE TITLE
For..of not supported

### ISSUE THREAD

**Issue by victordelacruz** [google/closure-compiler#1775]
Hello guys, I tried to use the `for..of` form in my code and got this:

```
Closure::Error: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.
INTERNAL COMPILER ERROR.
Please report this problem.
Invalid attempt to remove node: NAME elements$$11 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs] of FOR_OF 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs]
  Node(NAME elements$$11): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174223:26
      for( var element of elements ) {
  Parent(FOR_OF): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174223:6
      for( var element of elements ) {

  Node(FUNCTION ): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174222:47
    scope.$watchCollection( 'translationsFor', function( languages ) {
  Parent(CALL): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174222:4
    scope.$watchCollection( 'translationsFor', function( languages ) {

	at com.google.javascript.jscomp.NodeUtil.removeChild(NodeUtil.java:2149)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeNode(UnreachableCodeElimination.java:261)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeDeadExprStatementSafely(UnreachableCodeElimination.java:251)
	at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.visit(UnreachableCodeElimination.java:104)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:584)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:535)
	at com.google.javascript.jscomp.UnreachableCodeElimination$1.visit(UnreachableCodeElimination.java:81)
	at com.google.javascript.jscomp.NodeTraversal$1.shouldTraverse(NodeTraversal.java:521)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:564)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:618)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:569)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:618)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:569)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverseChangedFunctions(NodeTraversal.java:526)
	at com.google.javascript.jscomp.UnreachableCodeElimination.process(UnreachableCodeElimination.java:66)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:449)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1962)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:752)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:92)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:638)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:635)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:682)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.
Invalid attempt to remove node: NAME elements$$11 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs] of FOR_OF 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs]
  Node(NAME elements$$11): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174223:26
      for( var element of elements ) {
  Parent(FOR_OF): /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs:174223:6
      for( var element of elements ) {

	... 38 more
Caused by: java.lang.IllegalStateException: Invalid attempt to remove node: NAME elements$$11 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs] of FOR_OF 174223 [source_file: /var/folders/14/r324yp115tz3ngst5gzm257w0000gn/T/closure_compiler20160505-5280-v0uvqs]
	... 38 more
```

After swapping `for..of` for lodash's `forEach` it compiled without problems.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by dimvar** [comment]
Make sure you pass `--language_out=ECMASCRIPT5`
