### ISSUE TITLE
Minification fails if file name contains `<`, `[`, `]`, or `>` chars

### ISSUE THREAD

**Issue by jochenberger** [google/closure-compiler#1817]
```
...
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 18: StreamableResource<text/javascript;charset=utf-8%20'core'%20JavaScript%20stack,%20for%20locale%20en,%20resources=classpath-META-INF/assets/tapestry5/require.js,%20classpath-META-INF/assets/tapestry5/underscore-1.8.3.js,%20webjars-META-INF/resources/webjars/jquery/3.0.0-rc1/dist/jquery.js,%20classpath-META-INF/modules/t5/core/alert.js,%20classpath-META-INF/modules/t5/core/ajax.js,%20classpath-META-INF/modules/t5/core/bootstrap.js,%20classpath-META-INF/modules/t5/core/console.js,%20classpath-org/apache/tapestry5/t5-core-dom-jquery.js,%20classpath-META-INF/modules/t5/core/events.js,%20classpath-META-INF/modules/t5/core/exception-frame.js,%20classpath-META-INF/modules/t5/core/fields.js,%20classpath-META-INF/modules/t5/core/forms.js,%20classpath-META-INF/modules/t5/core/pageinit.js,%20classpath-META-INF/modules/t5/core/messages.js,%20classpath-META-INF/modules/t5/core/utils.js,%20classpath-META-INF/modules/t5/core/validation.js,%20classpath-META-INF/assets/tapestry5/underscore-shim.js%20COMPRESSABLE%20lastModified-%20Thu%20May%2026%2011-33-44%20CEST%202016%20size-%20449953>
    	at java.net.URI.create(URI.java:852)
    	at com.google.javascript.jscomp.deps.Es6SortedDependencies.createUri(Es6SortedDependencies.java:165)
    	at com.google.javascript.jscomp.deps.Es6SortedDependencies.processInputs(Es6SortedDependencies.java:187)
    	at com.google.javascript.jscomp.deps.Es6SortedDependencies.<init>(Es6SortedDependencies.java:65)
    	at com.google.javascript.jscomp.JSModuleGraph.manageDependencies(JSModuleGraph.java:362)
    	at com.google.javascript.jscomp.Compiler.orderInputs(Compiler.java:1491)
    	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1409)
    	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:736)
    	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:692)
    	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
    	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:659)
    	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:656)
    	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:118)
    	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:686)
    	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:656)
    	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:626)
```

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/747aa4dfc5fb8c7a10dcaf96abb122cc72825fdb (#1818).
