### ISSUE TITLE
Invalid var args jsdoc crashes the pretty printer

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1944]
As previously discussed here: https://github.com/google/closure-compiler/pull/1369#issuecomment-185372236

Crash in pretty print
```
java.lang.UnsupportedOperationException: EMPTY is not a string node
	at com.google.javascript.rhino.Node.getString(Node.java:1095)
	at com.google.javascript.jscomp.JSDocInfoPrinter.appendTypeNode(JSDocInfoPrinter.java:296)
	at com.google.javascript.jscomp.JSDocInfoPrinter.appendTypeNode(JSDocInfoPrinter.java:250)
	at com.google.javascript.jscomp.JSDocInfoPrinter.typeNode(JSDocInfoPrinter.java:228)
	at com.google.javascript.jscomp.JSDocInfoPrinter.buildParamType(JSDocInfoPrinter.java:220)
	at com.google.javascript.jscomp.JSDocInfoPrinter.print(JSDocInfoPrinter.java:128)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:114)
...
```

Caused by jsdoc for variable args without a type qualifier:
``` javascript
/**
 * @param {...} var_args
 */
AA = function(var_args) {
};
```
Presumably the proper jsdoc for a loose varargs would be `{...?}`, which prints fine.

Test case in the [Debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257B...%257D%2520var_args%250A%2520*%252F%250AAA%2520%253D%2520function(var_args)%2520%257B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

**Comment by Dominator008** [comment]
I think `{...}` implies `{...?}`: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257B...%257D%2520var_args%250A%2520*%252F%250AAA%2520%253D%2520function(var_args)%2520%257B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26TRANSPILE%3D1

Will fix this.

**Comment by supersteves** [comment]
Thanks!
