### ISSUE TITLE
Ungraceful error: Already found a mapping for inlining short name

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1964]
```js
goog.module('a');

const a = goog.require('a');
const a = goog.require('a');
```

Result:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

Already found a mapping for inlining short name: a
  Node(CALL): input0:4:10
const a = goog.require('a');
  Parent(NAME a): input0:4:6
const a = goog.require('a');

	at com.google.common.base.Preconditions.checkState(Preconditions.java:523)
	at com.google.javascript.jscomp.ClosureRewriteModule.recordNameToInline(ClosureRewriteModule.java:1296)
	at com.google.javascript.jscomp.ClosureRewriteModule.updateGoogRequire(ClosureRewriteModule.java:860)
```

**Comment by MatrixFrog** [comment]
Er, shouldn't this be a syntax error (or at least an early error in CheckVars or something) to have two `const a`s?

**Comment by SLaks** [comment]
Yes, but it should not be an `INTERNAL COMPILER ERROR`.

This might be caused by `ClosureRewriteModule` running before the real error.

**Comment by Dominator008** [comment]
@MatrixFrog I now think VariableReferenceCheck should run before the closure passes.
