### ISSUE TITLE
Compiler crash with "Unexpected variable"

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1978]
```javascript
var listener;
self.addEventListener('click', listener = function(event) {
	console.log(listener);
});
```

This piece of code makes it crash in ADVANCED compilation. In SIMPLE compilation level is everything ok. I was not able to reproduce it via debugger.

```
media/js/test.js:3: ERROR - variable listener is undeclared
	console.log(listener);
	            ^

1 error(s), 0 warning(s), 100.0% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable listener
  Node(NAME listener): media/js/test.js:3:13
	console.log(listener);
  Parent(CALL): media/js/test.js:3:1
	console.log(listener);

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:208)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:646)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:733)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:640)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:677)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:634)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:347)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:146)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:2046)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:748)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:690)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:687)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable listener
	... 33 more
```

**Comment by Dominator008** [comment]
Can you do a git bisect and see if it's from a recent change?

**Comment by vobruba-martin** [comment]
I tried more than 3 months old commit and it was still broken.

**Comment by brad4d** [comment]
I replicated the failure with a simpler bit of code:

```
var f;
console.log(f = function() { f; });
```

However, these snippets do not trigger the error.

```
var x;
var f;
console.log(f = function() {return x;});
```

```
var f = function() { console.log(f); };
```

So the key problem seems to be assigning to a variable in a function argument and referring to that same variable in the function being assigned there.

**Comment by Dominator008** [comment]
Looks like an ancient known bug in `NameAnalyzer`: https://github.com/google/closure-compiler/blob/4ea798e5f385b568aa07b978035b137960c5081b/test/com/google/javascript/jscomp/NameAnalyzerTest.java#L1252

Haven't found a fix and honestly this is of low priority. Will revisit later.
