### ISSUE TITLE
`IllegalStateException` in closure-compiler-linter-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by ilyaigpetrov** [google/closure-compiler#2049]
I successfully compiled linter with `mvn -DskipTests -pl externs\pom.xml,pom-linter.xml`, but can't launch it the right way:
```
closure-compiler$ java -jar target/closure-compiler-linter-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot set value to a final field 'com.google.javascript.jscomp.Linter.files'.
        at org.kohsuke.args4j.spi.Setters.create(Setters.java:32)
        at org.kohsuke.args4j.ClassParser.parse(ClassParser.java:38)
        at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:96)
        at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:71)
        at com.google.javascript.jscomp.Linter.run(Linter.java:52)
        at com.google.javascript.jscomp.Linter.main(Linter.java:48)
```
Tried in `cmd.exe` and bash for windows.

Maybe there is a way to run linter from closure-compiler? `--checks-only` seems not enough.

**Comment by MatrixFrog** [comment]
You can run the compiler with `--jscomp_warning=lintChecks --checks_only` and that will be reasonably close to what the linter does. But we should fix this. I suspect what happened is that our internal analysis tools "helpfully" pointed out that a field was never assigned and so could be made `final`, without realizing that args4j sets it through reflection.
