### ISSUE TITLE
Compiler crash with  INTERNAL COMPILER ERROR.

### ISSUE THREAD

**Issue by reshadi** [google/closure-compiler#2081]
A simple line of code crashes the compiler. 
To repro:

```
mkdir test
cd test
npm install google-closure-compiler@20160911.0.0
wget https://code.jquery.com/qunit/qunit-2.0.1.js
java -jar ./node_modules/google-closure-compiler/compiler.jar  --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT5 --new_type_inf --summary_detail_level 3 --warning_level QUIET --js_output_file=test.min.js  --summary_detail_level 3 qunit-2.0.1.js
```

Workaround:
converting

``` js
window.onerror = function( error, filePath, linerNr ) {
```

to

``` js
window["onerror"] = function( error, filePath, linerNr ) {
```

resolves the issue.

**Comment by ChadKillingsworth** [comment]
Thanks for the repo case. Can you post the stack trace? It saves us a step.

**Comment by reshadi** [comment]
I think this is a repeat of https://github.com/google/closure-compiler/issues/1513, which was closed already. 
It won't crash after removing the --new_type_inf switch

```
null
  Node(EXPR_RESULT): qunit-2.0.1.js:307:1
        window.onerror = function( error, filePath, linerNr ) {
  Parent(BLOCK): qunit-2.0.1.js:295:13
( function() {

        at com.google.common.base.Preconditions.checkState(Preconditions.java:159)
        at com.google.javascript.jscomp.NTIScope.addNamespace(NTIScope.java:529)
        at com.google.javascript.jscomp.NTIScope.addNamespaceLit(NTIScope.java:491)
        at com.google.javascript.jscomp.GlobalTypeInfo$CollectNamedTypes.mayCreateWindowNamespace(GlobalTypeInfo.java:892)
        at com.google.javascript.jscomp.GlobalTypeInfo$CollectNamedTypes.processQualifiedDefinition(GlobalTypeInfo.java:821)
        at com.google.javascript.jscomp.GlobalTypeInfo$CollectNamedTypes.visit(GlobalTypeInfo.java:786)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:645)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:717)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:732)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:327)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:590)
        at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:373)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:855)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:750)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:698)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:695)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
        ... 25 more

```
