### ISSUE TITLE
goog.reflect.objectProperty causes exceptions in simple mode

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2141]
JSCompiler_renameProperty references cause exceptions in simple mode because it may not be in either source or externs. We either need to remove and replace the calls early in this case or add synthetic definitions.

```
Unexpected variable JSCompiler_renameProperty
  Node(NAME JSCompiler_renameProperty): /src/js/api/controllers/login-controller.js:332:39
      this.model_.listenOnce(`change:${goog.reflect.objectProperty('needsEulaAcceptance', this.model_)}`, evt => {
  Parent(CALL): /src/js/api/controllers/login-controller.js:332:39
      this.model_.listenOnce(`change:${goog.reflect.objectProperty('needsEulaAcceptance', this.model_)}`, evt => {

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:208)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:729)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:636)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:673)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:630)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:344)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:146)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:2176)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:776)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:718)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:715)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable JSCompiler_renameProperty
	... 41 more
```

**Comment by ChadKillingsworth** [comment]
Fixed by 8030b55
