### ISSUE TITLE
Internal compiler error on destructuring in externs

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#2166]
These externs:

```js
/** @constructor */
function Foo() {}

Foo.prototype.bar = function({a}) {};
```

produce

```
null
  Node(NAME ): extern:4:20
Foo.prototype.bar = function({a}) {};
  Parent(FUNCTION ): extern:4:20
Foo.prototype.bar = function({a}) {};

	at com.google.common.base.Preconditions.checkState(Preconditions.java:431)
	at com.google.javascript.jscomp.SyntacticScopeCreator.scanRoot(SyntacticScopeCreator.java:112)
	at com.google.javascript.jscomp.SyntacticScopeCreator.createScope(SyntacticScopeCreator.java:80)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:828)
	at com.google.javascript.jscomp.NodeTraversal.getTypedScope(NodeTraversal.java:844)
	at com.google.javascript.jscomp.TypedScopeCreator$FirstOrderFunctionAnalyzer.visit(TypedScopeCreator.java:2174)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:654)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:674)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:650)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:650)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:650)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:650)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:346)
	at com.google.javascript.jscomp.NodeTraversal.traverseRootsTyped(NodeTraversal.java:624)
	at com.google.javascript.jscomp.TypedScopeCreator$FirstOrderFunctionAnalyzer.process(TypedScopeCreator.java:2141)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:236)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:97)
	at com.google.javascript.jscomp.MemoizedScopeCreator.createScope(MemoizedScopeCreator.java:87)
	at com.google.javascript.jscomp.PassConfig.regenerateGlobalTypedScope(PassConfig.java:68)
	at com.google.javascript.jscomp.DefaultPassConfig$GlobalTypeResolver.process(DefaultPassConfig.java:1854)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:888)
```

https://closure-compiler-debugger.appspot.com/#input0%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250AFoo.prototype.bar%2520%253D%2520function(%257Ba%257D)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26COLLAPSE_PROPERTIES%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26GENERATE_EXPORTS%3D1%26INLINE_VARIABLES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26SMART_NAME_REMOVAL%3D1%26TRANSPILE%3D1%26VARIABLE_RENAMING%3D1

**Comment by MatrixFrog** [comment]
I don't remember if we ever decided if we officially want to allow ES6 constructs like destructuring in externs files. I think we should though. Probably the transpilation pass is just skipping the externs because we assumed at the time that externs would always be ES5.

**Comment by Dominator008** [comment]
What's the point of having destructuring in this particular case though? The parameter name / type is not documented so it will just become:
```js
Foo.prototype.bar = function($jscomp$destructuring$var0) {
  var $jscomp$destructuring$var1 = $jscomp$destructuring$var0;",
  var a = $jscomp$destructuring$var1.a;",
}
```
after transpilation.

**Comment by evmar** [comment]
I think the reason to use destructuring here is to prevent renaming of the parameter, but maybe there's some way to provide that name in the jsdoc to prevent renaming there too?

**Comment by MatrixFrog** [comment]
`/** @param {{a: ?}} arg */` (or `/** @param {{a: number}} arg */`, whatever it is) should do it for now. I do think we should support the destructuring syntax and infer the type to be `{a: ?}` though.

**Comment by evmar** [comment]
(Also, the smaller nice thing to do here would be to give an error message rather than crashing.)

**Comment by Dominator008** [comment]
@MatrixFrog @evmar Inferring `{a: ?}` sounds reasonable.
