### ISSUE TITLE
INTERNAL COMPILER ERROR on destructuring funky type

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#2189]
```js
/**
 * @param {string} a
 * @param {{b: ?<?>}} __1
 */
function x(a, { b }) {
}
```

I think the issue is that the type `?<?>` is nonsense, but the compiler still shouldn't crash.

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

position (1) must be less than the number of elements that remained (1)
  Node(PARAM_LIST): input0:5:10
function x(a, { b }) {
  Parent(FUNCTION x): input0:5:0
function x(a, { b }) {

	at com.google.common.collect.Iterators.get(Iterators.java:810)
	at com.google.common.collect.Iterables.get(Iterables.java:787)
	at com.google.javascript.rhino.JSDocInfo.getParameterNameAt(JSDocInfo.java:1418)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.getTempParameterName(Es6RewriteDestructuring.java:189)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.visitParamList(Es6RewriteDestructuring.java:142)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.shouldTraverse(Es6RewriteDestructuring.java:57)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:628)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:672)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:633)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:717)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:641)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:321)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:591)
	at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:240)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.process(Es6RewriteDestructuring.java:45)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:889)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:782)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:86)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:729)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:726)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:118)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:756)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:726)
	at com.google.javascript.jscomp.Compiler.compileModules(Compiler.java:717)
	at com.google.javascript.jscomp.debugger.CompilationServlet.service(CompilationServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520a%250A%2520*%2520%2540param%2520%257B%257Bb%253A%2520%253F%253C%253F%253E%257D%257D%2520__1%250A%2520*%252F%250Afunction%2520x(a%252C%2520%257B%2520b%2520%257D)%2520%257B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26COLLAPSE_PROPERTIES%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26GENERATE_EXPORTS%3D1%26INLINE_VARIABLES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26SMART_NAME_REMOVAL%3D1%26TRANSPILE%3D1%26VARIABLE_RENAMING%3D1

**Comment by MatrixFrog** [comment]
You are very good at finding these crashes. Thanks!

**Comment by evmar** [comment]
I think I am just unlucky.  :~(  They also are all reduced from larger programs, which is why they're often funny-looking.

**Comment by MatrixFrog** [comment]
As a workaround, you can make sure that the parser warning on `?<?>` is an error, in which case the compilation won't even get to this step. `--jscomp_error=checkTypes` should do it.

**Comment by evmar** [comment]
I have the CHECK_TYPES checkbox on in the debug page, which I think I had imagined was doing something like that.  Does it control something else?

**Comment by MatrixFrog** [comment]
That makes it a warning, not an error. Which means compilation continues even after the warning is reported. No way to make it an error on the debugger :(
