### ISSUE TITLE
"RuntimeException: INTERNAL COMPILER ERROR" when using NTI with Function ctor and const

### ISSUE THREAD

**Issue by Perelandric** [google/closure-compiler#2214]
When NTI is enabled, the compiler crashes if you invoke JavaScript's `Function` constructor, invoke the resulting function immediately, and assign its result to a `const`.

***Minimal example:***

*terminal:*
``` 
> java -jar $CLOSURE --new_type_inf --js test.js
```

*test.js:*
``` javascript
const bar = new Function("")()
```

***Result:***
``` 
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(NAME x): test.js:3:6
const x = new Function("")()
  Parent(VAR): test.js:3:0
const x = new Function("")()

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.javascript.jscomp.newtypes.FunctionType.getReturnType(FunctionType.java:278)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.simpleInferCallNewType(GlobalTypeInfo.java:2029)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.simpleInferExprType(GlobalTypeInfo.java:2087)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.inferConstTypeFromRhs(GlobalTypeInfo.java:1951)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.mayInferFromRhsIfConst(GlobalTypeInfo.java:1932)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visitVar(GlobalTypeInfo.java:1492)
	at com.google.javascript.jscomp.GlobalTypeInfo$ProcessScope.visit(GlobalTypeInfo.java:1397)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:318)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:588)
	at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:440)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:877)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:770)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:718)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:715)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	... 30 more
```

***Version:***
```
> java -jar $CLOSURE --version

Closure Compiler (http://github.com/google/closure-compiler)
Version: v20161201
Built on: 2016-12-02 14:56
```

**Comment by Perelandric** [comment]
Wrapping it in an IIFE seems to serve as a workaround:

``` javascript
const bar = (function() { return new Function("")() })()
```
