### ISSUE TITLE
Bad type annotation warnings for re-exported modules

### ISSUE THREAD

**Issue by traviskaufman** [google/closure-compiler#2257]
Given:

```js
// a.js
export default class A {
  constructor() {
    /** @type {string} */
    this.message = 'Hello';
  }
}
```

```js
// b.js
import A from './a';

export {A};
```

```js
// c.js
import {A} from './b';

class C {
  /**
   * @param {!A} a
   */
  constructor(a) {
    /** @const */
    this.a = a;
  }
}

console.log(new C(new A()).a.message);
```

Running:

```sh
java -jar path/to/compiler.jar \
--compilation_level ADVANCED \
--js *.js \
--language_out ECMASCRIPT5_STRICT \
--entry_point c.js
```

Yields:

```
c.js:5: WARNING - Bad type annotation. Unknown type A$$module$b
   * @param {!A} a
              ^

0 error(s), 1 warning(s), 90.3% typed
'use strict';console.log((new function(a){this.a=a}(new function(){this.message="Hello"})).a.message);
```

It seems that closure is having some issues with types from re-exported modules from a different file. If I change the initial statement in `c.js` to `import A from './a'` the code compiles fine.

p.s. Sorry if this is a dupe; I searched through the current issues but missed anything pertaining to this.

**Comment by ChadKillingsworth** [comment]
Transitive imports/exports like this are very challenging. The compiler has to internally unwind all the aliases created. Currently the module rewrite strategy is to avoid creating aliases whenever possible. In this case, the algorithm creates aliases.

**Comment by traviskaufman** [comment]
> Currently the module rewrite strategy is to avoid creating aliases whenever possible. 

Would you mind elaborating on this?

Since these types of imports are supported in ES2015 and part of the specification, if the module rewrite strategy is to avoid creating aliases, does that mean that there will be parts of the ES2015 module spec that won't be supported?

I'd be happy to help out with this if it's something the team plans on supporting.

**Comment by MatrixFrog** [comment]
I suspect the code we're producing is correct; it just doesn't typecheck well.

I don't expect to have time to look at this in the near future but we should definitely fix it. Sometimes when an alias is annotated `@const` that helps the compiler to understand it's supposed to be treated as an alias. So the first thing I'd try is running this example with `--preserve_type_annotations` and see if we have those `@const` annotations. If not, you can try going into the ProcessEs6Modules class and adding them. See https://github.com/google/closure-compiler/wiki/Writing-Compiler-Pass if you haven't worked in the compiler code base before.

**Comment by traviskaufman** [comment]
Thanks for the input! You're right that the code compiles correctly but the type-checking is off.

Here's the output when running with `--preserve_type_annotations`

```js
'use strict';/**
 @suppress {missingProvide,missingRequire}
 */
;/**
 @suppress {missingProvide,missingRequire}
 */
;/**
 @suppress {missingProvide,missingRequire}
 */
console.log((new function(a){/** @const */ this.a=a}(new {}.b)).a.a);
```

FYI, I believe this is another issue but I also tried modifying `b.js` to export an object containing `A`:


```js
export default {
  A,
}
```

And when I tried to compile, it completely error'd out:

```
java -jar ../node_modules/google-closure-compiler/compiler.jar --compilation_level ADVANCED \
--js *.js \
--language_out ECMASCRIPT5_STRICT \
--entry_point c.js \

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected node type: GETPROP 4 [length: 1] [source_file: b.js]
  Node(OBJECTLIT): b.js:3:15
export default {
  Parent(NAME $jscompDefaultExport$$module$b): b.js:3:0
export default {

	at com.google.javascript.jscomp.NodeUtil.getObjectLitKeyName(NodeUtil.java:3060)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.processObjectLitProperties(TypedScopeCreator.java:692)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.defineObjectLiteral(TypedScopeCreator.java:674)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.attachLiteralTypes(TypedScopeCreator.java:619)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.visit(TypedScopeCreator.java:525)
	at com.google.javascript.jscomp.TypedScopeCreator$GlobalScopeBuilder.visit(TypedScopeCreator.java:1884)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:642)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:714)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:638)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:318)
	at com.google.javascript.jscomp.NodeTraversal.traverseTyped(NodeTraversal.java:593)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:243)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:97)
	at com.google.javascript.jscomp.MemoizedScopeCreator.createScope(MemoizedScopeCreator.java:87)
	at com.google.javascript.jscomp.PassConfig.regenerateGlobalTypedScope(PassConfig.java:68)
	at com.google.javascript.jscomp.DefaultPassConfig$GlobalTypeResolver.process(DefaultPassConfig.java:1854)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:877)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:770)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:718)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:715)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected node type: GETPROP 4 [length: 1] [source_file: b.js]
	... 36 more
```

**Comment by ChadKillingsworth** [comment]
There isn't an obvious fix to this. It's a known/shared problem between all 3 module types: goog.module, ES6 and CommonJS.

Module rewriting occurs per-file and in isolation. Using your above example, the modules would be rewritten to:

```js
// a.js
module$a.default = class A {
  constructor() {
    /** @type {string} */
    this.message = 'Hello';
  }
}
```

```js
// b.js
module$b.default = module$a.default;
```

```js
// c.js
class C {
  /**
   * @param {!module$b.default} a
   */
  constructor(a) {
    /** @const */
    this.a = a;
  }
}

console.log(new C(new A()).a.message);
```

The transitive import/export in b.js creates an alias.

Workarounds:

 1. Avoid transitive import/exports whenever possible by importing the defining module directly.
 2. For type references only, reference the module path in the type annotation.

```js
// c.js
class C {
  /**
   * @param {!/a.default} a - type reference is a module path
   */
  constructor(a) {
    /** @const */
    this.a = a;
  }
}

console.log(new C(new A()).a.message);
```

To support transitive imports/exports would require analyzing across module boundaries. We don't currently do that during module rewriting. We used to rely on the early inlining pass and `@const` annotations to assist with this, but that caused other issues and was removed.

At a minimum, we'd need to be able to identify module import and export statements to know what aliases were safe to unwind in such a later pass.

**Comment by ChadKillingsworth** [comment]
Also - we most very much want to keep all 3 module systems at parity. Any fix/change needs to apply to all 3.
