### ISSUE TITLE
"let this.foo" leads to NullPointerException

### ISSUE THREAD

**Issue by danshaffer** [google/closure-compiler#2284]
We're using io_bazel_rules_closure @ 0.4.0. 

in npe.js
```js
goog.provide('Fun');

/**
* @constructor
 */
let Fun = function() {
	let this.foo_ = 7;
};
```

BUILD:
```bzl
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_binary")

closure_js_binary(
    name = "npe_result",
    language = "ECMASCRIPT5_STRICT",
    deps = [
        ":npe_lib",
    ],
)

closure_js_library(
    name = "npe_lib",
    srcs = [
        "npe.js",
    ],
    language = "ECMASCRIPT6_STRICT",
)
```

Result:
```
ERROR: Worker threw uncaught exception with args: JsChecker --output bazel-out/local_linux-opt/bin/experimental/users/dshaffer/npe_lib-provided.txt --output_errors bazel-out/local_linux-opt/bin/experimental/users/dshaffer/npe_lib-stderr.txt --label //experimental/users/dshaffer:npe_lib --convention CLOSURE --language ECMASCRIPT6_STRICT --src experimental/users/dshaffer/npe.js
java.lang.NullPointerException
        at com.google.javascript.jscomp.parsing.IRFactory.getJsDoc(IRFactory.java:674)
        at com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:758)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processName(IRFactory.java:1454)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processName(IRFactory.java:1442)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processName(IRFactory.java:1438)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2688)
        at com.google.javascript.jscomp.parsing.IRFactory.transformNodeWithInlineJsDoc(IRFactory.java:790)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableDeclaration(IRFactory.java:1979)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2722)
        at com.google.javascript.jscomp.parsing.IRFactory.transformNodeWithInlineJsDoc(IRFactory.java:790)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableDeclarationList(IRFactory.java:1973)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2720)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableStatement(IRFactory.java:1950)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2718)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:763)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBlock(IRFactory.java:1091)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2646)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:763)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processFunction(IRFactory.java:1279)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2674)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:763)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableDeclaration(IRFactory.java:1982)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2722)
        at com.google.javascript.jscomp.parsing.IRFactory.transformNodeWithInlineJsDoc(IRFactory.java:790)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableDeclarationList(IRFactory.java:1973)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2720)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processVariableStatement(IRFactory.java:1950)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2718)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:763)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1020)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2708)
        at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:350)
        at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:136)
        at com.google.javascript.jscomp.JsAst.parse(JsAst.java:142)
        at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:52)
        at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:118)
        at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:1638)
        at com.google.javascript.jscomp.Compiler.orderInputs(Compiler.java:1590)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1525)
        at com.google.javascript.jscomp.Compiler.parse(Compiler.java:794)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:750)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:717)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:714)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:118)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:744)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:714)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:684)
        at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:270)
        at com.google.javascript.jscomp.JsChecker.access$200(JsChecker.java:57)
        at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:331)
        at io.bazel.rules.closure.ClosureUberAlles.apply(ClosureUberAlles.java:41)
        at io.bazel.rules.closure.BazelWorker.runAsPersistentWorker(BazelWorker.java:84)
        at io.bazel.rules.closure.BazelWorker.apply(BazelWorker.java:60)
        at io.bazel.rules.closure.ClosureUberAlles.main(ClosureUberAlles.java:31)
```

**Comment by danshaffer** [comment]
bazelbuild/rules_closure 0.4.0 is using v20161024, hopefully this belongs here and not in that repo.

**Comment by MatrixFrog** [comment]
Doesn't seem to happen at head: https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('Fun')%253B%250A%250A%252F**%250A*%2520%2540constructor%250A%2520*%252F%250Alet%2520Fun%2520%253D%2520function()%2520%257B%250A%2520%2520let%2520this.foo_%2520%253D%25207%253B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

so this might be fixed by just updating rules_closure to a later compiler version.

cc @jart

**Comment by jart** [comment]
I'll get on that right away. @MatrixFrog and @danshaffer.

**Comment by concavelenz** [comment]
@MatrixFrog seem we can close this?

**Comment by MatrixFrog** [comment]
I wish we could transfer this bug over to the rules_closure repo. I'll close it here though, and let @jart open a new bug on the rules_closure side if needed.

**Comment by jart** [comment]
Thank you for your patience @danshaffer. I'd like to share with you [Closure Rules v0.4.1](https://github.com/bazelbuild/rules_closure/releases/tag/0.4.1) which is a minor release updating all the Closure Tools. It should address the issue you encountered.
