### ISSUE TITLE
RuntimeException with  --process_common_js_modules

### ISSUE THREAD

**Issue by drjokepu** [google/closure-compiler#2308]
The following code crashes on the latest master (91fb5ba) with a java.lang.RuntimeException when `--process_common_js_module` is enabled:

```javascript
exports.y = null;

var x;
x = exports.y;
```
```
$ java -jar closure-compiler-1.0-SNAPSHOT.jar --js test.js --process_common_js_modules
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(SCRIPT): test.js:1:0
exports.y = null;
  Parent: NULL
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:752)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:722)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:692)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1906)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(SCRIPT): test.js:1:0
exports.y = null;
  Parent: NULL
        at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.visitExport(ProcessCommonJSModules.java:774)
        at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.visit(ProcessCommonJSModules.java:635)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:643)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:316)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:586)
        at com.google.javascript.jscomp.ProcessCommonJSModules.process(ProcessCommonJSModules.java:128)
        at com.google.javascript.jscomp.Compiler.processAMDAndCommonJSModules(Compiler.java:1841)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1549)
        at com.google.javascript.jscomp.Compiler.parse(Compiler.java:809)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:762)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:88)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:725)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:722)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        ... 18 more
```

```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

$ javac -version
javac 1.8.0_121
```

Let me know if any further details are needed.

**Comment by ChadKillingsworth** [comment]
Closed by 77b7ea0
