### ISSUE TITLE
NTI v20170124 --new_type_inf with --jscomp_erorr=* causes INTERNAL COMPILER ERROR

### ISSUE THREAD

**Issue by hochhaus** [google/closure-compiler#2333]
When using v20170124 with --new_type_inf with --jscomp_erorr=* to compile closure-library's base.js I receive the following INTERNAL COMPILER ERROR. However, this works without an error on the v20161201 compiler.

```
ahochhaus@ahochhaus-pc:~/closure$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-3-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
ahochhaus@ahochhaus-pc:~/closure$ ls
closure-compiler-v20161201.jar  closure-compiler-v20170124.jar  closure-library-20170124
ahochhaus@ahochhaus-pc:~/closure$ java -jar closure-compiler-v20170124.jar --hide_warnings_for=closure-library-20170124/ --jscomp_error=* --new_type_inf closure-library-20170124/closure/goog/base.js 
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(GETPROP): closure-library-20170124/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;
  Parent(EXPR_RESULT): closure-library-20170124/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:740)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:710)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:680)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1866)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(GETPROP): closure-library-20170124/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;
  Parent(EXPR_RESULT): closure-library-20170124/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;

	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.javascript.jscomp.newtypes.NominalType.getRawNominalType(NominalType.java:59)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getNamedTypeHelper(JSTypeCreatorFromJSDoc.java:427)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromCommentHelper(JSTypeCreatorFromJSDoc.java:297)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromComment(JSTypeCreatorFromJSDoc.java:274)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeOfCommentNode(JSTypeCreatorFromJSDoc.java:239)
	at com.google.javascript.jscomp.GlobalTypeInfo.createTypeFromCommentNode(GlobalTypeInfo.java:2726)
	at com.google.javascript.jscomp.ImplicitNullabilityCheck$2.visit(ImplicitNullabilityCheck.java:121)
	at com.google.javascript.jscomp.NodeUtil.visitPreOrder(NodeUtil.java:3976)
	at com.google.javascript.jscomp.NodeUtil.visitPreOrder(NodeUtil.java:3980)
	at com.google.javascript.jscomp.ImplicitNullabilityCheck.visit(ImplicitNullabilityCheck.java:80)
	at com.google.javascript.jscomp.CombinedCompilerPass$CallbackWrapper.visitOrMaybeActivate(CombinedCompilerPass.java:123)
	at com.google.javascript.jscomp.CombinedCompilerPass.visit(CombinedCompilerPass.java:178)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:643)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:316)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:586)
	at com.google.javascript.jscomp.CombinedCompilerPass.process(CombinedCompilerPass.java:154)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:873)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:766)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:713)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:710)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
	... 35 more
ahochhaus@ahochhaus-pc:~/closure$ java -jar closure-compiler-v20161201.jar --hide_warnings_for=closure-library-20170124/ --jscomp_error=* --new_type_inf closure-library-20170124/closure/goog/base.js > /dev/null
ahochhaus@ahochhaus-pc:~/closure$ echo $?
0
ahochhaus@ahochhaus-pc:~/closure$ 
```

**Comment by hochhaus** [comment]
This bug is fixed in v20170218 of the compiler.
