### ISSUE TITLE
goog.module, ES6 and CommonJS interop issue

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2360]
I am encountering a couple of errors importing an ES6 module into a goog.module using CommonJS syntax. I'm doing this because currently I used the internal $ based module name, which is not recommended, and according to the wiki, the following is the correct way to achieve this.

(I'm using the "legacy" value for the new module resolution option, with cjs modules enabled and "/" module prefix.)

File A (ES6):
``` javascript
export default {
    someProp: {}
};
```
File B (goog.module):
``` javascript
goog.module("namespace.B");
//goog.module.declareLegacyNamespace();
const _A = require("/A");
const A = _A.default;
...
```

I get `INTERNAL COMPILER ERROR` 
with node `VAR` for `const _A`, parent `MODULE_BODY` for `goog.module...`
and node `MODULE_BODY` with parent `SCRIPT`:
```
	at com.google.common.base.Preconditions.checkState(Preconditions.java:430)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.assertDefinitionNode(TypedScopeCreator.java:766)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.defineVar(TypedScopeCreator.java:785)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.visit(TypedScopeCreator.java:559)
	at com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder.visit(TypedScopeCreator.java:2012)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:711)
	at com.google.javascript.jscomp.NodeTraversal.traverseModule(NodeTraversal.java:719)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:311)
	at com.google.javascript.jscomp.NodeTraversal.traverseTyped(NodeTraversal.java:587)
	at com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder.build(TypedScopeCreator.java:1959)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:248)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:97)
	at com.google.javascript.jscomp.MemoizedScopeCreator.createScope(MemoizedScopeCreator.java:87)
	at com.google.javascript.jscomp.MemoizedScopeCreator.createScope(MemoizedScopeCreator.java:47)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:806)
	at com.google.javascript.jscomp.NodeTraversal.getTypedScope(NodeTraversal.java:822)
	at com.google.javascript.jscomp.TypeInferencePass$FirstScopeBuildingCallback.enterScope(TypeInferencePass.java:133)
	at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:753)
	at com.google.javascript.jscomp.NodeTraversal.traverseModule(NodeTraversal.java:718)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:711)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:635)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:711)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:635)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:711)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:635)
	at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:366)
	at com.google.javascript.jscomp.TypeInferencePass.inferAllScopes(TypeInferencePass.java:103)
	at com.google.javascript.jscomp.TypeInferencePass.process(TypeInferencePass.java:73)
	at com.google.javascript.jscomp.DefaultPassConfig$45$1.process(DefaultPassConfig.java:1685)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:298)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:891)
```

It seems sourceName isn't initialised, presumably because the AST still has a MODULE_BODY rather than script or function node in TypedScopeCreator:494.

Then, if I uncomment `declareLegacyNamespace`, I get `ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.` at line 1.  Debugging, it seems the file now has a virtual goog.provide in it.

The leading slash in the `require` seems to make no difference to any of this if I remove it.

I tried to reproduce this in the debugger, but it doesn't expose options for CJS module processing. I don't think I can create a public test case, but can debug this if directed.

**Comment by teppeis** [comment]
This is similar reproducing code: https://github.com/teppeis/closure-compiler-errors/tree/require-in-goog-module

Simply, this code causes the error.
```js
goog.module('loadFromGoogModule');
require('./cjs1');
```

**Comment by teppeis** [comment]
@supersteves It seems to have been fixed in v20170626.
