### ISSUE TITLE
Missing var in try block causes internal compiler error

### ISSUE THREAD

**Issue by bnkuhn** [google/closure-compiler#2388]
Compiling this code with simple optimizations:

```
(function() {
  try {
    x = 2; 
  } catch(e) {
    var x = 1;
  }
})();
```

Causes a runtime exception in the compiler:

```
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

Unexpected variable x
  Node(NAME x): input0:4:4
    x = 2;
  Parent(ASSIGN): input0:4:4
    x = 2;

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:763)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:733)
	at com.google.javascript.jscomp.Compiler.compileModules(Compiler.java:724)
	at com.google.javascript.jscomp.debugger.CompilationServlet.service(CompilationServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:635)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:595)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:565)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

Unexpected variable x
  Node(NAME x): input0:4:4
    x = 2;
  Parent(ASSIGN): input0:4:4
    x = 2;

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:208)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:643)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:730)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:637)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:730)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:637)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:674)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:333)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:146)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:298)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:2239)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:797)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:90)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:736)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:733)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:116)
	... 39 more
Caused by: java.lang.IllegalStateException: Unexpected variable x
	... 73 more
```

**Comment by MatrixFrog** [comment]
The work-in-progress change that I _think_ will fix this, should be submitted next week. Thank you for the reminder to add this as a test case.
