### ISSUE TITLE
StringIndexOutOfBoundsException with empty conformance_config

### ISSUE THREAD

**Issue by Yannic** [google/closure-compiler#2393]
The compiler crashes on the latest master f9c738e with an empty conformance configs file.

`java -jar closure-compiler/target/closure-compiler-1.0-SNAPSHOT.jar --conformance_configs "js_conformance.txt`

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.google.javascript.jscomp.CommandLineRunner.loadConformanceConfig(CommandLineRunner.java:1757)
	at com.google.javascript.jscomp.CommandLineRunner.loadConformanceConfigs(CommandLineRunner.java:1741)
	at com.google.javascript.jscomp.CommandLineRunner.createOptions(CommandLineRunner.java:1683)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1008)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1887)
```

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L1757

So we could probably just do

    if (!textProto.isEmpty() && textProto.charAt(0) == ...

**Comment by MatrixFrog** [comment]
(Do people actually use the BOM character much in UTF-8 encoded files?)

**Comment by Yannic** [comment]
Close because of 3c7e125
