### ISSUE TITLE
INTERNAL COMPILER ERROR with branch coverage enabled

### ISSUE THREAD

**Issue by ribrdb** [google/closure-compiler#2459]
I compiled with
       options.setInstrumentForCoverage(true);
      options.setInstrumentBranchCoverage(true);

java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(FOR): external/com_google_javascript_closure_library/closure/goog/base.js:134:2
  for (var part; parts.length && (part = parts.shift());) {
  Parent(BLOCK): external/com_google_javascript_closure_library/closure/goog/base.js:117:68
goog.exportPath_ = function(name, opt_object, opt_objectToExportTo) {

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:740)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:710)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:680)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
	at com.google.javascript.jscomp.JsCompilerRunner.go(JsCompilerRunner.java:47)
	at com.google.javascript.jscomp.JsCompiler.run(JsCompiler.java:198)
	at com.google.javascript.jscomp.JsCompiler.apply(JsCompiler.java:82)
	at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
	at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:72)
	at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
	at io.bazel.rules.closure.worker.PersistentWorker.runAsPersistentWorker(PersistentWorker.java:144)
	at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:84)
	at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(FOR): external/com_google_javascript_closure_library/closure/goog/base.js:134:2
  for (var part; parts.length && (part = parts.shift());) {
  Parent(BLOCK): external/com_google_javascript_closure_library/closure/goog/base.js:117:68
goog.exportPath_ = function(name, opt_object, opt_objectToExportTo) {

	at com.google.javascript.jscomp.BranchCoverageInstrumentationCallback.visit(BranchCoverageInstrumentationCallback.java:89)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:643)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:730)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:637)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:674)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:316)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:586)
	at com.google.javascript.jscomp.CoverageInstrumentationPass.process(CoverageInstrumentationPass.java:87)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:2175)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:772)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:713)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:710)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	... 30 more

**Comment by MatrixFrog** [comment]
Branch coverage was mostly implemented by a 20%er. That person is going to take a look.
