### ISSUE TITLE
CommonJS module - Internal compiler error

### ISSUE THREAD

**Issue by kommen** [google/closure-compiler#2507]
When consuming the [`entities`](https://www.npmjs.com/package/entities) npm with `--module_resolution NODE --process_common_js_modules` the compiler throws an internal error:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(NAME decodeHTMLStrict): node_modules/entities/lib/decode.js:7:4
    decodeHTMLStrict = getStrictDecoder(entityMap);
  Parent(VAR): node_modules/entities/lib/decode.js:6:0
var decodeXMLStrict  = getStrictDecoder(xmlMap),

	at com.google.javascript.rhino.Node.replaceWith(Node.java:867)
	at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.updateNameReference(ProcessCommonJSModules.java:1064)
	at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.maybeUpdateName(ProcessCommonJSModules.java:943)
	at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.visit(ProcessCommonJSModules.java:705)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:629)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:579)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:604)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:553)
	at com.google.javascript.jscomp.ProcessCommonJSModules.process(ProcessCommonJSModules.java:127)
	at com.google.javascript.jscomp.Compiler.processAMDAndCommonJSModules(Compiler.java:2120)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1811)
	at com.google.javascript.jscomp.Compiler.parseForCompilationInternal(Compiler.java:1024)
	at com.google.javascript.jscomp.Compiler.access$300(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$7.call(Compiler.java:1004)
	at com.google.javascript.jscomp.Compiler$7.call(Compiler.java:1001)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	... 24 more
```

To reproduce:
1) extract the attached demo [entities-error-demo.zip](https://github.com/google/closure-compiler/files/1028458/entities-error-demo.zip)
2) put an `closure-compiler-v20170521.jar` into the directory
3) run `build.sh`

This originally came up in ClojureScript here: https://dev.clojure.org/jira/browse/CLJS-2048

**Comment by MatrixFrog** [comment]
Crash bugs are often a "good first bug" for someone wanting to jump into this codebase.

**Comment by kommen** [comment]
This seems to be the same issue as #2450. Closing this in favor of that.
