### ISSUE TITLE
ECMAScript6 Compile Failures

### ISSUE THREAD

**Issue by protosam** [google/closure-compiler#2519]
Just read the EMCAScript6 page and figured this was supported now... I'm kinda doing some janky stuff anyway I guess... not really sure how to proceed with this.

Error Output:
```
sam@sam:~/hellogap/www/js$ java -jar ~/Downloads/closure-compiler-v20170521.jar --js dompackage.js --js_output_file dompackage.min.js
dompackage.js:149574: WARNING - Class level JSDocs (@interface, @extends, etc.) are not allowed on class members
        constructor(description) {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^

dompackage.js:45951: ERROR - @nosideeffects may only appear in externs files.
CSSOM.clone = function clone(stylesheet) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 1 warning(s)
sam@sam:~/hellogap/www/js$ java -jar ~/Downloads/closure-compiler-v20170521.jar --compilation_level WHITESPACE_ONLY --js dompackage.js --js_output_file dompackage.min.js
dompackage.js:84755: ERROR - This code cannot be converted from ES6. extending native class: Array
  constructor() {
  ^^^^^^^^^^^^^^^

dompackage.js:85688: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:87812: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:88003: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:88572: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:89079: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:101403: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:101726: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:102397: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:102618: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:104418: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:104641: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:105219: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:109367: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    return super._attrModified.apply(this, arguments);
           ^^^^^

dompackage.js:109688: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._attrModified.apply(this, arguments);
    ^^^^^

dompackage.js:109819: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._descendantAdded.apply(this, arguments);
    ^^^^^

dompackage.js:109829: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._descendantRemoved.apply(this, arguments);
    ^^^^^

dompackage.js:110664: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._attrModified.apply(this, arguments);
    ^^^^^

dompackage.js:111438: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._attrModified.apply(this, arguments);
    ^^^^^

dompackage.js:111788: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._descendantAdded.apply(this, arguments);
    ^^^^^

dompackage.js:111796: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._descendantRemoved.apply(this, arguments);
    ^^^^^

dompackage.js:111803: ERROR - ES6 transpilation of 'Only calls to super or to a method of super are supported.' is not yet implemented.
    super._attrModified.apply(this, arguments);
    ^^^^^

dompackage.js:115060: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
  if (!new.target) {
       ^^^^^^^^^^

dompackage.js:115095: ERROR - ES6 transpilation of 'new.target' is not yet implemented.
      if (!new.target) {
           ^^^^^^^^^^

24 error(s), 0 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

GETPROP 109367 [length: 25] [source_file: dompackage.js]
  Node(SUPER): dompackage.js:109367:11
    return super._attrModified.apply(this, arguments);
  Parent(GETPROP): dompackage.js:109367:11
    return super._attrModified.apply(this, arguments);

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.javascript.jscomp.Es6ConvertSuperConstructorCalls.shouldTraverse(Es6ConvertSuperConstructorCalls.java:65)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:612)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:716)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:660)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:591)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:607)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:716)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:660)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:591)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:607)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:625)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:716)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:660)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:591)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:607)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:701)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:579)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:604)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:553)
	at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:252)
	at com.google.javascript.jscomp.Es6ConvertSuperConstructorCalls.process(Es6ConvertSuperConstructorCalls.java:489)
	at com.google.javascript.jscomp.Compiler.transpileAndDontCheck(Compiler.java:1088)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:911)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:848)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:845)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: GETPROP 109367 [length: 25] [source_file: dompackage.js]
	... 60 more

```

I'm trying to specificly compile this. 
[dompackage.js.zip](https://github.com/google/closure-compiler/files/1046414/dompackage.js.zip)

It is a part of some witchcraft that I'm working on here:
[www.zip](https://github.com/google/closure-compiler/files/1046418/www.zip)

**Comment by brad4d** [comment]
@protosam 
Thanks for the error report.

The error message says to report this as a problem, but I expect the crash occurred as a side-effect of the other errors reported before it. We'd need a clear, small reproduction case to investigate further. Feel free to reopen this bug or file a new one if you come up with such a case.

FYI regarding the errors reported:

* We have no plans support writing a class that extends Array. It doesn't work now because disallowing `[]` access to objects is an important protection provided by the compiler. Making an exception for things that extend `Array` as long as the index is a number would be nice, but it's not on our current roadmap.
* Transpilation of `new.target` is problematic, and we don't currently have a plan to support it. We're working to allow ES6 output, which will allow it of course, but at the price of not working on older browsers.
* There's an open PR #2418 that should fix the errors about `super.someMethod.apply(...)` when it is completed.
