### ISSUE TITLE
Issues with ExportTestFunctions

### ISSUE THREAD

**Issue by Yannic** [google/closure-compiler#2563]
I recently found out about the `ExportTestFunctions`-pass which can compile test cases and make it possible to run ES6-code and ES6-tests in non-ES6-browsers.  
I found some issues while I tried to make it work:

- Not all valid definitions of ES6-classes are exported. [Here](https://github.com/Yannic/closure-compiler/blob/exportTestFunction/test/com/google/javascript/jscomp/ExportTestFunctionsTest.java) are some tests and a fix for this. I will create a PR for this later.
```javascript
// Classes like this will be exported.
class MyTest1 {setUp() {}};

// Classes like this will not be exported.
const MyTest2 = class {setUp() {}};
```
- The compiler crashes if a test is defined like this:
```javascript
testBar = function() {};
```

**Comment by MatrixFrog** [comment]
I think we had some discussion about this a while back, and we decided to allow classes but only when passed to `goog.testing.testSuite`, though I'm not sure that was ever implemented.

What's the crash stack trace look like?

**Comment by Yannic** [comment]
This is the crash stack trace for `v20170626`. It was the same for current master since the file was not modified since the release:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

String index out of range: -2
  Node(ASSIGN): test.js:1:0
testFunc = function() {}
  Parent(EXPR_RESULT): test.js:1:0
testFunc = function() {}

	at java.lang.String.substring(String.java:1931)
	at com.google.javascript.jscomp.NodeUtil.getPrototypePropertyName(NodeUtil.java:3837)
	at com.google.javascript.jscomp.ExportTestFunctions.exportTestFunctionAsProperty(ExportTestFunctions.java:204)
	at com.google.javascript.jscomp.ExportTestFunctions.access$100(ExportTestFunctions.java:30)
	at com.google.javascript.jscomp.ExportTestFunctions$ExportTestFunctionsNodes.visit(ExportTestFunctions.java:91)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:730)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:680)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:705)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:307)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:647)
	at com.google.javascript.jscomp.ExportTestFunctions.process(ExportTestFunctions.java:175)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:233)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1084)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:884)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:818)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:815)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	... 28 more
```

There is a check for `goog.testing.testSuite`, but as far as I understand it only exports object literals.

**Comment by MatrixFrog** [comment]
Are there still issues to address here?
