### ISSUE TITLE
INTERNAL COMPILER ERROR while using ES6 classes in externs

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2577]
`java -jar closure-compiler-v20170626.jar --js main.js --externs=externs.js --compilation_level=ADVANCED_OPTIMIZATIONS`

```
// main.js is empty
// externs.js
class Config {
	/** @return {number} */
	get flags() {}
}
```

compiler output 
```
externs.js:1: ERROR - variable $jscomp is undeclared
class Config {
^^^^^^^^^^^^^^^

1 error(s), 0 warning(s), 86.4% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable $jscomp
  Node(NAME $jscomp): externs.js:1:0
class Config {
  Parent(GETPROP): externs.js:1:0
class Config {

	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:207)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:730)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:680)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:705)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:323)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:233)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2459)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:844)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:840)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Unexpected variable $jscomp
	... 29 more
```

**Comment by ChadKillingsworth** [comment]
Externs currently need written in ES5 syntax.
