### ISSUE TITLE
java.lang.IllegalStateException: Unknown precedence for EXPR_RESULT

### ISSUE THREAD

**Issue by mayankdevapplift** [google/closure-compiler#2592]
Hi 

This is the stack trace

java.lang.IllegalStateException: Unknown precedence for EXPR_RESULT
at com.google.javascript.jscomp.NodeUtil.precedence(NodeUtil.java:1632)
at com.google.javascript.jscomp.CodeGenerator.precedence(CodeGenerator.java:1264)
at com.google.javascript.jscomp.CodeGenerator.opRequiresParentheses(CodeGenerator.java:1579)
at com.google.javascript.jscomp.CodeGenerator.addExpr(CodeGenerator.java:1556)
at com.google.javascript.jscomp.CodeGenerator.addArrayList(CodeGenerator.java:1666)
at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:281)
at com.google.javascript.jscomp.CodeGenerator.addExpr(CodeGenerator.java:1561)
at com.google.javascript.jscomp.CodeGenerator.addList(CodeGenerator.java:1608)
at com.google.javascript.jscomp.CodeGenerator.addList(CodeGenerator.java:1593)
at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:821)
at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:934)
at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:638)
at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:106)
at com.google.javascript.jscomp.CodePrinter.toSource(CodePrinter.java:875)
at com.google.javascript.jscomp.CodePrinter.access$300(CodePrinter.java:42)
at com.google.javascript.jscomp.CodePrinter$Builder.build(CodePrinter.java:821)

I am getting the error when I am using this library for calculating the code coverage using jscover.
Is it the problem with closure-compiler?

**Comment by tntim96** [comment]
I think it's a problem with JSCover. Ill take a look in https://github.com/tntim96/JSCover/issues/260.
