### ISSUE TITLE
INTERNAL COMPILER ERROR

### ISSUE THREAD

**Issue by JohannBlake** [google/closure-compiler#2602]
The following exception gets generated for this line of code:

`async function createHeader(paneHeaderInfo) {...}`

```
scripts/ui/content-panes/pane-headers/ph-source-stats/ph-source-stats.js:22: WARNING - Parse error. this language feature is only supported for ECMASCRIPT8 mode or better: async function
    async function createHeader(paneHeaderInfo) {
    ^

scripts/ui/content-panes/pane-headers/ph-source-stats/ph-source-stats.js:26: WARNING - Parse error. this language feature is only supported for ECMASCRIPT8 mode or better: async function
        return await new Promise(function (resolve, reject) {
               ^

0 error(s), 2 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

async functions should have already been converted
  Node(FUNCTION createHeader): scripts/ui/content-panes/pane-headers/ph-source-stats/ph-source-stats.js:22:4
    async function createHeader(paneHeaderInfo) {
  Parent(BLOCK): scripts/ui/content-panes/pane-headers/ph-source-stats/ph-source-stats.js:1:57
ROOTNS.ui.components.content.panes.headers = function () {

        at com.google.javascript.jscomp.Es6ToEs3Converter.shouldTraverse(Es6ToEs3Converter.java:111)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:691)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:708)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:817)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:724)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:761)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:692)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:708)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:726)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:680)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:705)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:307)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:647)
        at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:342)
        at com.google.javascript.jscomp.Es6ToEs3Converter.process(Es6ToEs3Converter.java:83)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:233)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1084)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:884)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:818)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:815)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: async functions should have already been converted
        ... 32 more


```

**Comment by dimvar** [comment]
To use async functions you should use the flag `--language_in=ECMASCRIPT8`.

**Comment by JohannBlake** [comment]
@dimvar I tried using:

> --language_in=ECMASCRIPT8

That results in a compiler error: 

> Unknown language 'ECMASCRIPT8' specified.

I am using the latest version of the compiler. The setting that I am currently using is:

> --language_in=ES6_Strict

**Comment by ChadKillingsworth** [comment]
Use `ECMASCRIPT_NEXT`. A release hasn't happened since `ECMASCRIPT8` was added.
