### ISSUE TITLE
NullPointerException in ProcessDefines.overrideDefines

### ISSUE THREAD

**Issue by kommen** [google/closure-compiler#2629]
Since upgrading to Closure Compiler v20170806 (using ClojureScript 1.9.908, which depends on that version) I'm getting an exception when compiling our project with simple optimizations.

```
                                       java.lang.Thread.run              Thread.java:  745
           java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
            java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                          java.util.concurrent.FutureTask.run          FutureTask.java:  266
         com.google.javascript.jscomp.CompilerExecutor$2.call    CompilerExecutor.java:  101
                 com.google.javascript.jscomp.Compiler$3.call            Compiler.java:  830
                 com.google.javascript.jscomp.Compiler$3.call            Compiler.java:  834
   com.google.javascript.jscomp.Compiler.performOptimizations            Compiler.java: 2421
          com.google.javascript.jscomp.PhaseOptimizer.process      PhaseOptimizer.java:  231
com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process      PhaseOptimizer.java:  305
  com.google.javascript.jscomp.DefaultPassConfig$57$1.process   DefaultPassConfig.java: 2154
          com.google.javascript.jscomp.ProcessDefines.process      ProcessDefines.java:  120
  com.google.javascript.jscomp.ProcessDefines.overrideDefines      ProcessDefines.java:  134
```

I wasn't able yet to produce a simple test case yet and I'm not entirely sure if this is a problem from the Closure compiler or how ClojureScript uses it. But as the relevant code section was changed since the latest release in e9db5c87398390d53f04738751b8aa51b2324c2c, this looks to be on the Closure compiler side.

From some basic poking it looks like `info.initialValue` is `null` when procesing the `COMPILED` define. 

Will post here when/if I find out more, but I wanted to file what I have so far, maybe somebody has an idea what could be the culprit?

**Comment by kommen** [comment]
One more note: this only happens when ClojureScript's `:infer-externs` is turned on.

**Comment by blickly** [comment]
Hmm, it's not really clear from the commit diff, but the only real change
in that commit is whether or not the lines after the for loop are executed
in the checkOnly case.

**Comment by mfikes** [comment]
@kommen It might be worth trying ClosureScript master. In particular, with this downstream commit, things appear to work for a very similar stack trace: https://github.com/clojure/clojurescript/commit/30bc7c2ef251d74c2ab398c2a1461984f9c80469

The stack trace involved is
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.javascript.jscomp.ProcessDefines.overrideDefines(ProcessDefines.java:140)
	at com.google.javascript.jscomp.ProcessDefines.process(ProcessDefines.java:125)
	at com.google.javascript.jscomp.DefaultPassConfig$57$1.process(DefaultPassConfig.java:2272)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2541)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:833)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:829)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

with this being reproed in https://github.com/pesterhazy/see-el-jay-ess (as of this commit `09d0fd1f2724294dc9c20fd06614f12fc3bbc187`) via 

```
scripts/run-test-deps --infer
```
