### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by coot** [google/closure-compiler#2635]
The following command:
```
java -jar ~/.node/lib/node_modules/google-closure-compiler/compiler.jar --js 'output/*/*.js' --entry_point output/Prelude/index.js  --js_output_file prelude.js -O ADVANCED --module_resolution NODE --process_common_js_modules
```
Results in an `INTERNAL COMPILER ERROR` which referes to the following js code:
```
var Show = function (show) {
    this.show = show;
};
```

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Invalid node in lhs of declaration: GETPROP 4 [length: 34] [originalname: show] [source_file: output/Data.Show/index.js]
  Node(NAME ): output/Data.Show/index.js:4:11
var Show = function (show) {
  Parent(FUNCTION ): output/Data.Show/index.js:4:11
var Show = function (show) {

	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at com.google.javascript.jscomp.NodeUtil.getLhsNodesHelper(NodeUtil.java:3783)
	at com.google.javascript.jscomp.NodeUtil.getLhsNodesHelper(NodeUtil.java:3759)
	at com.google.javascript.jscomp.NodeUtil.getLhsNodesOfDeclaration(NodeUtil.java:3797)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:190)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.populate(Es6SyntacticScopeCreator.java:143)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:92)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:895)
	at com.google.javascript.jscomp.ReferenceCollectingCallback.visit(ReferenceCollectingCallback.java:166)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:751)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:693)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:709)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:803)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:727)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:803)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:727)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:803)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:681)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:706)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:803)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:727)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:326)
	at com.google.javascript.jscomp.ReferenceCollectingCallback.process(ReferenceCollectingCallback.java:113)
	at com.google.javascript.jscomp.VariableReferenceCheck.process(VariableReferenceCheck.java:114)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:305)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1072)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:874)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:808)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:805)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Invalid node in lhs of declaration: GETPROP 4 [length: 34] [originalname: show] [source_file: output/Data.Show/index.js]
	... 37 more
```

[PureScript](https://github.com/purescript/purescript) compiler generates this kind of code.

_closure version_
```
Version: v20170806
Built on: 2017-08-09 13:35
```

**Comment by coot** [comment]
issue #2616 might be related

**Comment by lauraharker** [comment]
Can you check if 9d2c0de fixed your issue?

**Comment by coot** [comment]
Unfortunately not.
