### ISSUE TITLE
Closure Compiler Service Problem

### ISSUE THREAD

**Issue by blooddy** [google/closure-compiler#2646]
23: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(RETURN): Input_0:367:2
		return assign(
  Parent(BLOCK): Input_0:350:95
	var requestAnimationFrame = getNativeFunction( window.requestAnimationFrame ) || ( function() {

	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.processObjectLitProperties(TypedScopeCreator.java:698)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.defineObjectLiteral(TypedScopeCreator.java:677)
	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.visit(TypedScopeCreator.java:580)
	at com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder.visit(TypedScopeCreator.java:2009)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:735)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:766)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:697)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:713)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:312)
	at com.google.javascript.jscomp.NodeTraversal.traverseTyped(NodeTraversal.java:664)
	at com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder.build(TypedScopeCreator.java:1956)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:251)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:100)
	at com.google.javascript.jscomp.MemoizedTypedScopeCreator.createScope(MemoizedTypedScopeCreator.java:88)
	at com.google.javascript.jscomp.MemoizedTypedScopeCreator.createScope(MemoizedTypedScopeCreator.java:48)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:899)
	at com.google.javascript.jscomp.NodeTraversal.getTypedScope(NodeTraversal.java:932)
	at com.google.javascript.jscomp.TypeInferencePass$FirstScopeBuildingCallback.enterScope(TypeInferencePass.java:133)
	at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:848)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:750)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:697)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:713)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:766)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:697)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:713)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:685)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:710)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:807)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:731)
	at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:367)
	at com.google.javascript.jscomp.TypeInferencePass.inferAllScopes(TypeInferencePass.java:103)
	at com.google.javascript.jscomp.TypeInferencePass.process(TypeInferencePass.java:73)
	at com.google.javascript.jscomp.DefaultPassConfig$44$1.process(DefaultPassConfig.java:1882)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:305)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1092)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:894)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:104)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:828)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:825)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:882)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:824)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:741)
	at com.google.javascript.jscomp.webservice.backend.CompilerInvokerImpl.compile(CompilerInvokerImpl.java:46)
	at com.google.javascript.jscomp.webservice.backend.ServerController.executeRequest(ServerController.java:179)
	at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.serviceParsedRequest(CompilationRequestHandler.java:178)
	at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.service(CompilationRequestHandler.java:160)
	at com.google.javascript.jscomp.webservice.frontend.CompilationServlet.doPost(CompilationServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:219)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:108)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:650)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:582)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:776)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	... 108 more

**Comment by lauraharker** [comment]
Thanks for the report. Can you give us some more context so that we can reproduce the problem, or find a workaround?
