### ISSUE TITLE
INTERNAL COMPILER ERROR with class

### ISSUE THREAD

**Issue by pandanoir** [google/closure-compiler#2666]
I tried to compile below code. However, INTERNAL COMPILER ERROR occurred.

```javascript
class Hoge {
    constructor() {
        this.obj = {z: 'foobar'};
        for (const [alphabet, type] of [['abcde', 'foo,bar'], ['fghij', 'baz']]) {
            for (let i = 0, _i = alphabet.length; i < _i; i++) {
                const s = alphabet[i];
                if (!this.obj[s]) this.obj[s] = type;
                this.obj[s].split(',').map(s => s + '12345'[i]);
            }
        }
    }
}
```

But compiling little different code below caused no error.

```javascript
const obj = {z: 'foobar'};
for (const [alphabet, type] of [['abcde', 'foo,bar'], ['fghij', 'baz']]) {
    for (let i = 0, _i = alphabet.length; i < _i; i++) {
        const s = alphabet[i];
        if (!obj[s]) obj[s] = type;
        obj[s].split(',').map(s => s + '12345'[i]);
    }
}
```

There is no important difference. Why Closure Compiler causes INTERNAL COMPILER ERROR? Is this a bug?

This is a full error message.
```
# yarn minify
yarn minify v1.0.2
$ gulp minify
[15:27:45] Using gulpfile /path/to/gulpfile.js
[15:27:45] Starting 'minify'...
[15:27:45] Finished 'minify' after 8.91 ms

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: Command failed: java -jar -XX:-TieredCompilation /path/to/node_modules/google-closure-compiler/compiler.jar --flagfile="/tmp/9f45c583-3bc5-4051-9170-e92d1e428f02" --compilation_level=SIMPLE_OPTIMIZATIONS --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --warning_level=QUIET --js_output_file="typing.min.js"
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(FOR): dist/typing.js:6:12
            for (let i = 0, _i = alphabet.length; i < _i; i++) {
  Parent(BLOCK): dist/typing.js:5:81
        for (const [alphabet, type] of [['abcde', 'foo,bar'], ['fghij', 'baz']]) {

        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.javascript.jscomp.DeadAssignmentsElimination.exitScope(DeadAssignmentsElimination.java:85)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:724)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:715)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:666)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:664)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:664)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:609)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:655)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:607)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
        at com.google.javascript.jscomp.DeadAssignmentsElimination.process(DeadAssignmentsElimination.java:66)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:458)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1937)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:694)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalArgumentException
        ... 32 more

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dimvar** [comment]
There is not enough information here to reproduce the issue. Compiling this code in simple mode using the [web service](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250Aclass%2520Hoge%2520%257B%250A%2520%2520%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.obj%2520%253D%2520%257Bz%253A%2520'foobar'%257D%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520for%2520(const%2520%255Balphabet%252C%2520type%255D%2520of%2520%255B%255B'abcde'%252C%2520'foo%252Cbar'%255D%252C%2520%255B'fghij'%252C%2520'baz'%255D%255D)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520for%2520(let%2520i%2520%253D%25200%252C%2520_i%2520%253D%2520alphabet.length%253B%2520i%2520%253C%2520_i%253B%2520i%252B%252B)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520const%2520s%2520%253D%2520alphabet%255Bi%255D%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520if%2520(!this.obj%255Bs%255D)%2520this.obj%255Bs%255D%2520%253D%2520type%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520this.obj%255Bs%255D.split('%252C').map(s%2520%253D%253E%2520s%2520%252B%2520'12345'%255Bi%255D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D) does not crash.

Please provide instructions to reproduce that only involve the closure compiler, not other external tools such as gulp. Closing this for now. If you give us steps to repro, I will reopen.
