### ISSUE TITLE
NPE in NTI, precondition failure in makeObjectType()

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2686]
This occurred when playing with the debugger trying to report another separate bug. I realise what's wrong, but it's crashing:

``` javascript
goog.provide("ns1");

var ns = {};

/**
 * @type {function(new:?)}
 */
ns.something;
```

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.javascript.jscomp.newtypes.ObjectType.makeObjectType(ObjectType.java:128)
	at com.google.javascript.jscomp.newtypes.NamespaceLit.computeJSType(NamespaceLit.java:49)
	at com.google.javascript.jscomp.newtypes.Namespace.toJSType(Namespace.java:246)
	at com.google.javascript.jscomp.NTIScope.freezeScope(NTIScope.java:749)
	at com.google.javascript.jscomp.GlobalTypeInfoCollector.process(GlobalTypeInfoCollector.java:408)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:304)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1082)
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide(%2522ns1%2522)%253B%250A%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bfunction(new%253A%253F)%257D%250A%2520*%252F%250Ans.something%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by supersteves** [comment]
Related:
https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide(%2522ns1%2522)%253B%250A%250Avar%2520ns1%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bfunction(new%253A%253F)%257D%250A%2520*%252F%250Ans1.something%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue
