### ISSUE TITLE
Arrow functions - single, default parameter

### ISSUE THREAD

**Issue by kuklanski** [google/closure-compiler#2703]
Whenever I use arrow function with single, default parameter, I've go Es6RewriteBlockScopedDeclaration:

   Caused by: null
     at com.google.javascript.jscomp.Es6RewriteBlockScopedDeclaration.process(Es6RewriteBlockScopedDeclaration.java:136)
     at com.google.javascript.jscomp.Compiler.transpileAndDontCheck(Compiler.java:1046)
     at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:871)
     at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
     at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:808)
     at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:805)
     at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
     at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:862)
     at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:804)

Example function: 
`(x = true) => true;`

**Comment by MatrixFrog** [comment]
Hm, I'm not seeing this in the debugger https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520f%2520%253D%2520(x%2520%253D%2520true)%2520%253D%253E%2520x%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by brad4d** [comment]
@kuklanski 
could you provide more information about how to reproduce this?
Without a repro, I don't think we can proceed here.

In addition to @MatrixFrog's attempt using the debugger I tried this.

`closure-compiler --js tmp.js`
where `tmp.js` contains
```javascript
(x = true) => true;
```

**Comment by kuklanski** [comment]
It is hard to provide a repo, because error occured while using Sencha Cmd for ExtJs 6.5.2. The only thing I have are logs from sencha build. which I have already posted.
