### ISSUE TITLE
Multiple functions with same name in try scope 

### ISSUE THREAD

**Issue by Raghul-S-1994** [google/closure-compiler#2755]
Executing the following code that contains multiple functions with the same name results in a runtime exception.
```javascript
var main=(function(){
	try{
		function function1(arg1){
		}

		function function1(arg1, arg2){		
		}
	}catch(e) {
	}
})();
```
The resulting exception is
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(FUNCTION function1$0): try.js:6:2
		function function1(arg1, arg2){
  Parent(BLOCK): try.js:2:4
	try{

	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.javascript.jscomp.Scope.undeclare(Scope.java:148)
	at com.google.javascript.jscomp.Es6RewriteBlockScopedDeclaration.visit(Es6RewriteBlockScopedDeclaration.java:111)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:735)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:749)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:855)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:763)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:855)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:763)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:799)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:733)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:749)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:721)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:746)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:680)
	at com.google.javascript.jscomp.Es6RewriteBlockScopedDeclaration.process(Es6RewriteBlockScopedDeclaration.java:119)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:304)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1066)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:865)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:101)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:799)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:796)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	... 42 more

```

**Comment by MatrixFrog** [comment]
We can probably just ban this pattern in `VarCheck` (even though Chrome technically allows it even in strict mode)
