### ISSUE TITLE
`loadMaps: true` cause some error in google-closure-compiler

### ISSUE THREAD

**Issue by Aqours** [google/closure-compiler#2776]
Move from https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/329

**Code**
```js
const gulp = require('gulp');
const sourcemaps = require('gulp-sourcemaps');
const closureCompiler = require('google-closure-compiler').gulp();
// others vars...

gulp.task('compress', function () {
    const options = {
        js_output_file: './dist/closure-output-file.js',
        compilation_level: 'ADVANCED',
        externs: [
            // ...
        ],
        warning_level: 'QUIET',
        language_in: 'ECMASCRIPT5'
    };

    return gulp.src([/* ... */])
        // Using `loadMaps: true` option will cause some error.
        // It works without `loadMaps` flag or `loadMaps: fasle`.
        // .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(sourcemaps.init())
        .pipe(closureCompiler(options))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('./'));
});
```

**output error**
```
[18:07:10] gulp-google-closure-compiler: java.nio.file.InvalidPathException: Illegal char <:> at index 7: webpack:///webpack/bootstrap 2605c8b88e36771ea52b
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolveSibling(AbstractPath.java:66)
	at com.google.javascript.jscomp.Compiler.getRelativeTo(Compiler.java:691)
	at com.google.javascript.jscomp.Compiler.getSourceMapping(Compiler.java:2872)
	at com.google.javascript.jscomp.SourceMap.addMapping(SourceMap.java:148)
	at com.google.javascript.jscomp.CodePrinter$MappedCodePrinter.generateSourceMap(CodePrinter.java:139)
	at com.google.javascript.jscomp.CodePrinter.toSource(CodePrinter.java:879)
	at com.google.javascript.jscomp.CodePrinter.access$300(CodePrinter.java:40)
	at com.google.javascript.jscomp.CodePrinter$Builder.build(CodePrinter.java:819)
	at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2386)
	at com.google.javascript.jscomp.Compiler.access$700(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$15.call(Compiler.java:2346)
	at com.google.javascript.jscomp.Compiler$15.call(Compiler.java:2308)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:118)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:902)
	at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2307)
	at com.google.javascript.jscomp.Compiler$11.call(Compiler.java:2202)
	at com.google.javascript.jscomp.Compiler$11.call(Compiler.java:2191)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

(node:8752) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-google-closure-compiler'
Message:
    Compilation error
(node:8752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Aqours** [comment]
I found a workaround.
This issue is not relevant with google-closure-compiler. It relevant with webpack.
```js
module.exports = {

    // Other code...

    devtool: 'inline-source-map',

    output: {
        // Other code...

        // @see https://github.com/google/closure-compiler/issues/2776
        // @see https://github.com/webpack/webpack/issues/238#issuecomment-174468364
        // @see https://webpack.js.org/configuration/output/#output-devtoolfallbackmodulefilenametemplate
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
    }

};

```
