### ISSUE TITLE
INTERNAL COMPILER ERROR, Preconditions.java:429

### ISSUE THREAD

**Issue by syranide** [google/closure-compiler#2791]
NPM version 20180101.0.0

Not really sure how I can narrow this down as there's not really anything helpful being printed. I'm only using GCC intermittently on my large codebase for now, so I'm not sure when this problem appeared.

```
java -XX:+TieredCompilation -jar node_modules/google-closure-compiler/compiler.jar -O ADVANCED --js "src/**.js" --entry_point "src/index" --js_output_file "output/bundle.js" --create_source_map "output/bundle.js.map" --source_map_include_content --output_wrapper "(function(){%output%}).call(this)" --language_out ECMASCRIPT5_STRICT --new_type_inf --env BROWSER --module_resolution NODE --warning_level=VERBOSE --jscomp_warning=extraRequire
```

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
In scope: <TOP SCOPE> with root: ROOT
        at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
        at com.google.javascript.jscomp.newtypes.JSType.getPrototypeObject(JSType.java:2022)
        at com.google.javascript.jscomp.newtypes.FunctionType.getPrototypeOfNewInstances(FunctionType.java:455)
        at com.google.javascript.jscomp.newtypes.ObjectType.getOwnerFunction(ObjectType.java:262)
        at com.google.javascript.jscomp.newtypes.ObjectType.isPrototypeObject(ObjectType.java:247)
        at com.google.javascript.jscomp.newtypes.ObjectType.canMergeObjectsInJoin(ObjectType.java:1208)
        at com.google.javascript.jscomp.newtypes.ObjectType.joinSets(ObjectType.java:1248)
        at com.google.javascript.jscomp.newtypes.JSType.join(JSType.java:653)
        at com.google.javascript.jscomp.newtypes.NominalType.joinTypeMaps(NominalType.java:560)
        at com.google.javascript.jscomp.newtypes.NominalType.join(NominalType.java:579)
        at com.google.javascript.jscomp.newtypes.ObjectType.join(ObjectType.java:1186)
        at com.google.javascript.jscomp.newtypes.ObjectType.joinSets(ObjectType.java:1257)
        at com.google.javascript.jscomp.newtypes.JSType.join(JSType.java:653)
        at com.google.javascript.jscomp.NewTypeInference.analyzeArrayLitFwd(NewTypeInference.java:2640)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1647)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1459)
        at com.google.javascript.jscomp.NewTypeInference.calcTypeInstantiation(NewTypeInference.java:2996)
        at com.google.javascript.jscomp.NewTypeInference.calcTypeInstantiationFwd(NewTypeInference.java:2931)
        at com.google.javascript.jscomp.NewTypeInference.analyzeInvocationFwd(NewTypeInference.java:2235)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1610)
        at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1464)
        at com.google.javascript.jscomp.NewTypeInference.analyzeVarDeclFwd(NewTypeInference.java:1392)
        at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:1013)
        at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:837)
        at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:560)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:300)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:227)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1067)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:866)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:800)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:797)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
        ... 37 more
```

**Comment by dimvar** [comment]
As is, we cannot even reproduce the crash. Closing for now. If you can provide us with some code to reproduce this, please reply here and I will take a look.

**Comment by syranide** [comment]
@dimvar I'm not sure if it helps, but I narrowed it down to this code (but doesn't crash on its own). It's rather finicky and it only happens under very exact circumstances, remove one item from the list and it works, change one of the "constructors" to something else and it works, etc.

Specifically, it really doesn't like me naming the member "constructor" (which is probably a bad idea on my part, but still a bug). If I change that to something else it seems to work consistently.

```js
/** @type {!Map<string,?>} */
const HostDefinitions = new Map([
  ['link', {
    constructor: LinkEditable,
  }],
  ['image', {
    constructor: ImageEditable,
  }],
  ['prftf', {
    constructor: RenderedBitmapFontTextFieldEditable,
  }],
]);

function test() {
  let hostDef = HostDefinitions.get(...);
  let inst = new (hostDef.constructor);
}
```
