### ISSUE TITLE
[NTI] Attempting to assign to a type-cast value results in an internal compiler error

### ISSUE THREAD

**Issue by rcfox** [google/closure-compiler#2795]
```
/** @type {*} */
var foo = 0;

/** @type {number} */(foo) = 1;
```

I realize that's an unnecessary cast in this case. I encountered the error while trying to do a `+=`, and figured that including the extra operation might just be distracting. I'm not sure if it's intended that this be an illegal operation, but it should at least be handled more gracefully.

```
$ java -jar closure-compiler-v20171203.jar --new_type_inf --jscomp_error=* test.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
In scope: <TOP SCOPE> with root: ROOT
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.javascript.jscomp.NewTypeInference.analyzeLValueFwd(NewTypeInference.java:4693)
	at com.google.javascript.jscomp.NewTypeInference.analyzeLValueFwd(NewTypeInference.java:4618)
	at com.google.javascript.jscomp.NewTypeInference.analyzeAssignAddFwd(NewTypeInference.java:2038)
	at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1557)
	at com.google.javascript.jscomp.NewTypeInference.analyzeExprFwd(NewTypeInference.java:1464)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:981)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:837)
	at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:560)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:304)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1066)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:865)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:101)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:799)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:796)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	... 21 more

```

Version info:
```
$ java -jar closure-compiler-v20171203.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by rcfox** [comment]
It's also worth mentioning that this is not an error when not using NTI:

```
$ java -jar closure-compiler-v20171203.jar --jscomp_error=* test.js
var foo=0;foo=1;
```

**Comment by realityforge** [comment]
@lauraharker This issue is related to NTI which has been dropped so the issue can be closed. (It works in current master)
