### ISSUE TITLE
IllegalStateException with @constructor in object literal

### ISSUE THREAD

**Issue by JaredNeil** [google/closure-compiler#2819]
`my_file.js`:
```
my_object = {
    /**
     * @constructor
     */
    my_key: function() {
        this.prop = '';
    },
};
```
Using Bazel rules_closure version:
`Latest commit 08039ba on Jan 11`
Closure Compiler Version:
`closure-compiler-unshaded-v20180101.jar`
Command run:
`bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/ClosureWorker JsChecker --src my_file.js`

Error:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(EXPR_RESULT): my_file.js:6:8
        this.prop = '';
  Parent(BLOCK): my_file.js:5:20
    key: function() {

        at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
        at com.google.javascript.jscomp.ijs.ClassUtil.getPrototypeNameOfThisProp(ClassUtil.java:40)
        at com.google.javascript.jscomp.ijs.PotentialDeclaration.fromName(PotentialDeclaration.java:57)
        at com.google.javascript.jscomp.ijs.FileInfo.recordNameDeclaration(FileInfo.java:37)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface$PropagateConstJsdoc.visit(ConvertToTypedInterface.java:320)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:769)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:855)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:763)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:799)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:733)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:749)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:765)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:721)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:746)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:680)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface.processFile(ConvertToTypedInterface.java:95)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface.process(ConvertToTypedInterface.java:87)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:300)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:227)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1067)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:866)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:800)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:797)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:854)
        at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:796)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:713)
        at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:249)
        at com.google.javascript.jscomp.JsChecker.access$300(JsChecker.java:63)
        at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:341)
        at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
        at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:69)
        at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
        at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:88)
        at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
Caused by: java.lang.IllegalStateException
        ... 46 more
```

**Comment by JaredNeil** [comment]
Not sure if this should be a new issue, but I found another one.
This time it was a `NullPointerException`.
`my_file.js`:
```
var a, b, c = [];
```

Error:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(VAR): my_file.js:1:0
var a, b, c;
  Parent(SCRIPT): my_file.js:1:0
var a, b, c;

        at com.google.javascript.rhino.IR.mayBeExpression(IR.java:717)
        at com.google.javascript.rhino.IR.declaration(IR.java:202)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface$RemoveNonDeclarations.splitNameDeclarationsAndRemoveDestructuring(ConvertToTypedInterface.java:274)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface$RemoveNonDeclarations.visit(ConvertToTypedInterface.java:239)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:769)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:840)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:721)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:746)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:680)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface.processFile(ConvertToTypedInterface.java:94)
        at com.google.javascript.jscomp.ijs.ConvertToTypedInterface.process(ConvertToTypedInterface.java:87)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:300)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:227)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1067)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:866)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:800)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:797)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:854)
        at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:796)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:713)
        at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:249)
        at com.google.javascript.jscomp.JsChecker.access$300(JsChecker.java:63)
        at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:341)
        at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
        at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:69)
        at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
        at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:88)
        at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
Caused by: java.lang.NullPointerException
        ... 31 more
```

**Comment by blickly** [comment]
Thanks for the reports! These are both now fixed at head:
https://closure-compiler-debugger.appspot.com/ijs_generator.html#input0%3Dobject%2520%253D%2520%257B%250A%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540constructor%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520key%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.prop%2520%253D%2520''%253B%250A%2520%2520%2520%2520%257D%252C%250A%257D%253B%26conformanceConfig%26externs%26refasterjs-template
https://closure-compiler-debugger.appspot.com/ijs_generator.html#input0%3Dvar%2520a%252C%2520b%252C%2520c%2520%253D%2520%255B%255D%253B%26conformanceConfig%26externs%26refasterjs-template
