### ISSUE TITLE
java.lang.RuntimeException: INTERNAL COMPILER ERROR.

### ISSUE THREAD

**Issue by sayrer** [google/closure-compiler#2848]
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

```
ERROR: Program threw uncaught exception with args: JsCompiler --checks_only --incremental_check_mode CHECK_IJS --warning_level VERBOSE --jscomp_off reportUnknownTypes --language_in ECMASCRIPT_2017 --language_out ECMASCRIPT5 --js_output_file bazel-out/k8-fastbuild/bin/protobufs/closure_lib_google_typecheck --externs=bazel-out/k8-fastbuild/bin/external/io_bazel_rules_closure/closure/library/library.i.js --externs=bazel-out/k8-fastbuild/bin/external/io_bazel_rules_closure/closure/protobuf/jspb.i.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/abstractclientbase.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/clientreadablestream.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/error.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/gatewayclientbase.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/grpcwebclientbase.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/grpcwebclientreadablestream.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/grpcwebstreamparser.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/status.js --js=external/com_github_vsco_grpc_web/javascript/net/grpc/web/streambodyclientreadablestream.js --js=bazel-out/k8-fastbuild/genfiles/protobufs/protos_grpc_web_closure.js --suppress JSC_UNKNOWN_EXPR_TYPE --suppress JSC_IMPLICITLY_NULLABLE_JSDOC --suppress JSC_VAR_MULTIPLY_DECLARED_ERROR

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

com.google.javascript.jscomp.ClosureRewriteModule$ScriptDescription@2dd8cf50
  Node(CALL): bazel-out/k8-fastbuild/bin/external/io_bazel_rules_closure/closure/library/library.i.js:7042:0
goog.module("goog.delegate.DelegateRegistry");
  Parent(EXPR_RESULT): bazel-out/k8-fastbuild/bin/external/io_bazel_rules_closure/closure/library/library.i.js:7042:0
goog.module("goog.delegate.DelegateRegistry");

	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.javascript.jscomp.ClosureRewriteModule.updateGoogModule(ClosureRewriteModule.java:1109)
	at com.google.javascript.jscomp.ClosureRewriteModule.access$2200(ClosureRewriteModule.java:88)
	at com.google.javascript.jscomp.ClosureRewriteModule$ScriptUpdater.shouldTraverse(ClosureRewriteModule.java:485)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:757)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:843)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:768)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:843)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:724)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:749)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:305)
	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:680)
	at com.google.javascript.jscomp.ClosureRewriteModule.processAllFiles(ClosureRewriteModule.java:788)
	at com.google.javascript.jscomp.ClosureRewriteModule.process(ClosureRewriteModule.java:756)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1080)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:873)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:101)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:804)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: com.google.javascript.jscomp.ClosureRewriteModule$ScriptDescription@2dd8cf50
```

**Comment by negator** [comment]
In [rules_closure](https://github.com/bazelbuild/rules_closure/blob/4af89ef1db659eb41f110df189b67d4cf14073e1/closure/compiler/closure_js_library.bzl#L160
), It seems that the checker is only run if its output files are required by other rules, namely ones that generate `.i.js` files (externs). And these files are generated by implicitly defined rules. So our workaround was simply to exclude these rules in our CI.
