### ISSUE TITLE
INTERNAL COMPILER ERROR: assigning a class extending class expression

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#2937]
```js
var A = class extends (class {}) {};
```

[Demo in closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520A%2520%253D%2520class%2520extends%2520(class%2520%257B%257D)%2520%257B%257D%253B)

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(CLASS): src/index.js:14:8
var A = class extends (class {}) {};
  Parent(NAME A): src/index.js:14:4
var A = class extends (class {}) {};

        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:782)
        at com.google.javascript.jscomp.Es6RewriteClass.visitClass(Es6RewriteClass.java:218)
        at com.google.javascript.jscomp.Es6RewriteClass.visit(Es6RewriteClass.java:121)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:806)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:758)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:783)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:328)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:338)
        at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:455)
        at com.google.javascript.jscomp.Es6RewriteClass.process(Es6RewriteClass.java:78)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1044)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:837)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:771)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:768)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        ... 27 more
```

**Comment by lauraharker** [comment]
This was fixed in https://github.com/google/closure-compiler/pull/2997
