### ISSUE TITLE
The system called the miss object

### ISSUE THREAD

**Issue by mendickxiao** [google/closure-compiler#2951]
When I test the project based on the vsaq.
https://github.com/google/vsaq

We updated the "vsaq-main.js" 
vsaq\client_side_only_impl\vsaq_main.js

When we run the /do.sh, it is failed and checked the root cause, it will call the miss object.
We download the latest code of closure-compiler

git submodule add -f https://github.com/google/closure-compiler closure-compiler

The error:
java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at com.google.javascript.jscomp.deps.ClosureSortedDependencies.cycleToString(ClosureSortedDependencies.java:184)
        at com.google.javascript.jscomp.deps.ClosureSortedDependencies.<init>(ClosureSortedDependencies.java:108)
        at com.google.javascript.jscomp.JSModuleGraph.manageDependencies(JSModuleGraph.java:380)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1324)
        at com.google.javascript.jscomp.Compiler.parse(Compiler.java:710)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:671)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:639)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I found the code ClosureSortedDependencies.java is removed after the branch 20160315, so I didn't know what happen.

**Comment by lauraharker** [comment]
It sounds like you're still on an old compiler version.

`git submodule add -f https://github.com/google/closure-compiler closure-compiler` adds a new submodule for Closure Compiler under `closure-compiler` - but from what I see, you need to update the existing submodule under `third_party/closure-compiler`.

Can you try `git submodule update --remote --recursive third_party/closure-compiler`?
