### ISSUE TITLE
INTERNAL_COMPILER_ERROR when compiling closure library class in BUNDLE mode

### ISSUE THREAD

**Issue by albertsteckermeier** [google/closure-compiler#2955]
The following error occurs for the file `cssspecificity.js` from the Closure library when using `CompilationLevel.BUNDLE`.

```
Please report this problem.

null
  Node(VAR): /goog/html/cssspecificity.js/:20:0
var userAgent = goog.require('goog.userAgent');
  Parent(MODULE_BODY): /goog/html/cssspecificity.js/:17:0
goog.module('goog.html.CssSpecificity');

	at com.google.common.base.Preconditions.checkState(Preconditions.java:441)
	at com.google.javascript.jscomp.TypedScopeCreator$IdentifyGlobalEnumsAndTypedefsAsNonNullable.visit(TypedScopeCreator.java:451)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:806)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseModule(NodeTraversal.java:885)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:798)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:758)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:783)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:328)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:338)
	at com.google.javascript.jscomp.TypedScopeCreator.createInitialScope(TypedScopeCreator.java:386)
	at com.google.javascript.jscomp.TypedScopeCreator.createScopeInternal(TypedScopeCreator.java:301)
	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:274)
	at com.google.javascript.jscomp.PassConfig.regenerateGlobalTypedScope(PassConfig.java:55)
	at com.google.javascript.jscomp.DefaultPassConfig$GlobalTypeResolver.process(DefaultPassConfig.java:2079)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1044)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:837)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:771)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:768)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	... 4 more
Caused by: java.lang.IllegalStateException
	... 32 more
```

**Comment by lauraharker** [comment]
Looks like this Preconditions check during typechecking is failing:
https://github.com/google/closure-compiler/blob/2dd0970934b49c374ff99a2800c26d9d3b3885d7/src/com/google/javascript/jscomp/TypedScopeCreator.java#L467

This would be because typechecking doesn't understand modules and expects things to be in either the global scope or a function scope. 

Typechecking isn't supposed to run if you request bundling, though. Bundling just concatenates the input files + some special module handling. How are you calling the compiler?

**Comment by albertsteckermeier** [comment]
You're right I had enabled type checking. Without it everything works fine. The ticket can be closed.
