### ISSUE TITLE
gulp build stopped working with release v20180610

### ISSUE THREAD

**Issue by ray007** [google/closure-compiler#2974]
After updating to the new release, my gulp build stopped working.
This is caused by the gulp module now using the js-builder instead of the java-builder which still works fine.
Stacktrace as follows:
```
Error: Cannot find module '../../jscomp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\product_dir\src\html5app\node_modules\google-closure-compiler\lib\node\closure-compiler-js.js:27:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\product_dir\src\html5app\node_modules\google-closure-compiler\index.js:28:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\product_dir\src\html5app\gulpfile.js:15:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:185:9)
    at C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:159:9
    at C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:108:14
    at C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:36:12
    at C:\Users\rbauer\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:47:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by ahocevar** [comment]
I get the same error message without gulp. See travis test log in openlayers/openlayers#8268.

**Comment by ChadKillingsworth** [comment]
This was fixed by https://github.com/google/closure-compiler-npm/pull/84.

A patch level release has been made to include the jscomp file in the npm bundle.

**Comment by ray007** [comment]
Sounds good, but isn't there an option to make the gulp plugin use the java compiler?
Adding `{jsMode: false}` as parameter does not work...

**Comment by ChadKillingsworth** [comment]
Java is the default. Omitting the flag completely should be using the Java version.
