### ISSUE TITLE
Source map original file without a name causes exception

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2976]
```
Error: Compilation error: java.lang.IllegalArgumentException: a source must have a name
	at com.google.javascript.jscomp.SourceFile.<init>(SourceFile.java:100)
	at com.google.javascript.jscomp.SourceFile$OnDisk.<init>(SourceFile.java:600)
	at com.google.javascript.jscomp.SourceFile$Builder.buildFromPath(SourceFile.java:502)
	at com.google.javascript.jscomp.SourceFile.fromPath(SourceFile.java:421)
	at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:101)
	at com.google.javascript.jscomp.Compiler.getSourceMapping(Compiler.java:2943)
	at com.google.javascript.jscomp.SourceMap.addMapping(SourceMap.java:178)
	at com.google.javascript.jscomp.CodePrinter$MappedCodePrinter.generateSourceMap(CodePrinter.java:141)
	at com.google.javascript.jscomp.CodePrinter.toSource(CodePrinter.java:887)
	at com.google.javascript.jscomp.CodePrinter.access$300(CodePrinter.java:42)
	at com.google.javascript.jscomp.CodePrinter$Builder.build(CodePrinter.java:816)
	at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2337)
	at com.google.javascript.jscomp.Compiler.access$600(Compiler.java:108)
	at com.google.javascript.jscomp.Compiler$12.call(Compiler.java:2297)
	at com.google.javascript.jscomp.Compiler$12.call(Compiler.java:2258)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:836)
	at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2257)
	at com.google.javascript.jscomp.Compiler$10.call(Compiler.java:2210)
	at com.google.javascript.jscomp.Compiler$10.call(Compiler.java:2192)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ChadKillingsworth** [comment]
Closed by e6a6cbb
