### ISSUE TITLE
Internal Compiler Error When Having class Foo extends RequestInit and getters and setters

### ISSUE THREAD

**Issue by phistuck** [google/closure-compiler#3010]
Not sure what is the culprit here, but the following externs (while not great) break the compiler (and make it ask me to report this error, so here) -
```
class RequestEntityInit extends RequestInit {
 /** @param {?} value */
 set bodyEntity(value) {}
 /** @return {?} */
 get bodyEntity() {}
};
```

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540js_externs%2520class%2520RequestEntityInit%2520extends%2520RequestInit%2520%257B%2520%252F**%2520%2540param%2520%257B%253F%257D%2520value%2520*%252F%2520set%2520bodyEntity(value)%2520%257B%257D%2520%2520%252F**%2520%2540return%2520%257B%253F%257D%2520*%252F%2520get%2520bodyEntity()%2520%257B%257D%2520%257D%250A%252F%252F%2520%2540language_out%2520ES5%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable $jscomp
  Node(NAME $jscomp): web/externs.js:7:0
class RequestEntityInit extends RequestInit {
  Parent(GETPROP): web/externs.js:7:0
class RequestEntityInit extends RequestInit {

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:222)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:806)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:758)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:783)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:877)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:802)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:356)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2480)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:808)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:804)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unexpected variable $jscomp
        ... 29 more
```

**Comment by phistuck** [comment]
It does pretty much the same without extending -
```
/** @implements {RequestInit} */
class RequestEntityInit {
 /** @param {?} value */
 set bodyEntity(value) {}
 /** @return {?} */
 get bodyEntity() {}
};
```

**Comment by lauraharker** [comment]
Interesting... it looks like the crash is because 
1) we add a call to  `$jscomp.global.Object.defineProperties` when transpiling the externs class
   and inject the `$jscomp.global.Object.defineProperties` function into the code
2) optimization passes remove the `$jscomp` variable (thinking it's unused for some reason)
3) the AST validity check notices we have a reference to an undefined variable `$jscomp` and complains

[debugger link](https://closure-compiler-debugger.appspot.com/#input0%26input1%26conformanceConfig%26externs%3D%250Aclass%2520RequestEntityInit%2520%257B%250A%2520%2520get%2520x()%2520%257B%257D%250A%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26ENABLE_ALL_DIAGNOSTIC_GROUPS%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

This should fix itself in a few weeks when we can typechecking ES6 classes without transpiling them first, since then we won't need to transpile classes in the externs.

Is this blocking anything for you in the short term?

**Comment by phistuck** [comment]
Not blocking, I ended up not extending that class and separated the new properties to a different object.

**Comment by phistuck** [comment]
@lauraharker - note that this is still happening (still not blocking, but you mentioned that it should fix itself in a few weeks and half a year has passed).

**Comment by lauraharker** [comment]
I see, thanks for pointing out this is still happening.

Looks like there's a slightly different error now:

```
23: java.lang.RuntimeException: runtime library injected after type checking:util/global
	at com.google.javascript.jscomp.Compiler.ensureLibraryInjected(Compiler.java:3284)
	at com.google.javascript.jscomp.Es6RewriteClass.visitClass(Es6RewriteClass.java:211)
	at com.google.javascript.jscomp.Es6RewriteClass.visit(Es6RewriteClass.java:130)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:927)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1039)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:408)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:418)
	at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:571)
	at com.google.javascript.jscomp.Es6RewriteClass.process(Es6RewriteClass.java:91)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:310)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1039)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:843)
	
```

**Comment by lauraharker** [comment]
Created Google internal issue http://b/123244870
