### ISSUE TITLE
browser_resolver_prefix_replacements flag is non-functional

### ISSUE THREAD

**Issue by l1bbcsg** [google/closure-compiler#3038]
```
$ closure-compiler --version

Closure Compiler (http://github.com/google/closure-compiler)
Version: v20180716
Built on: 2018-07-17 22:09
```

```
$ closure-compiler --browser_resolver_prefix_replacements="foo=bar"

Exception in thread "main" java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:529)
	at org.kohsuke.args4j.spi.MapOptionHandler.addToMap(MapOptionHandler.java:92)
	at org.kohsuke.args4j.spi.MapOptionHandler.addToMap(MapOptionHandler.java:85)
	at org.kohsuke.args4j.spi.MapOptionHandler.parseArguments(MapOptionHandler.java:45)
	at org.kohsuke.args4j.CmdLineParser.parseArgument(CmdLineParser.java:508)
	at com.google.javascript.jscomp.CommandLineRunner$Flags.parse(CommandLineRunner.java:850)
	at com.google.javascript.jscomp.CommandLineRunner$Flags.access$500(CommandLineRunner.java:140)
	at com.google.javascript.jscomp.CommandLineRunner.initConfigFromFlags(CommandLineRunner.java:1549)
	at com.google.javascript.jscomp.CommandLineRunner.<init>(CommandLineRunner.java:1397)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2156)
```

From my understanding, it attempts to call `put` on `ImmutableMap` with is not possible (immutable, duh) since the method is deprecated and always throws this exception.

Also `browser_resolver_prefix_replacements` flag is not documented, I was only able to find about its existence from source files. However `--module_resolution=BROWSER_WITH_TRANSFORMED_PREFIXES` is and it's pretty much useless without `browser_resolver_prefix_replacements`.

**Comment by ChadKillingsworth** [comment]
@l1bbcsg Is that with the native binary version?

**Comment by l1bbcsg** [comment]
This is the Java binary, not js version. It was installed through `brew` on macOS. The binary is called `closure-compiler-v20180716.jar`
And it was run with this Java:
```
$ java -version

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by blickly** [comment]
@jplaisted , can you take a look?

It sounds like maybe the pattern for using this flag with args4j is broken.

**Comment by l1bbcsg** [comment]
Can confirm it's fixed and the flag seems to be working as intended now, thanks!

Still would appreciate documentation though.
