### ISSUE TITLE
UnsupportedClassVersionError / Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Daijobou** [google/closure-compiler#3059]
```
java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```
In compiler.jar from 2016 its working, but new one compiler-20180805.zip give me a error
Command
`...\CommonFiles\Java64\bin\java -jar compiler.jar --language_in=ECMASCRIPT6 --compilation_level SIMPLE_OPTIMIZATIONS --js folder/file.js --js_output_file folder2/file.js`

Output
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
I found https://github.com/google/closure-compiler/wiki/FAQ#the-compiler-crashes-with-unsupportedclassversionerror-or-unsupported-majorminor-version-510 but I have 1.7.

**Comment by thheller** [comment]
It was bumped up to requiring Java 8+ not too long ago.

It is mentioned in the main README.

> Note: The Closure Compiler requires Java 8 or higher.

**Comment by PatelAshish11** [comment]
The version number shown describes the version of the JRE the class file is compatible with.

The reported major numbers are:

Java SE 13 = 57,
Java SE 12 = 56,
Java SE 11 = 55,
Java SE 10 = 54,
Java SE 9 = 53,
Java SE 8 = 52,
Java SE 7 = 51,
Java SE 6.0 = 50,
Java SE 5.0 = 49,
JDK 1.4 = 48,
JDK 1.3 = 47,
JDK 1.2 = 46,
JDK 1.1 = 45

Full source [here](https://icetutor.com/question/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-version/)
