### ISSUE TITLE
Compiler crashes while processing nodejs module with destructuring

### ISSUE THREAD

**Issue by nbeloglazov** [google/closure-compiler#3090]
Repro case:

```js
const {Foo} = require('./foo.js');
Foo;
exports.Foo = Foo;
```

Run:
```bash
java -jar closure-compiler-v20180910.jar test.js --process_common_js_modules
```

Error:
```text
INTERNAL COMPILER ERROR.
Please report this problem.

The nameNode for Var Foo @ NAME Foo 1 [length: 3] [source_file: test.js] must be a descendant of one of: [PARAM_LIST, FUNCTION, VAR, CATCH, CONST, CLASS, LET, IMPORT]
  Node(NAME Foo): test.js:2:0
Foo;
  Parent(EXPR_RESULT): test.js:2:0
Foo;

  Node(SCRIPT): test.js:1:0
const {Foo} = require('./foo.js');
  Parent(ROOT): [source unknown]

	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.javascript.jscomp.AbstractVar.declarationType(AbstractVar.java:227)
	at com.google.javascript.jscomp.AbstractVar.isParam(AbstractVar.java:184)
	at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.maybeUpdateName(ProcessCommonJSModules.java:1658)
	at com.google.javascript.jscomp.ProcessCommonJSModules$RewriteModule.visit(ProcessCommonJSModules.java:1336)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:797)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:822)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:331)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:341)
	at com.google.javascript.jscomp.ProcessCommonJSModules.shouldTraverse(ProcessCommonJSModules.java:126)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:796)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:822)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:331)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:341)
	at com.google.javascript.jscomp.ProcessCommonJSModules.process(ProcessCommonJSModules.java:75)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1029)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:823)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:110)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:758)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:755)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

The nameNode for Var Foo @ NAME Foo 1 [length: 3] [source_file: test.js] must be a descendant of one of: [PARAM_LIST, FUNCTION, VAR, CATCH, CONST, CLASS, LET, IMPORT]
  Node(NAME Foo): test.js:2:0
Foo;
  Parent(EXPR_RESULT): test.js:2:0
Foo;

	... 33 more
Caused by: java.lang.IllegalStateException: The nameNode for Var Foo @ NAME Foo 1 [length: 3] [source_file: test.js] must be a descendant of one of: [PARAM_LIST, FUNCTION, VAR, CATCH, CONST, CLASS, LET, IMPORT]
	... 33 more
```

The root cause is that `Foo` on the first line gets rewritten here: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ProcessCommonJSModules.java#L1317 Removing `maybeUpdateName` fixes the problem. 

It was added by @ChadKillingsworth in #2762. Chad, why do we need to rewrite names inside destructuring?

**Comment by ChadKillingsworth** [comment]
It's the fact that it's a transitive export. There's tests for destructured imports: https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/ProcessCommonJSModulesTest.java#L639-L664

Just need a special case not to rename the definition when it is imported from another module.

**Comment by ChadKillingsworth** [comment]
Nevermind - it has to be renamed so that it doesn't conflict with anything else in the same scope.

**Comment by nbeloglazov** [comment]
Chad, in what case it'll conflict if we don't rename? I can see it conflicting if these names need to be unique globally when we write all js as 1 file at the end. Is that the case?

**Comment by nbeloglazov** [comment]
Actually seems like current behavior is also slightly broken in another way:

test1.js
```js
const {Foo} = require('./foo.js');
console.log('first ', Foo);
```
test2.js
```js
const {Foo} = require('./foo.js');
console.log('second ', Foo);
```

It fails with 
```test
test2.js:1: ERROR - Illegal redeclared variable: Foo
const {Foo} = require('./foo.js');
```

The reason is that compiler doesn't recognize these files as commonjs modules and doesn't rewrite Foo in destructuring.

**Comment by ChadKillingsworth** [comment]
A file is only considered a module if it exports a symbol. Namespace rewriting won't occur on files that only import. So this last behavior is expected.

**Comment by nbeloglazov** [comment]
I see. And looking more into code we also rewrite namespaces even if the file doesn't have exports but still imported by some other file (probably for side effects): https://github.com/google/closure-compiler/blob/903204a548cfd3803346f6d8a34c7a9cbce4b34a/src/com/google/javascript/jscomp/ProcessCommonJSModules.java#L94 

I'll poke around and see how to fix the original problem without changing which files we rewrite.

**Comment by ChadKillingsworth** [comment]
I had a few minutes this morning so took a look. The problem was not at all what I expected. I've posted a PR to fix the issue.
