### ISSUE TITLE
INTERNAL COMPILER ERROR when using `if(new.target)`

### ISSUE THREAD

**Issue by tlhunter** [google/closure-compiler#3097]
I've whittled down a failing test file to [this code sample](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2015%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520x()%2520%257B%250A%2520%2520%252F%252Freturn%2520new.target%2520%253F%25201%2520%253A%25202%250A%2520%2520if%2520(new.target)%2520%257B%250A%2520%2520%2520%2520return%25201%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%25202%253B%250A%2520%2520%257D%250A%257D%250A%250A%252F%252Fx()%253B):

```js
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// @language_out ECMASCRIPT_2015
// ==/ClosureCompiler==

function x() {
  //return new.target ? 1 : 2
  if (new.target) {
    return 1;
  } else {
    return 2;
  }
}

//x();
```

Which gives the following stack trace:

```
file.js:1: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
(function () {
 ^^^^^^^^^^^^^

0 error(s), 1 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(IF): file.js:2:2
  if (new.target) {
  Parent(BLOCK): file.js:1:13
(function () {

        at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
        at com.google.javascript.rhino.IR.hook(IR.java:434)
        at com.google.javascript.jscomp.PeepholeMinimizeConditions.tryMinimizeIf(PeepholeMinimizeConditions.java:620)
        at com.google.javascript.jscomp.PeepholeMinimizeConditions.optimizeSubtree(PeepholeMinimizeConditions.java:82)
        at com.google.javascript.jscomp.PeepholeOptimizationsPass$PeepCallback.visit(PeepholeOptimizationsPass.java:82)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:974)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:841)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:886)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:809)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:825)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:797)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:822)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:331)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:341)
        at com.google.javascript.jscomp.NodeTraversal.traverseScopeRoots(NodeTraversal.java:552)
        at com.google.javascript.jscomp.NodeTraversal.traverseScopeRoots(NodeTraversal.java:533)
        at com.google.javascript.jscomp.PeepholeOptimizationsPass.process(PeepholeOptimizationsPass.java:67)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:452)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2404)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:783)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:779)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
        ... 37 more
```

One thing interesting is that the commented ternary preceding the if statement does work.

**Comment by EatingW** [comment]
Seems like in minimizing conditions, the creation of the IR.hook node checks for an expression as the condition. The new.target node should be treated as an expression, but is not currently so. I have a fix for this out for internal review.
