### ISSUE TITLE
ES6 Out: Rescope Global Symbols Crash 

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3106]
```
ERROR in closure-compiler: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Index: 0, Size: 0
  Node(CONST): /Users/chad/git/platform-ux/projects/dashboard/node_modules/$banno/polymer/polymer-element.js:1:0
const { ElementMixin } = __webpack_require__(49);
  Parent(SCRIPT): /Users/chad/git/platform-ux/projects/dashboard/node_modules/$banno/polymer/polymer-element.js:1:0
const { ElementMixin } = __webpack_require__(49);

	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.google.javascript.jscomp.RescopeGlobalSymbols$RewriteScopeCallback.visitNameDeclaration(RescopeGlobalSymbols.java:379)
	at com.google.javascript.jscomp.RescopeGlobalSymbols$RewriteScopeCallback.shouldTraverse(RescopeGlobalSymbols.java:364)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:830)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:797)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:822)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:331)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:341)
	at com.google.javascript.jscomp.RescopeGlobalSymbols.process(RescopeGlobalSymbols.java:179)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:308)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2452)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:832)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:828)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	... 23 more
```

Stepping through the code, the nodes go:

```
CONST
   DESTRUCTURING_LHS
      OBJECT_PATTERN // this node has no children
```

I haven't figured out _why_ the destructured pattern has no children.

**Comment by ChadKillingsworth** [comment]
Interesting - git bisect blames me: 3b0f0011af374c1183e27e55a90141208055a995

**Comment by lauraharker** [comment]
The pass should just ignore a destructured pattern with no children. It just needs to handle actual global names.

It is concerning that the pattern isn't getting dead-code-removed, though. Running with ADVANCED_OPTIMIZATIONS in ES6 output doesn't seem to remove empty assign patterns...
[`const {} = {};`](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2015%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520%257B%257D%2520%253D%2520%257B%257D%253B%250A)
