### ISSUE TITLE
GWT Version Throws Exceptions

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3142]
The nightly builds of the npm package are failing. The GWT version is throwing the following exception:

```
TypeError: Cannot read property 'b' of null
    at BTb (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8110:586)
    at ATb (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:2642:39)
    at CUb.DUb [as Ni] (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8146:177875)
    at MUb (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:5075:36)
    at ASb (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:5885:61)
    at Zxd (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8020:897)
    at YO (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:1979:29)
    at _O (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3434:44)
    at /home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3640:46
    at CompilerJS.run (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler/lib/node/closure-compiler-js.js:54:17)
    at getFilesFromStdin.then.inputFiles (/home/travis/build/google/closure-compiler-npm/packages/google-closure-compiler/cli.js:164:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
  '__java$exception':
   { g: null,
     backingJsObject: [Circular],
     e: 'TypeError: Cannot read property \'b\' of null',
     a: '',
     b: [Circular] }
```

See https://travis-ci.org/google/closure-compiler-npm/jobs/452676309

git bisect blames 37a03f338de2e602757d57d49fad8c5e9c5e89c2

The Travis build is incorrectly marked as successful. That's fixed by https://github.com/google/closure-compiler-npm/pull/117

**Comment by brad4d** [comment]
Filed Google internal bug b/119282522

**Comment by jplaisted** [comment]
Building with debug flags I'm not wholly convinced it is related to that commit. At the very least, it isn't obviously that commit, the NPE is in the parseInputs method of the compiler, which I didn't touch...

```
{ TypeError: Cannot read property 'needsManagement' of null
    at Compiler_1.parseInputs (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:55662:44)
    at Compiler_1.parseForCompilationInternal (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:55615:8)
    at Compiler_1.lambda$4_0 [as lambda$4] (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:54319:10)
    at Compiler$lambda$4$Type.call_5 [as call_1] (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:56497:25)
    at CompilerExecutor.runInCompilerThread_0 (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:56590:21)
    at Compiler_1.runInCompilerThread (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:55990:32)
    at Compiler_1.parseForCompilation (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:55608:8)
    at Compiler_1.compile [as compile_0] (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:54540:12)
    at compile_0 (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:142865:14)
    at apply_45 (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:31056:23)
    at entry0 (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:31120:14)
    at /tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/node_modules/google-closure-compiler-js/jscomp.js:31087:14
    at CompilerJS.run (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/lib/node/closure-compiler-js.js:54:17)
    at getFilesFromStdin.then.inputFiles (/tmp/google-closure-compiler/closure-compiler-npm/packages/google-closure-compiler/cli.js:164:31)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

**Comment by jplaisted** [comment]
Just to keep this up to date: This will be fixed with our next batch of commits.

**Comment by ChadKillingsworth** [comment]
Nightly build passed.
