### ISSUE TITLE
Compiler crashes on async function with default argument compiling esnext -> es5

### ISSUE THREAD

**Issue by trxcllnt** [google/closure-compiler#3178]
Sample code:
```js
// tmp.js
class Foo {
    constructor(x) { this.x = x }
    async doThing(y = this.x) { (y !== false) && console.log('blah'); }
}
(async () => await new Foo(true).doThing())();
```
Crashes with the following error:
```sh
$ java -jar node_modules/google-closure-compiler-java/compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20181210
Built on: 2018-12-12 22:32

$ java -jar node_modules/google-closure-compiler-java/compiler.jar \
  --language_in=ECMASCRIPT_NEXT \
  --language_out=ECMASCRIPT5 \
  --js=tmp.js

java.lang.NullPointerException: NAME $jscomp$async$this 3 [length: 4] [source_file: tmp.js]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:669)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:531)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:406)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseGetProp(RemoveUnusedCode.java:442)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:411)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1118)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:415)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1200(RemoveUnusedCode.java:90)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1536)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:249)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:228)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:310)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:455)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2435)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:849)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by brad4d** [comment]
Created internal Google issue b/121377660

**Comment by brad4d** [comment]
Thanks for pointing this out @trxcllnt

**Comment by brad4d** [comment]
Internal tracking switched to issue http://b/122100368
I understand the problem and am working on a fix

**Comment by lkjames** [comment]
Any updates on this? I'm having the same problem.

**Comment by brad4d** [comment]
This was fixed in https://github.com/google/closure-compiler/commit/83a8b02c384abda8db5b57d46c1805f592ccd77a#diff-8766342281b3b4b5ee20a57d7f5b061d

I'm not sure why this issue wasn't automatically closed by the "Fixes" comment on that commit.

If you are having a problem with the current version of closure-compiler, please file a new issue with instructions for reproducing the problem. Thanks.
