### ISSUE TITLE
Destructuring in catch throws internal error for ecma > 5

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3197]
```js
try {
  throw new Error('error')
} catch ({ stack }) {
  console.log(stack)
}
```
will yield a compiler error, which is also pretty cryptic and if not for `traverseCatch` I would've never figured out what the problem was.

```
-jar /Users/zavr/node_modules/google-closure-compiler-java/compiler.jar --language_out ECMASCRIPT_2015
  --js t/error.js
```
```
Exit code 254
java.lang.UnsupportedOperationException: OBJECT_PATTERN 3 [length: 9] [source_file: t/error.js] is not a string node
        at com.google.javascript.rhino.Node.getString(Node.java:1231)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:557)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseCatch(RemoveUnusedCode.java:800)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:299)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1174)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:356)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1174)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:435)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1174)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:435)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1174)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:435)
        at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:94)
        at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1601)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:269)
        at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:248)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:310)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:455)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2381)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:793)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lauraharker** [comment]
Created internal issue http://b/122961244

**Comment by zavr-1** [comment]
@lauraharker this seems to be working now, 

```
try {
  throw new Error('example')
} catch ({ stack }) {
  console.log(stack)
}
```
```
-jar /Users/zavr/node_modules/google-closure-compiler-java/compiler.jar --language_out ECMASCRIPT_2015
--js catch.js
```
```js
'use strict';try{throw Error("example");}catch({stack:a}){console.log(a)};
```

**Comment by blickly** [comment]
Thanks for confirming!
