### ISSUE TITLE
Travis build srcmap test failing at head for the GWT version

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3238]
The first red build was at https://github.com/google/closure-compiler/commit/03f37534f3883139be8c26050410a3f068bc338e (the build included multiple new commits)
Last green at https://github.com/google/closure-compiler/commit/08f60507a2fcbb2e622a32c352f3945d2617e303.

```
  1) gulp-google-[secure]
       javascript version
         should generate a sourcemap for a single output file:
     Error: 0 position is not passing assertion: expected Array [
  'test/fixtures/extern.js',
  'test/fixtures/one.js',
  'test/fixtures/two.js'
] to have property length of 2 (got 3)
      at DestroyableTransform.stream.assertion (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/assertStream.js:24:26)
      at DestroyableTransform._transform (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/index.js:102:10)
      at DestroyableTransform.Transform._read (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at write (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:623:24)
      at flow (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:632:7)
      at DestroyableTransform.pipeOnReadable (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:664:5)
      at emitReadable_ (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:448:10)
      at emitReadable (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:444:5)
      at readableAddChunk (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:187:9)
      at DestroyableTransform.Readable.push (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:149:10)
      at DestroyableTransform.Transform.push (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at afterTransform (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:101:12)
      at TransformState.afterTransform (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at DestroyableTransform._transform (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/index.js:80:3)
      at DestroyableTransform.Transform._read (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at CompilationStream.ondata (_stream_readable.js:639:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at CompilationStream.Readable.push (_stream_readable.js:208:10)
      at CompilationStream.Transform.push (_stream_transform.js:147:32)
      at CompilationStream._compilationComplete (lib/gulp/index.js:258:14)
      at compiler.run (lib/gulp/index.js:160:18)
      at CompilerJS.run (lib/node/[secure]-js.js:66:7)
      at CompilerJS.value (test/gulp.js:61:50)
      at CompilationStream._flush (lib/gulp/index.js:159:20)
      at CompilationStream.prefinish (_stream_transform.js:137:10)
      at prefinish (_stream_writable.js:593:14)
      at finishMaybe (_stream_writable.js:601:5)
      at endWritable (_stream_writable.js:612:3)
      at CompilationStream.Writable.end (_stream_writable.js:563:5)
      at DestroyableTransform.onend (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at endReadableNT (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

**Comment by lauraharker** [comment]
Most recent broken build:
https://travis-ci.org/google/closure-compiler/builds/496672606

**Comment by lauraharker** [comment]
Created internal issue http://b/125851384

**Comment by lauraharker** [comment]
Looks like https://github.com/google/closure-compiler/commit/d60394e18bb7878ab129a71d0aa02b60a8d9a2aa is responsible.

And here's the failing test:
https://github.com/google/closure-compiler-npm/blob/583a7ea96f08d9be5df8e79a9e0c1e66f58bfd9d/packages/google-closure-compiler/test/gulp.js#L224

The problem is that test/fixtures/extern.js is included in the output sourceMap.sources unexpectedly. Here's the file, which does have @externs:
https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler/test/fixtures/extern.js

The equivalent Java tests are all still passing, though, it's just the JS version that's failing. I'm not sure why that is.

**Comment by ChadKillingsworth** [comment]
I'm looking into this too

**Comment by ChadKillingsworth** [comment]
I think I may see why this is happening. You can't get information on annotations in the input until it has been parsed. You force parsing by getting the ast. Since that was moved inside an if guard, it will never be true unless the file has already been parsed.

**Comment by brad4d** [comment]
I've just pushed the fixing PR to GitHub.
I'm waiting to confirm that the Travis build turns green before closing this issue.

**Comment by brad4d** [comment]
Travis is now passing.
