### ISSUE TITLE
Internal Compiler Error exporting class extending goog.debug.Error

### ISSUE THREAD

**Issue by michaelfig** [google/closure-compiler#3260]
When [compiling the Javascript Tink implementation with Bazel](https://github.com/google/tink/pull/190), using `bazel test --test_output=all :*` there is an ICE:

```
JsCompiler --checks_only --warning_level VERBOSE --jscomp_off reportUnknownTypes --language_in ECMASCRIPT_2017 --language_out ECMASCRIPT5 --js_output_file bazel-out/darwin-fastbuild/bin/javascript/cleartext_keyset_handle_typecheck --externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/library.i.js
[...]
--externs=bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js
[...] --js=javascript/cleartext_keyset_handle.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

NAME InvalidArgumentsException 14 [length: 25] [source_file: bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js]
  Node(NAME exports): bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js:28:0
exports = SecurityException;
  Parent(ASSIGN): bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js:28:0
exports = SecurityException;

        at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
        at com.google.javascript.jscomp.ClosureRewriteModule.maybeRecordExportDeclaration(ClosureRewriteModule.java:976)
        at com.google.javascript.jscomp.ClosureRewriteModule.access$1900(ClosureRewriteModule.java:88)
        at com.google.javascript.jscomp.ClosureRewriteModule$ScriptRecorder.shouldTraverse(ClosureRewriteModule.java:425)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:830)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
       at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseModule(NodeTraversal.java:967)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:797)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:822)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:331)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:341)
        at com.google.javascript.jscomp.ClosureRewriteModule.processAllFiles(ClosureRewriteModule.java:712)
        at com.google.javascript.jscomp.ClosureRewriteModule.process(ClosureRewriteModule.java:697)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:307)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1056)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:849)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:109)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:783)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:780)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: NAME InvalidArgumentsException 14 [length: 25] [source_file: bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js]
        ... 31 more
```

Here is the source file that seems to exhibit the problem (bazel-out/darwin-fastbuild/bin/javascript/exception/exception.i.js):
```
/** @fileoverview @typeSummary */
goog.module("tink.exception.InvalidArgumentsException");
const Error = goog.require("goog.debug.Error");
/**
 @extends {Error}
 */
class InvalidArgumentsException extends Error {
  /**
 @param {*=} opt_msg
 */
constructor(opt_msg) {
  }
}
exports = InvalidArgumentsException;
/** @fileoverview @typeSummary */
goog.module("tink.exception.SecurityException");
const Error = goog.require("goog.debug.Error");
/**
 @extends {Error}
 */
class SecurityException extends Error {
  /**
 @param {*=} opt_msg
 */
constructor(opt_msg) {
  }
}
exports = SecurityException;
/** @fileoverview @typeSummary */
goog.module("tink.exception.UnsupportedException");
const Error = goog.require("goog.debug.Error");
/**
 @extends {Error}
 */
class UnsupportedException extends Error {
  /**
 @param {*=} opt_msg
 */
constructor(opt_msg) {
  }
}
exports = UnsupportedException;
```

Help would be appreciated!

Thanks,
Michael.

**Comment by tjgq** [comment]
Created Google internal issue b/128521165

**Comment by michaelfig** [comment]
I was misusing bazel: doing a simple `bazel test ...` made things work.  I was misunderstanding that the `...` is **actually, literally three dots**, not a literary shorthand for other arguments.
