### ISSUE TITLE
INTERNAL COMPILER ERROR when using destructuring and "arguments"

### ISSUE THREAD

**Issue by steph643** [google/closure-compiler#3285]
Code:
```javascript
function doIt({ foo }) {
  console.log(arguments[0])
}
doIt({foo: 'bar'})
```

Output:
```
Error: Google Closure Compiler exit 4294967294: java -jar C:\Users\Steph\Work
\Current Projects\Docuss 4.0\r&d\test\node_modules\google-closure-compiler-jav
a\compiler.jar --language_out=NO_TRANSPILE --assume_function_wrapper=true --warn
ing_level=QUIET --module_resolution=NODE --externs=C:\Users\Steph\AppData\Loca
l\Temp\1bddf89e-763e-4f25-875b-b711a52f23bd --compilation_level=ADVANCED --js=C:
\Users\Steph\AppData\Local\Temp\aedfba12-6150-41dd-b4a5-2e854ec8a8a9 --create_
source_map=C:\Users\Steph\AppData\Local\Temp\294fddea-4777-4e12-aac4-a658c8eeb
078

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

OBJECT_PATTERN 9 [length: 7] [source_file: C:/Users/Steph/AppData/Local/Temp/a
edfba12-6150-41dd-b4a5-2e854ec8a8a9] is not a string node
  Node(BLOCK): C:/Users/Steph/AppData/Local/Temp/aedfba12-6150-41dd-b4a5-2e854
ec8a8a9:9:23
function doIt({ foo }) {
  Parent(FUNCTION doIt): C:/Users/Steph/AppData/Local/Temp/aedfba12-6150-41dd-
b4a5-2e854ec8a8a9:9:0
function doIt({ foo }) {

        at com.google.javascript.rhino.Node.getString(Node.java:1231)
        at com.google.javascript.jscomp.OptimizeArgumentsArray.changeBody(Optimi
zeArgumentsArray.java:344)
        at com.google.javascript.jscomp.OptimizeArgumentsArray.tryReplaceArgumen
ts(OptimizeArgumentsArray.java:217)
        at com.google.javascript.jscomp.OptimizeArgumentsArray.exitScope(Optimiz
eArgumentsArray.java:135)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.jav
a:1032)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.jav
a:1023)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTrave
rsal.java:888)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTravers
al.java:809)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTravers
al.java:825)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTrave
rsal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal
.java:797)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTravers
al.java:822)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTrave
rsal.java:959)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTravers
al.java:843)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.jav
a:331)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.jav
a:341)
        at com.google.javascript.jscomp.OptimizeArgumentsArray.process(OptimizeA
rgumentsArray.java:93)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOp
timizer.java:310)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.ja
va:231)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.j
ava:2415)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.
java:829)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor
.java:102)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: OBJECT_PATTERN 9 [length: 7]
 [source_file: C:/Users/Steph/AppData/Local/Temp/aedfba12-6150-41dd-b4a5-2e854
ec8a8a9] is not a string node
        ... 26 more



    at instance.run (C:\Users\Steph\Work\Current Projects\Docuss 4.0\r&d\te
st\node_modules\@ampproject\rollup-plugin-closure-compiler\dist\index.js:1053:24
)
    at ChildProcess.compileProcess.on.code (C:\Users\Steph\Work\Current Projects
\Docuss 4.0\r&d\test\node_modules\google-closure-compiler\lib\node\closure-
compiler.js:103:9)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by EatingW** [comment]
I wasn't able to reproduce it using the debugger:
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520doIt(%257B%2520foo%2520%257D)%2520%257B%250A%2520%2520alert(arguments%255B0%255D)%250A%257D%250AdoIt(%257Bfoo%253A%2520'bar'%257D)%26input1%26conformanceConfig%26externs%3Dfunction%2520alert(x)%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26STRICT_CHECK_TYPES%3Dtrue%26CHECK_CONSTANTS%3Dtrue%26CHECK_DEPRECATED%3Dtrue%26CHECK_ES5_STRICT%3Dtrue%26CHECK_GLOBAL_NAMES%3Dtrue%26CHECK_GLOBAL_THIS%3Dtrue%26CHECK_MISSING_RETURN%3Dtrue%26CHECK_UNREACHABLE_CODE%3Dtrue%26CHECK_PROVIDES%3Dtrue%26CHECK_REQUIRES%3Dtrue%26CHECK_REPORT_MISSING_OVERRIDE%3Dtrue%26CHECK_SUSPICIOUS_CODE%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26CHECK_VISIBILITY%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_PROTOTYPE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Are you using the most updated version of the compiler?

**Comment by lauraharker** [comment]
Nick may have fixed this in https://github.com/google/closure-compiler/commit/c24053e400fd5540e1a61870a1f57c2ada9a5601. Like Yiting said, I'd check your compiler version.

**Comment by steph643** [comment]
Yes, I'm using version 20181125.0.1, which is the one currently supported by `rollup-plugin-closure-compiler`. I've forced update to version 20190301.0.0, but then it crashes the rollup plugin. I will try to free time to check with the CLI directly. Thanks.

**Comment by steph643** [comment]
Closing for now.
