### ISSUE TITLE
NullPointerException in calculated default values

### ISSUE THREAD

**Issue by acceptibru** [google/closure-compiler#3336]
Trying to compile following code:
`class AnotherClass {
    constructor(id) {
        this.id = id;
    }
    isWhatever() {
        return true;
    }
}
class Bug2 {
    constructor(id) {
        this.id = id;
    }
    async doStuff(doStuff = new AnotherClass(this.id).isWhatever()) {
        console.warn(doStuff);
    }
}
console.warn(new Bug2(1).doStuff());`
inside a webpack module with settings
`java -jar closure-compiler-v20190325.jar --language_in ECMASCRIPT_2017 --language_out ECMASCRIPT5 --compilation_level ADVANCED_OPTIMIZATIONS --jscomp_off=* --js=dist/closure-bug.js --js_output_file=dist/closure-bug.min.js`
results in error 
> java.lang.NullPointerException: NAME $jscomp$async$this 109 [length: 4] [source_file: dist/closure-bug.js]
>          at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
>          at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:726)
>          at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:564)
>          at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:427)
>          at com.google.javascript.jscomp.RemoveUnusedCode.traverseGetProp(RemoveUnusedCode.java:469) <...>

In case it's important, the code is generated with TS 3.4.3 with settings
{
"compilerOptions": {
 "target": "es2017",
 "module": "es2015",
 "strict": true,
 "noImplicitReturns": true
}
}
and webpack 4.30.0

Full code in attachment. Just the *.js file is enough, .ts is provided merely for information.
There are different attempts, some of them work, some create error.
One case ("SometimesWorks") compiles by itself, but creates error if compiled with other working examples. Other working examples compile fine in any combination, and buggy examples create error in any case.

[code.zip](https://github.com/google/closure-compiler/files/3089445/code.zip)

**Comment by acceptibru** [comment]
Here's a link to online example:

https://closure-compiler-debugger.appspot.com/#input0%3D%252F%252F%2520this%2520is%2520file%2520is%2520created%2520by%2520typescript%2520%2526%2520webpack%250A%252F%252F%2520trying%2520to%2520compile%2520with%250A%252F%252F%2520java%2520-jar%2520closure-compiler-v20190325.jar%2520--language_in%2520ECMASCRIPT_2017%2520--language_out%2520ECMASCRIPT5%2520--compilation_level%2520ADVANCED_OPTIMIZATIONS%2520--jscomp_off%253D*%2520--js%253Ddist%252Fclosure-bug.js%2520--js_output_file%253Ddist%252Fclosure-bug.min.js%250A%250A%250A%252F******%252F%2520(function(modules)%2520%257B%2520%252F%252F%2520webpackBootstrap%250A%252F******%252F%2520%2509%252F%252F%2520The%2520module%2520cache%250A%252F******%252F%2520%2509var%2520installedModules%2520%253D%2520%257B%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520The%2520require%2520function%250A%252F******%252F%2520%2509function%2520__webpack_require__(moduleId)%2520%257B%250A%252F******%252F%250A%252F******%252F%2520%2509%2509%252F%252F%2520Check%2520if%2520module%2520is%2520in%2520cache%250A%252F******%252F%2520%2509%2509if(installedModules%255BmoduleId%255D)%2520%257B%250A%252F******%252F%2520%2509%2509%2509return%2520installedModules%255BmoduleId%255D.exports%253B%250A%252F******%252F%2520%2509%2509%257D%250A%252F******%252F%2520%2509%2509%252F%252F%2520Create%2520a%2520new%2520module%2520(and%2520put%2520it%2520into%2520the%2520cache)%250A%252F******%252F%2520%2509%2509var%2520module%2520%253D%2520installedModules%255BmoduleId%255D%2520%253D%2520%257B%250A%252F******%252F%2520%2509%2509%2509i%253A%2520moduleId%252C%250A%252F******%252F%2520%2509%2509%2509l%253A%2520false%252C%250A%252F******%252F%2520%2509%2509%2509exports%253A%2520%257B%257D%250A%252F******%252F%2520%2509%2509%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%2509%252F%252F%2520Execute%2520the%2520module%2520function%250A%252F******%252F%2520%2509%2509modules%255BmoduleId%255D.call(module.exports%252C%2520module%252C%2520module.exports%252C%2520__webpack_require__)%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%2509%252F%252F%2520Flag%2520the%2520module%2520as%2520loaded%250A%252F******%252F%2520%2509%2509module.l%2520%253D%2520true%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%2509%252F%252F%2520Return%2520the%2520exports%2520of%2520the%2520module%250A%252F******%252F%2520%2509%2509return%2520module.exports%253B%250A%252F******%252F%2520%2509%257D%250A%252F******%252F%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520expose%2520the%2520modules%2520object%2520(__webpack_modules__)%250A%252F******%252F%2520%2509__webpack_require__.m%2520%253D%2520modules%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520expose%2520the%2520module%2520cache%250A%252F******%252F%2520%2509__webpack_require__.c%2520%253D%2520installedModules%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520define%2520getter%2520function%2520for%2520harmony%2520exports%250A%252F******%252F%2520%2509__webpack_require__.d%2520%253D%2520function(exports%252C%2520name%252C%2520getter)%2520%257B%250A%252F******%252F%2520%2509%2509if(!__webpack_require__.o(exports%252C%2520name))%2520%257B%250A%252F******%252F%2520%2509%2509%2509Object.defineProperty(exports%252C%2520name%252C%2520%257B%2520enumerable%253A%2520true%252C%2520get%253A%2520getter%2520%257D)%253B%250A%252F******%252F%2520%2509%2509%257D%250A%252F******%252F%2520%2509%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520define%2520__esModule%2520on%2520exports%250A%252F******%252F%2520%2509__webpack_require__.r%2520%253D%2520function(exports)%2520%257B%250A%252F******%252F%2520%2509%2509if(typeof%2520Symbol%2520!%253D%253D%2520'undefined'%2520%2526%2526%2520Symbol.toStringTag)%2520%257B%250A%252F******%252F%2520%2509%2509%2509Object.defineProperty(exports%252C%2520Symbol.toStringTag%252C%2520%257B%2520value%253A%2520'Module'%2520%257D)%253B%250A%252F******%252F%2520%2509%2509%257D%250A%252F******%252F%2520%2509%2509Object.defineProperty(exports%252C%2520'__esModule'%252C%2520%257B%2520value%253A%2520true%2520%257D)%253B%250A%252F******%252F%2520%2509%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520create%2520a%2520fake%2520namespace%2520object%250A%252F******%252F%2520%2509%252F%252F%2520mode%2520%2526%25201%253A%2520value%2520is%2520a%2520module%2520id%252C%2520require%2520it%250A%252F******%252F%2520%2509%252F%252F%2520mode%2520%2526%25202%253A%2520merge%2520all%2520properties%2520of%2520value%2520into%2520the%2520ns%250A%252F******%252F%2520%2509%252F%252F%2520mode%2520%2526%25204%253A%2520return%2520value%2520when%2520already%2520ns%2520object%250A%252F******%252F%2520%2509%252F%252F%2520mode%2520%2526%25208%257C1%253A%2520behave%2520like%2520require%250A%252F******%252F%2520%2509__webpack_require__.t%2520%253D%2520function(value%252C%2520mode)%2520%257B%250A%252F******%252F%2520%2509%2509if(mode%2520%2526%25201)%2520value%2520%253D%2520__webpack_require__(value)%253B%250A%252F******%252F%2520%2509%2509if(mode%2520%2526%25208)%2520return%2520value%253B%250A%252F******%252F%2520%2509%2509if((mode%2520%2526%25204)%2520%2526%2526%2520typeof%2520value%2520%253D%253D%253D%2520'object'%2520%2526%2526%2520value%2520%2526%2526%2520value.__esModule)%2520return%2520value%253B%250A%252F******%252F%2520%2509%2509var%2520ns%2520%253D%2520Object.create(null)%253B%250A%252F******%252F%2520%2509%2509__webpack_require__.r(ns)%253B%250A%252F******%252F%2520%2509%2509Object.defineProperty(ns%252C%2520'default'%252C%2520%257B%2520enumerable%253A%2520true%252C%2520value%253A%2520value%2520%257D)%253B%250A%252F******%252F%2520%2509%2509if(mode%2520%2526%25202%2520%2526%2526%2520typeof%2520value%2520!%253D%2520'string')%2520for(var%2520key%2520in%2520value)%2520__webpack_require__.d(ns%252C%2520key%252C%2520function(key)%2520%257B%2520return%2520value%255Bkey%255D%253B%2520%257D.bind(null%252C%2520key))%253B%250A%252F******%252F%2520%2509%2509return%2520ns%253B%250A%252F******%252F%2520%2509%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520getDefaultExport%2520function%2520for%2520compatibility%2520with%2520non-harmony%2520modules%250A%252F******%252F%2520%2509__webpack_require__.n%2520%253D%2520function(module)%2520%257B%250A%252F******%252F%2520%2509%2509var%2520getter%2520%253D%2520module%2520%2526%2526%2520module.__esModule%2520%253F%250A%252F******%252F%2520%2509%2509%2509function%2520getDefault()%2520%257B%2520return%2520module%255B'default'%255D%253B%2520%257D%2520%253A%250A%252F******%252F%2520%2509%2509%2509function%2520getModuleExports()%2520%257B%2520return%2520module%253B%2520%257D%253B%250A%252F******%252F%2520%2509%2509__webpack_require__.d(getter%252C%2520'a'%252C%2520getter)%253B%250A%252F******%252F%2520%2509%2509return%2520getter%253B%250A%252F******%252F%2520%2509%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520Object.prototype.hasOwnProperty.call%250A%252F******%252F%2520%2509__webpack_require__.o%2520%253D%2520function(object%252C%2520property)%2520%257B%2520return%2520Object.prototype.hasOwnProperty.call(object%252C%2520property)%253B%2520%257D%253B%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520__webpack_public_path__%250A%252F******%252F%2520%2509__webpack_require__.p%2520%253D%2520%2522%2522%253B%250A%252F******%252F%250A%252F******%252F%250A%252F******%252F%2520%2509%252F%252F%2520Load%2520entry%2520module%2520and%2520return%2520exports%250A%252F******%252F%2520%2509return%2520__webpack_require__(__webpack_require__.s%2520%253D%25200)%253B%250A%252F******%252F%2520%257D)%250A%252F************************************************************************%252F%250A%252F******%252F%2520(%255B%250A%252F*%25200%2520*%252F%250A%252F***%252F%2520(function(module%252C%2520__webpack_exports__%252C%2520__webpack_require__)%2520%257B%250A%250A%2522use%2520strict%2522%253B%250A__webpack_require__.r(__webpack_exports__)%253B%250A%252F*%2520harmony%2520export%2520(binding)%2520*%252F%2520__webpack_require__.d(__webpack_exports__%252C%2520%2522AnotherClass%2522%252C%2520function()%2520%257B%2520return%2520AnotherClass%253B%2520%257D)%253B%250A%250A%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%252F%252F%252F%252F%252F%252F%2520%2520START%2520OF%2520ACTUAL%2520CODE%250A%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%250A%250A%252F%252F%2520helper%2520class%250Aclass%2520AnotherClass%2520%257B%250A%2520%2520%2520%2520constructor(id)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.id%2520%253D%2520id%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520isWhatever()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520true%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A%252F%252F%252F%252F%252F%2520Each%2520creates%2520an%2520error%2520during%2520compilation%2520by%2520itself%250A%252F%252Fjava.lang.NullPointerException%253A%2520NAME%2520%2524jscomp%2524async%2524this%2520109%2520%255Blength%253A%25204%255D%2520%255Bsource_file%253A%2520dist%252Fclosure-bug.js%255D%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520at%2520com.google.common.base.Preconditions.checkNotNull(Preconditions.java%253A895)%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520at%2520com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java%253A726)%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520at%2520com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java%253A564)%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520at%2520com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java%253A427)%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520at%2520com.google.javascript.jscomp.RemoveUnusedCode.traverseGetProp(RemoveUnusedCode.java%253A469)%2520%253C...%253E%250Aclass%2520Bug1%2520%257B%250A%2520%2520%2520%2520constructor(id)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.id%2520%253D%2520id%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.doStuff()%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520async%2520doStuff(doStuff%2520%253D%2520new%2520AnotherClass(this.id).isWhatever())%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Bug1(1).id)%253B%250A%252F%252F%252F%252F%252F%250Aclass%2520Bug2%2520%257B%250A%2520%2520%2520%2520constructor(id)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.id%2520%253D%2520id%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520async%2520doStuff(doStuff%2520%253D%2520new%2520AnotherClass(this.id).isWhatever())%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Bug2(1).doStuff())%253B%250A%252F%252F%252F%252F%252F%250Aclass%2520Bug3%2520%257B%250A%2520%2520%2520%2520constructor(id%252C%2520obj%2520%253D%2520new%2520AnotherClass(id))%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.id%2520%253D%2520id%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.obj%2520%253D%2520obj%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520async%2520doStuff(doStuff%2520%253D%2520this.obj.isWhatever())%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Bug3(1).doStuff())%253B%250A%252F%252F%252F%252F%252F%250A%252F%252F%252F%252F%2520Works%2520by%2520itself%252C%2520but%2520doesn't%2520work%2520if%2520others%2520from%2520%2522Works%2522%2520are%2520uncommented%2520(%253F%253F%253F)%250Aclass%2520SometimesWorks%2520%257B%250A%2520%2520%2520%2520constructor(id)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520this.id%2520%253D%2520id%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520async%2520doStuff(doStuff%2520%253D%2520new%2520AnotherClass(this.id).isWhatever())%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520SometimesWorks(1).id)%253B%250A%252F%252F%252F%252F%252F%250A%252F%252F%252F%252F%252F%2520The%2520rest%2520seem%2520to%2520work%2520in%2520any%2520case%250Aclass%2520Works1%2520%257B%250A%2520%2520%2520%2520async%2520doStuff(doStuff)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Works1().doStuff(new%2520AnotherClass(1).isWhatever()))%253B%250A%252F%252F%252F%252F%252F%250Aconst%2520objw2%2520%253D%2520new%2520AnotherClass(1)%253B%250Aclass%2520Works2%2520%257B%250A%2520%2520%2520%2520async%2520doStuff(doStuff)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Works2().doStuff(objw2.isWhatever()))%253B%250A%252F%252F%252F%252F%252F%250Aclass%2520Works3%2520%257B%250A%2520%2520%2520%2520async%2520doStuff(doStuff)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Works3().doStuff())%253B%250A%252F%252F%252F%252F%252F%250Aconst%2520objw4%2520%253D%2520new%2520AnotherClass(1)%253B%250Aclass%2520Works4%2520%257B%250A%2520%2520%2520%2520async%2520doStuff(doStuff)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(doStuff%2520%253D%253D%253D%2520undefined)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520doStuff%2520%253D%2520objw4.isWhatever()%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Works4().doStuff())%253B%250A%252F%252F%252F%252F%252F%250Aconst%2520objw6%2520%253D%2520new%2520AnotherClass(1)%253B%250Aclass%2520Works6%2520%257B%250A%2520%2520%2520%2520async%2520doStuff(doStuff)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(doStuff%2520%253D%253D%253D%2520undefined)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520doStuff%2520%253D%2520objw6.isWhatever()%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520console.warn(doStuff)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aconsole.warn(new%2520Works6().doStuff())%253B%250A%252F%252F%252F%252F%252F%250A%250A%250A%252F***%252F%2520%257D)%250A%252F******%252F%2520%255D)%253B%26input1%26conformanceConfig%26externs%3Dfunction%2520alert(s)%2520%257B%257D%26refasterjs-template%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26MARK_NO_SIDE_EFFECT_CALLS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_PROTOTYPE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CHROME_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by tjgq** [comment]
Simpler repro:
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520o%2520%253D%2520%257B%257D%253B%250A%250AObject.defineProperty(o%252C%2520Symbol(%2522foo%2522)%252C%2520%257Bvalue%253A%2520%2522bar%2522%257D)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26MARK_NO_SIDE_EFFECT_CALLS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_PROTOTYPE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CHROME_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Actually, it looks like this isn't related to symbols at all; the compiler will crash if the second argument to `Object.defineProperty` is anything other than a string literal:

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520o%2520%253D%2520%257B%257D%253B%250A%250Afunction%2520s()%2520%257B%250A%2520%2520return%2520%2522foo%2522%253B%250A%257D%250A%250AObject.defineProperty(o%252C%2520s()%252C%2520%257Bvalue%253A%2520%2522bar%2522%257D)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26MARK_NO_SIDE_EFFECT_CALLS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_PROTOTYPE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CHROME_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by tjgq** [comment]
Created Google internal issue b/130739118

**Comment by tjgq** [comment]
Since the crash is in ChromePass, can you try passing `--chrome_pass=off` as a workaround and let us know if it works?
