### ISSUE TITLE
NullPointerException when using arrow functions with argument named "argument"

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3375]
Input for `SIMPLE_OPTIMIZATIONS`:

```
throw ((arguments) => {  })
```

Error output:

```
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(NAME arguments): /home/lganchin/repos/jqf-artifact/results/closure-knarr/failures/id_000001.input:1:8
throw ((arguments) => {  })
  Parent(PARAM_LIST): /home/lganchin/repos/jqf-artifact/results/closure-knarr/failures/id_000001.input:1:7
throw ((arguments) => {  })

	at com.google.javascript.jscomp.VarCheck$RedeclarationCheckHandler.onRedeclaration(VarCheck.java:462)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareVar(Es6SyntacticScopeCreator.java:330)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:191)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.populate(Es6SyntacticScopeCreator.java:134)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:91)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:35)
	at com.google.javascript.jscomp.NodeTraversal.getAbstractScope(NodeTraversal.java:1065)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:1141)
	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:193)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:401)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1011)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:819)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.NullPointerException
	... 35 more
```

Affects: v20190415 and current master (2375110b30ccb83b0a550c8c3d46c526e3896d62)

**Comment by EatingW** [comment]
Created internal issue http://b/132716087

**Comment by EatingW** [comment]
I believe there is an error of `Shadowing "arguments" is not allowed` but in any case it seems that the compiler should not be crashing.

**Comment by EatingW** [comment]
FYI here's the error. 
https://github.com/google/closure-compiler/blob/b61db9d1dbce79e8dd5f18f089d45f8f86471a55/src/com/google/javascript/jscomp/VarCheck.java#L79

**Comment by EatingW** [comment]
I also wasn't able to reproduce the error using the debugger
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Athrow%2520((arguments)%2520%253D%253E%2520%257B%2520%2520%257D)%250A

Could you provide the exact command you used that led to the crash?

**Comment by luisggpina** [comment]
I'm running these examples in the following Java class:

```
import com.google.javascript.jscomp.CompilationLevel;
import com.google.javascript.jscomp.CompilerOptions;
import com.google.javascript.jscomp.Result;
import com.google.javascript.jscomp.SourceFile;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assume.assumeTrue;

public class Compiler {

    static {
        java.util.logging.LogManager.getLogManager().reset();
    }

    // Compiler, options, and predefined JS environment
    private com.google.javascript.jscomp.Compiler compiler = new com.google.javascript.jscomp.Compiler(new PrintStream(new ByteArrayOutputStream(), false));
    private CompilerOptions options = new CompilerOptions();
    private SourceFile externs = SourceFile.fromCode("externs", "");

    public void initCompiler() {
        // Don't use threads
        compiler.disableThreads();
        // Don't print things
        options.setPrintConfig(false);
        // Enable all safe optimizations
        CompilationLevel.SIMPLE_OPTIMIZATIONS.setOptionsForCompilationLevel(options);
    }

    /** Compiles an input and returns its result */
    private Result compile(SourceFile input) {
        return compiler.compile(externs, input, options);
    }

    public static void main(String[] args) {
        Compiler t = new Compiler();
        t.compiler = new com.google.javascript.jscomp.Compiler(System.out);
        t.initCompiler();
        t.compiler.compile(t.externs, SourceFile.fromFile(args[0]), t.options);
    }
}
```

**Comment by luisggpina** [comment]
I realize now that my original report only has the `stderr` output, not the whole output.  Apologies for that.  Please find the full output below:

```
/tmp/tmp.ol2yiii2rd:1: ERROR - "arguments" cannot be redeclared in strict mode
throw ((arguments) => {  })
        ^^^^^^^^^

1 error(s), 0 warning(s)
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(NAME arguments): /tmp/tmp.ol2yiii2rd:1:8
throw ((arguments) => {  })
  Parent(PARAM_LIST): /tmp/tmp.ol2yiii2rd:1:7
throw ((arguments) => {  })

	at com.google.javascript.jscomp.VarCheck$RedeclarationCheckHandler.onRedeclaration(VarCheck.java:462)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareVar(Es6SyntacticScopeCreator.java:330)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:191)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.populate(Es6SyntacticScopeCreator.java:134)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:91)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:35)
	at com.google.javascript.jscomp.NodeTraversal.getAbstractScope(NodeTraversal.java:1065)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:1141)
	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:193)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:401)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1011)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:819)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.NullPointerException
	... 35 more
```

**Comment by lauraharker** [comment]
Here's a slightly simpler repro:

``` js
(arguments => {})
```

```
null
  Node(NAME arguments): input0:1:1
(arguments => {})
  Parent(PARAM_LIST): input0:1:1
(arguments => {})

	at com.google.javascript.jscomp.VarCheck$RedeclarationCheckHandler.onRedeclaration(VarCheck.java:464)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareVar(Es6SyntacticScopeCreator.java:331)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:192)
```

https://closure-compiler-debugger.appspot.com/#input0%3D(arguments%2520%253D%253E%2520%257B%257D)%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue
