### ISSUE TITLE
UnsupportedOperationException when using variable "arguments" inside arrow function body

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3376]
Input for `SIMPLE_OPTIMIZATIONS`:

```
a => (arguments * b)
```

Error output:

```
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(NAME arguments): /home/lganchin/repos/jqf-artifact/results/closure-knarr/min-fails-by-hand/id_000002.input:1:6
a => (arguments * b)
  Parent(MUL): /home/lganchin/repos/jqf-artifact/results/closure-knarr/min-fails-by-hand/id_000002.input:1:6
a => (arguments * b)

	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:222)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.visit(OptimizeArgumentsArray.java:141)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:987)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:861)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:906)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:371)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:381)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.process(OptimizeArgumentsArray.java:98)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2380)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:780)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage2Passes(Compiler.java:777)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:667)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.UnsupportedOperationException
	... 35 more
```

Affects: v20190415 and current master (2375110b30ccb83b0a550c8c3d46c526e3896d62)

**Comment by EatingW** [comment]
Created internal issue http://b/132717123

**Comment by NotWearingPants** [comment]
Note that an arrow function scope does not define an `arguments` symbol, so this is a reference to a symbol in a parent scope
