### ISSUE TITLE
NullPointerException when defining function named "arguments" inside arrow function

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3377]
Input for `SIMPLE_OPTIMIZATIONS`:

```
a => { function arguments(){  }}
```

Error output:

```
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(FUNCTION arguments): /home/lganchin/repos/jqf-artifact/results/closure-knarr/min-fails-by-hand/id_000003.input:1:7
a => { function arguments(){  }}
  Parent(BLOCK): /home/lganchin/repos/jqf-artifact/results/closure-knarr/min-fails-by-hand/id_000003.input:1:5
a => { function arguments(){  }}

	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.javascript.jscomp.ReferenceCollectingCallback.shouldTraverse(ReferenceCollectingCallback.java:280)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:815)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:987)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:861)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:906)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:401)
	at com.google.javascript.jscomp.ReferenceCollectingCallback.process(ReferenceCollectingCallback.java:113)
	at com.google.javascript.jscomp.VariableReferenceCheck.process(VariableReferenceCheck.java:117)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1011)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:819)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.NullPointerException
	... 31 more
```

Affects: v20190415 and current master (2375110b30ccb83b0a550c8c3d46c526e3896d62)

**Comment by EatingW** [comment]
Created internal issue http://b/132717341
