### ISSUE TITLE
IllegalStateException when using BITOR on variable named "arguments"

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3380]
Input for `SIMPLE_OPTIMIZATIONS`:

```
arguments |= (arguments => a)
```

Error output:

```
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

ASSIGN_BITOR 1 [length: 29] [source_file: /tmp/tmp.2H2is2i2ZG]
  Node(NAME arguments): /tmp/tmp.2H2is2i2ZG:1:14
arguments |= (arguments => a)
  Parent(PARAM_LIST): /tmp/tmp.2H2is2i2ZG:1:14
arguments |= (arguments => a)

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.javascript.jscomp.NodeUtil.getDeclaringParent(NodeUtil.java:3514)
	at com.google.javascript.jscomp.VarCheck$RedeclarationCheckHandler.onRedeclaration(VarCheck.java:463)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareVar(Es6SyntacticScopeCreator.java:330)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:191)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.populate(Es6SyntacticScopeCreator.java:134)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:91)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:35)
	at com.google.javascript.jscomp.NodeTraversal.getAbstractScope(NodeTraversal.java:1065)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:1141)
	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:193)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:401)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1011)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:819)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.IllegalStateException: ASSIGN_BITOR 1 [length: 29] [source_file: /tmp/tmp.2H2is2i2ZG]
	... 39 more
```

Affects: v20190415 and current master (2375110b30ccb83b0a550c8c3d46c526e3896d62)

**Comment by EatingW** [comment]
Created internal issue http://b/132727961

**Comment by luisggpina** [comment]
I realize now that my original report only has the `stderr` output, not the whole output.  Apologies for that.  Please find the full output below:

```
/tmp/tmp.1QvcNAqnNA:1: ERROR - "arguments" cannot be redeclared in strict mode
arguments |= (arguments => a)
              ^^^^^^^^^

1 error(s), 0 warning(s)
Exception in thread "main" java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

ASSIGN_BITOR 1 [length: 29] [source_file: /tmp/tmp.1QvcNAqnNA]
  Node(NAME arguments): /tmp/tmp.1QvcNAqnNA:1:14
arguments |= (arguments => a)
  Parent(PARAM_LIST): /tmp/tmp.1QvcNAqnNA:1:14
arguments |= (arguments => a)

	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.javascript.jscomp.NodeUtil.getDeclaringParent(NodeUtil.java:3514)
	at com.google.javascript.jscomp.VarCheck$RedeclarationCheckHandler.onRedeclaration(VarCheck.java:463)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareVar(Es6SyntacticScopeCreator.java:330)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.declareLHS(Es6SyntacticScopeCreator.java:191)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator$ScopeScanner.populate(Es6SyntacticScopeCreator.java:134)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:91)
	at com.google.javascript.jscomp.Es6SyntacticScopeCreator.createScope(Es6SyntacticScopeCreator.java:35)
	at com.google.javascript.jscomp.NodeTraversal.getAbstractScope(NodeTraversal.java:1065)
	at com.google.javascript.jscomp.NodeTraversal.getScope(NodeTraversal.java:1141)
	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:193)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:401)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:145)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1011)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:819)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:665)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
Caused by: java.lang.IllegalStateException: ASSIGN_BITOR 1 [length: 29] [source_file: /tmp/tmp.1QvcNAqnNA]
	... 39 more
```

**Comment by lauraharker** [comment]
This has the same root cause as https://github.com/google/closure-compiler/issues/3375
