### ISSUE TITLE
IllegalStateException when assigning the value of string length

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3382]
Input for `SIMPLE_OPTIMIZATIONS`:

```
"".length = 1
```

Error output:

```
Exception in thread "main" java.lang.IllegalStateException: Invalid child for ASSIGN node. Reference node:
NUMBER 0.0 1 [length: 9] [source_file: /tmp/tmp.w1M7cPGdI7]

 Parent node:
ASSIGN 1 [length: 13] [source_file: /tmp/tmp.w1M7cPGdI7]
    NUMBER 0.0 1 [length: 9] [source_file: /tmp/tmp.w1M7cPGdI7]
    NUMBER 1.0 1 [length: 1] [source_file: /tmp/tmp.w1M7cPGdI7]

	at com.google.javascript.jscomp.AstValidator$1.handleViolation(AstValidator.java:91)
	at com.google.javascript.jscomp.AstValidator.violation(AstValidator.java:1756)
	at com.google.javascript.jscomp.AstValidator.validateLHS(AstValidator.java:1128)
	at com.google.javascript.jscomp.AstValidator.validateAssignmentExpression(AstValidator.java:1418)
	at com.google.javascript.jscomp.AstValidator.validateExpression(AstValidator.java:310)
	at com.google.javascript.jscomp.AstValidator.validateExprStmt(AstValidator.java:1278)
	at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:220)
	at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:158)
	at com.google.javascript.jscomp.AstValidator.validateStatements(AstValidator.java:152)
	at com.google.javascript.jscomp.AstValidator.validateScript(AstValidator.java:141)
	at com.google.javascript.jscomp.AstValidator.validateCodeRoot(AstValidator.java:128)
	at com.google.javascript.jscomp.AstValidator.process(AstValidator.java:114)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:328)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:237)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2380)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:780)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:807)
	at com.google.javascript.jscomp.Compiler.stage2Passes(Compiler.java:777)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:667)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:634)
	at examples.CompilerTest.main(CompilerTest.java:67)
```

Affects: v20190415 and current master (2375110b30ccb83b0a550c8c3d46c526e3896d62)

**Comment by EatingW** [comment]
Created internal issue http://b/132729022

**Comment by lauraharker** [comment]
This has the same root cause as https://github.com/google/closure-compiler/issues/3379, so using that as the canonical issue.

The problem is that `PeepholeFoldConstants` optimizes [any string literal].length -> number without verifying that the string is not used as an lvalue.
https://github.com/google/closure-compiler/blob/bd445e7612318666c8068f0900b9153be4e309a1/src/com/google/javascript/jscomp/PeepholeFoldConstants.java#L1330
