### ISSUE TITLE
"Inner Types" causes internal compiler error

### ISSUE THREAD

**Issue by arv** [google/closure-compiler#3401]
Given code like this:

```js
// c.js
export class C {}
/** @enum {number} */
C.Type = {
  A: 1,
};
```

```js
// usage.js
import {C} from"./c.js";

class Usage {
  constructor() {
    /** @type {!Set<C.Type>} */
    this.foo = new Set();
  }
}
```

We are hitting an IllegalStateException here (we are using ModuleType SCRIPT): https://github.com/google/closure-compiler/blob/9d2bd505fe61549179ef456c1179ecf61d3276e9/src/com/google/javascript/jscomp/ModuleRenaming.java#L52-L73

Here is the full stack trace:

```
Unexpected module type: SCRIPT
  Node(ASSIGN): /code/static/js/core/experiment.js:19:8
        this.loggedExperiments_ = new Set();
  Parent(EXPR_RESULT): /code/static/js/core/experiment.js:19:8
        this.loggedExperiments_ = new Set();

  Node(SCRIPT): /code/static/js/core/experiment.js:3:0
import * as loop from "./loop.js";
  Parent(ROOT): [source unknown]

	at com.google.javascript.jscomp.ModuleRenaming.getGlobalName(ModuleRenaming.java:72)
	at com.google.javascript.jscomp.ModuleRenaming.getGlobalName(ModuleRenaming.java:83)
	at com.google.javascript.jscomp.ModuleRenaming.getGlobalName(ModuleRenaming.java:93)
	at com.google.javascript.jscomp.ModuleRenaming.getGlobalNameForJsDoc(ModuleRenaming.java:144)
	at com.google.javascript.jscomp.Es6RewriteModules$RenameGlobalVars.fixTypeNode(Es6RewriteModules.java:908)
	at com.google.javascript.jscomp.Es6RewriteModules$RenameGlobalVars.fixTypeNode(Es6RewriteModules.java:927)
	at com.google.javascript.jscomp.Es6RewriteModules$RenameGlobalVars.fixTypeNode(Es6RewriteModules.java:927)
	at com.google.javascript.jscomp.Es6RewriteModules$RenameGlobalVars.fixTypeNode(Es6RewriteModules.java:927)
	at com.google.javascript.jscomp.Es6RewriteModules$RenameGlobalVars.visit(Es6RewriteModules.java:845)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:867)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:987)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:861)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:906)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
	at com.google.javascript.jscomp.NodeTraversal.traverseClassMembers(NodeTraversal.java:968)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:859)
	at com.google.javascript.jscomp.NodeTraversal.traverseClass(NodeTraversal.java:951)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:857)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:804)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:371)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:381)
	at com.google.javascript.jscomp.Es6RewriteModules.visitScript(Es6RewriteModules.java:548)
	at com.google.javascript.jscomp.Es6RewriteModules.visit(Es6RewriteModules.java:378)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:806)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:371)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:381)
	at com.google.javascript.jscomp.Es6RewriteModules.processFile(Es6RewriteModules.java:186)
	at com.google.javascript.jscomp.Es6RewriteModules.hotSwapScript(Es6RewriteModules.java:175)
	at com.google.javascript.jscomp.Es6RewriteModules.process(Es6RewriteModules.java:164)
	at com.google.javascript.jscomp.Compiler.transpileAndDontCheck(Compiler.java:985)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:816)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:749)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected module type: SCRIPT
  Node(ASSIGN): /code/static/js/core/experiment.js:19:8
        this.loggedExperiments_ = new Set();
  Parent(EXPR_RESULT): /code/static/js/core/experiment.js:19:8
        this.loggedExperiments_ = new Set();
```

**Comment by arv** [comment]
@mihaip

**Comment by tjgq** [comment]
Can you show how you are invoking the compiler? I don't see a crash if I invoke the compiler with

```
java -jar ClosureCompiler.jar --js c.js --js usage.js
```

using the latest release.

**Comment by arv** [comment]
We figured out what is going on.

We do single file transpilation and we generate fake sources for the dependencies. These fake sources had the source `";"` which was not being treated as a `ES6_MODULE` but a `SCRIPT` which lead us to that error. If we generate the fake source `"export {}"` we get past that error. Of course our fake source has to be updated to export the right bindings but at least now we have a way forward.

Is there a way to tell the compiler to not validate that there is an exported binding? Are there some best practices for single file transpilation?
