### ISSUE TITLE
NullPointerException in Simple Mode attempting to call fully qualified name goog.reflect.objectProperty with no arguments

### ISSUE THREAD

**Issue by jkukucka** [google/closure-compiler#3455]
Input for `SIMPLE_OPTIMIZATIONS`:

```
(((goog.reflect.objectProperty)())[("")])
```

Error output:

```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:586)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:352)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:635)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:352)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:95)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1592)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:273)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:252)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:326)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:471)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:235)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2413)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:786)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:813)
	at com.google.javascript.jscomp.Compiler.stage2Passes(Compiler.java:783)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:673)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:640)
	at examples.CompilerTest.main(CompilerTest.java:67)
```

Affects: v20190819 and current master (21714316196c0b9807bb8622562bd1f8a9b9ad05)

**Comment by jkukucka** [comment]
Reproduced in the debugger here: https://closure-compiler-debugger.appspot.com/#input0%3D(((goog.reflect.objectProperty)())%255B(%2522%2522)%255D)%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by EatingW** [comment]
Created internal issue http://b/139877693
