### ISSUE TITLE
Travis CI build failing after 2019-10-08 GitHub push

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3478]
Link to the failing build is
https://travis-ci.org/google/closure-compiler/builds/595351077

relevant section of the build log seems to be this
```
  1) gulp-google-[secure]
       javascript version
         should generate a sourcemap for a single output file:
     Uncaught Error: gulp-google-[secure]: Compilation errors occurred
      at CompilationStream._compilationComplete (lib/gulp/index.js:244:28)
      at CompilationStream._flush (lib/gulp/index.js:164:16)
      at CompilationStream.prefinish (_stream_transform.js:141:10)
      at CompilationStream.EventEmitter.emit (domain.js:448:20)
      at prefinish (_stream_writable.js:635:14)
      at finishMaybe (_stream_writable.js:643:5)
      at endWritable (_stream_writable.js:663:3)
      at CompilationStream.Writable.end (_stream_writable.js:594:5)
      at DestroyableTransform.onend (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at DestroyableTransform.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  2) gulp-google-[secure]
       javascript version
         should generate a sourcemap for each output file with chunks:
     Uncaught Error: gulp-google-[secure]: Compilation errors occurred
      at CompilationStream._compilationComplete (lib/gulp/index.js:244:28)
      at CompilationStream._flush (lib/gulp/index.js:164:16)
      at CompilationStream.prefinish (_stream_transform.js:141:10)
      at CompilationStream.EventEmitter.emit (domain.js:448:20)
      at prefinish (_stream_writable.js:635:14)
      at finishMaybe (_stream_writable.js:643:5)
      at endWritable (_stream_writable.js:663:3)
      at CompilationStream.Writable.end (_stream_writable.js:594:5)
      at DestroyableTransform.onend (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at DestroyableTransform.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  3) gulp-google-[secure]
       javascript version
         should properly compose sourcemaps when multiple transformations are chained:
     Uncaught Error: gulp-google-[secure]: Compilation errors occurred
      at CompilationStream._compilationComplete (lib/gulp/index.js:244:28)
      at CompilationStream._flush (lib/gulp/index.js:164:16)
      at CompilationStream.prefinish (_stream_transform.js:141:10)
      at CompilationStream.EventEmitter.emit (domain.js:448:20)
      at prefinish (_stream_writable.js:635:14)
      at finishMaybe (_stream_writable.js:643:5)
      at endWritable (_stream_writable.js:663:3)
      at CompilationStream.Writable.end (_stream_writable.js:594:5)
      at DestroyableTransform.onend (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at DestroyableTransform.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (/home/travis/build/google/[secure]/node_modules/[secure]-npm/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 3
Command: /home/travis/.nvm/versions/node/v10.16.3/bin/node
Arguments: /home/travis/.yarn/lib/cli.js test
Directory: /home/travis/build/google/[secure]/node_modules/[secure]-npm/packages/google-[secure]
Output:
info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
The command "travis_util/test_npm.sh" exited with 3.

```

**Comment by brad4d** [comment]
Internal Google issue is http://b/142350707

**Comment by brad4d** [comment]
I got help from @ChadKillingsworth  to repro this, then @nreid260  figured out the fix and I confirmed it.
We'll submit a fix before today's push to GitHub.

**Comment by brad4d** [comment]
fix was pushed to GitHub and Travis build was successful.
