### ISSUE TITLE
NullPointerException when mismatching type is a primitive type in templates

### ISSUE THREAD

**Issue by jc-collet** [google/closure-compiler#3480]
The following code:
```javascript
const Foo = class Foo {
        constructor(v) {
                this.value = v;
        }
};

/**
 *
 * @template T
 * @param {function(new:T)} type
 * @param {T} value
 */
const bar = (type, value) => {
        console.log(`${type} , ${value}`);
};

bar(Foo, 0);
```
Triggers a **NullPointerException**:

java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.common.collect.ImmutableSet$Builder.add(ImmutableSet.java:483)
	at com.google.javascript.jscomp.InvalidatingTypes$Builder.addType(InvalidatingTypes.java:159)
	at com.google.javascript.jscomp.InvalidatingTypes$Builder.addAllTypeMismatches(InvalidatingTypes.java:120)
	at com.google.javascript.jscomp.DisambiguateProperties.<init>(DisambiguateProperties.java:396)
	at com.google.javascript.jscomp.DefaultPassConfig.lambda$new$52(DefaultPassConfig.java:2178)
	at com.google.javascript.jscomp.PassFactory.create(PassFactory.java:118)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:326)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:235)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2416)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:793)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

Suggested fix:
```
diff --git a/src/com/google/javascript/jscomp/InvalidatingTypes.java b/src/com/google/javascript/jscomp/InvalidatingTypes.java
index 9c35439a8..1337b8362 100644
--- a/src/com/google/javascript/jscomp/InvalidatingTypes.java
+++ b/src/com/google/javascript/jscomp/InvalidatingTypes.java
@@ -156,7 +156,8 @@ final class InvalidatingTypes {
             recordInvalidation(proto, mismatch);
           }
           if (objType.isConstructor()) {
-            types.add(objType.toMaybeFunctionType().getInstanceType());
+            ObjectType ot = objType.toMaybeFunctionType().getInstanceType();
+            types.add(ot != null ? ot : objType);
           } else if (objType.isInstanceType()) {
             types.add(objType.getConstructor());
           }
```

Here is the output with the fix applied:

```
hello.js:17: WARNING - [JSC_TYPE_MISMATCH] actual parameter 1 of bar does not match formal parameter
found   : (typeof Foo)
required: function(new:number): ?
bar(Foo, 0);
    ^^^
```

**Comment by concavelenz** [comment]
Repro:

https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520Foo%2520%253D%2520class%2520Foo%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520constructor(v)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520this.value%2520%253D%2520v%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%257D%253B%250A%250A%252F**%250A%2520*%250A%2520*%2520%2540template%2520T%250A%2520*%2520%2540param%2520%257Bfunction(new%253AT)%257D%2520type%250A%2520*%2520%2540param%2520%257BT%257D%2520value%250A%2520*%252F%250Aconst%2520bar%2520%253D%2520(type%252C%2520value)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2560%2524%257Btype%257D%2520%252C%2520%2524%257Bvalue%257D%2560)%253B%250A%257D%253B%250A%250Abar(Foo%252C%25200)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DEVIRTUALIZE_METHODS%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26OPTIMIZE_ARGUMENTS_ARRAY%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by concavelenz** [comment]
Created internal issue http://b/142424805
