### ISSUE TITLE
java.lang.NullPointerException: NAME goog 12

### ISSUE THREAD

**Issue by thebravoman** [google/closure-compiler#3484]
Playing around with '@implements' and an error occurred when the method 'getSpecial' has an '@export'

Running with 
````
java -jar $CLOSURE_PATH --js step.js --generate_exports  --compilation_level ADVANCED_OPTIMIZATIONS > result.js

````
Error is: 
````
java.lang.NullPointerException: NAME goog 12 [length: 4] [source_file: step.js]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:723)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:578)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:424)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseGetProp(RemoveUnusedCode.java:467)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:635)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:352)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1126)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:433)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:95)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1592)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:273)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:252)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:326)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:235)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2413)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:786)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```` 

Example is:

````
/**
 * @interface
 */
var IStep = function() {}

/** @return {IStep|null} */
IStep.prototype.getSpecial = function() {}

/**
 * @implements {IStep}
 */
class Implementor1 {
    constructor(parent = null) {
        /** @type {IStep|null} */
        this._parent = parent;
    }

    getNotSpecial() {
        return new Date();
    }

    /**	
     * @export
     * @return {IStep|null}
     */
    getSpecial() {
        if (this.getNotSpecial().now() > 2529644667834) {
            return null;
        }
        return this._parent;
    }
}

class Implementor2 {
    constructor() {}

    /**
     * @return {IStep} null
     */
    getSpecial() {
        return new Implementor1()
    }
}

const array = []
array.push(new Implementor1(new Implementor1()))
array.push(new Implementor2())
console.log(new Implementor1().getNotSpecial())
console.log(array[1].getSpecial())
````

**Comment by thebravoman** [comment]
Same error occurred for 

````
/**
 * @const
 * @namespace
 */
var NN = {}

/**
 * @interface
 * @export
 */
NN.IStep = function() {}
````

Am I missing something here?

````
java.lang.NullPointerException: NAME goog 11 [length: 4] [source_file: step.js]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:723)

````

**Comment by evmar** [comment]
Created Google internal http://b/142964491

**Comment by evmar** [comment]
We suspect that using @export triggers a reference to `goog.exportSymbol`, so you need the Closure base library involved.

**Comment by thebravoman** [comment]
I could not find an easy way to include goog.base. To include goog.require('goog.base') i need to have goog already defined. 

Changing as
````
goog.require('goog.base')
/**
 * @const
 * @namespace
 */
var NN = {}

/**
 * @interface
 */
NN.IStep = function() {}
````

for files
````
├── goog
│   └── base.js
├── result.js
└── step.js
````
and compiling gives me
````
step.js:1: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "goog.base" never defined.
goog.require('goog.base')
````

Reading at https://developers.google.com/closure/library/docs/gettingstarted

I am missing something fundamental here, but probably that's a discussion for another place.

**Comment by thebravoman** [comment]
Just copy pasted the content of closure/goog/base on top of my file. It is compiling and I can continue my learning from here. 

Thanks

**Comment by thebravoman** [comment]
On the '@export' documentation it is written that base should be included

````
````

**Comment by thebravoman** [comment]
On the export documentation
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#export

It is written that base should be included
````
Code that uses the @export annotation must either:

    include closure/base.js, or
    define both goog.exportSymbol and goog.exportProperty with the same method signature in their own codebase.
````

So I suppose it is not an error really.

**Comment by evmar** [comment]
Just a guess, but I think you can include base.js as an additional input to your compilation, without modifying this file.

**Comment by DreierF** [comment]
I'm experiencing the same crash. For me this happens in a slightly different setting, but seems to have the same root cause.

```
import * as goog from '../goog.js';
let SOMETHING = goog.LOCALE;
export {SOMETHING};
```

Debugging into the compiler revealed that the `scope` only knows the variable `global$$module$__$closure_library_converted$closure$goog$goog` when it tries to look up `goog`.

Compiler version is v20191111.
