### ISSUE TITLE
J2CL Version Error with Input Source Maps

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3486]
A undefined reference exception is occurring when running under Node. Blocks https://github.com/google/closure-compiler-npm/pull/148

```
TypeError: Cannot read property 'parse' of undefined
    at aoa (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:560:33)
    at cBa (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:1168:75)
    at jWa (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3784:84)
    at r1a (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:1815:432)
    at ETb (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3777:289)
    at /Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3776:446
    at $$ (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3741:39)
    at DTb (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3776:23)
    at /Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3775:186
    at $$ (/Users/chad/git/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:3741:39)
```

Basic repo case:

test.js
```js
const jscomp = require('./gen/jscomp.js');
console.log(jscomp({},
  [{
    src:
      '/*\n * Copyright 2018 The Closure Compiler Authors.\n *\n * Licensed under the Apache License, Version 2.0 (the "License");\n * you may not use this file except in compliance with the License.\n * You may obtain a copy of the License at\n *\n *     http://www.apache.org/licenses/LICENSE-2.0\n *\n * Unless required by applicable law or agreed to in writing, software\n * distributed under the License is distributed on an "AS IS" BASIS,\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n * See the License for the specific language governing permissions and\n * limitations under the License.\n */\n\n/**\n * @fileoverview\n * @externs\n */\n\n/** @param {string} input */\nfunction externalMethod(input) {}\n',
    path: 'test/fixtures/extern.js',
    sourceMap:
      '{"version":3,"names":[],"mappings":"","sources":["test/fixtures/extern.js"],"sourcesContent":["/*\\n * Copyright 2018 The Closure Compiler Authors.\\n *\\n * Licensed under the Apache License, Version 2.0 (the \\"License\\");\\n * you may not use this file except in compliance with the License.\\n * You may obtain a copy of the License at\\n *\\n *     http://www.apache.org/licenses/LICENSE-2.0\\n *\\n * Unless required by applicable law or agreed to in writing, software\\n * distributed under the License is distributed on an \\"AS IS\\" BASIS,\\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\\n * See the License for the specific language governing permissions and\\n * limitations under the License.\\n */\\n\\n/**\\n * @fileoverview\\n * @externs\\n */\\n\\n/** @param {string} input */\\nfunction externalMethod(input) {}\\n"],"file":"test/fixtures/extern.js"}'
  }, {
    src:
      '/*\n * Copyright 2016 The Closure Compiler Authors.\n *\n * Licensed under the Apache License, Version 2.0 (the "License");\n * you may not use this file except in compliance with the License.\n * You may obtain a copy of the License at\n *\n *     http://www.apache.org/licenses/LICENSE-2.0\n *\n * Unless required by applicable law or agreed to in writing, software\n * distributed under the License is distributed on an "AS IS" BASIS,\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n * See the License for the specific language governing permissions and\n * limitations under the License.\n */\nfunction log(a) {\n  console.log(a)\n}\nlog(\'one.js\');\n',
    path: 'test/fixtures/one.js',
    sourceMap:
      '{"version":3,"names":[],"mappings":"","sources":["test/fixtures/one.js"],"sourcesContent":["/*\\n * Copyright 2016 The Closure Compiler Authors.\\n *\\n * Licensed under the Apache License, Version 2.0 (the \\"License\\");\\n * you may not use this file except in compliance with the License.\\n * You may obtain a copy of the License at\\n *\\n *     http://www.apache.org/licenses/LICENSE-2.0\\n *\\n * Unless required by applicable law or agreed to in writing, software\\n * distributed under the License is distributed on an \\"AS IS\\" BASIS,\\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\\n * See the License for the specific language governing permissions and\\n * limitations under the License.\\n */\\nfunction log(a) {\\n  console.log(a)\\n}\\nlog(\'one.js\');\\n"],"file":"test/fixtures/one.js"}' },
    { src:
      '/*\n * Copyright 2016 The Closure Compiler Authors.\n *\n * Licensed under the Apache License, Version 2.0 (the "License");\n * you may not use this file except in compliance with the License.\n * You may obtain a copy of the License at\n *\n *     http://www.apache.org/licenses/LICENSE-2.0\n *\n * Unless required by applicable law or agreed to in writing, software\n * distributed under the License is distributed on an "AS IS" BASIS,\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n * See the License for the specific language governing permissions and\n * limitations under the License.\n */\nclass WindowInfo {\n  constructor() {\n    this.props = [];\n\n  }\n  propList() {\n    for (var prop in window) {\n      this.props.push(prop);\n    }\n  }\n\n  list() {\n    log(this.props.join(\', \'));\n  }\n}\n\n(new WindowInfo()).list();\n',
      path: 'test/fixtures/two.js',
      sourceMap:
        '{"version":3,"names":[],"mappings":"","sources":["test/fixtures/two.js"],"sourcesContent":["/*\\n * Copyright 2016 The Closure Compiler Authors.\\n *\\n * Licensed under the Apache License, Version 2.0 (the \\"License\\");\\n * you may not use this file except in compliance with the License.\\n * You may obtain a copy of the License at\\n *\\n *     http://www.apache.org/licenses/LICENSE-2.0\\n *\\n * Unless required by applicable law or agreed to in writing, software\\n * distributed under the License is distributed on an \\"AS IS\\" BASIS,\\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\\n * See the License for the specific language governing permissions and\\n * limitations under the License.\\n */\\nclass WindowInfo {\\n  constructor() {\\n    this.props = [];\\n\\n  }\\n  propList() {\\n    for (var prop in window) {\\n      this.props.push(prop);\\n    }\\n  }\\n\\n  list() {\\n    log(this.props.join(\', \'));\\n  }\\n}\\n\\n(new WindowInfo()).list();\\n"],"file":"test/fixtures/two.js"}'
    }
   ]
));
```

Run the test with `node test.js`

**Comment by nreid260** [comment]
Created Google internal issue http://b/143092317
