### ISSUE TITLE
NullPointerException during compilation of cocos2d application

### ISSUE THREAD

**Issue by andrey-shikhov** [google/closure-compiler#3511]
closure compiler v20191111
I tried to compile some cocos2d application into single js using closure compiler, but it crashed on cocos2d main script which is attached below
[cocos2d-js-min.zip](https://github.com/google/closure-compiler/files/3892466/cocos2d-js-min.zip)

to reproduce: 
java -jar closure-compiler-v20191111.jar cocos2d-js-min.js

java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.javascript.jscomp.RemoveUnusedCode$ClassSetupCall.removeInternal(RemoveUnusedCode.java:2484)
	at com.google.javascript.jscomp.RemoveUnusedCode$Removable.remove(RemoveUnusedCode.java:1622)
	at com.google.javascript.jscomp.RemoveUnusedCode$VarInfo.removeAllRemovables(RemoveUnusedCode.java:2579)
	at com.google.javascript.jscomp.RemoveUnusedCode.removeUnreferencedVarsAndPolyfills(RemoveUnusedCode.java:1532)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:272)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:250)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:462)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2418)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:799)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rishipal** [comment]
Created internal issue - http://b/145236516
