### ISSUE TITLE
java.lang.RuntimeException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by Brijeshlakkad** [google/closure-compiler#3536]
```
The compiler is waiting for input via stdin.
Using remote compiler: closure-compiler.appspot.com ...

SERVER ERROR: blockly_compressed_vertical.js
java.lang.RuntimeException: java.lang.InterruptedException
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:795)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:838)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:978)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:862)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:370)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:380)
        at com.google.javascript.jscomp.CheckSideEffects.process(CheckSideEffects.java:73)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1035)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:838)
        at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:768)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:826)
        at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:766)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:684)
        at com.google.javascript.jscomp.webservice.backend.CompilerInvokerImpl.compile(CompilerInvokerImpl.java:44)
        at com.google.javascript.jscomp.webservice.backend.ServerController.executeRequest(ServerController.java:178)
        at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.serviceParsedRequest(CompilationRequestHandler.java:178)
        at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.service(CompilationRequestHandler.java:160)
        at com.google.javascript.jscomp.webservice.frontend.CompilationServlet.doPost(CompilationServlet.java:82)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
        at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
        at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:539)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
        at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
        at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
        at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
        at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:752)
        at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:715)
        at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:685)
        at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:877)
        at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
        ... 53 more
```

**Comment by Brijeshlakkad** [comment]
@MatrixFrog  Please, look into this issue, when you get time.

**Comment by Brijeshlakkad** [comment]
This is also throwing the error
`goog.isString is not a function`
Please, help me get this solved.
Thanks you

**Comment by kjin** [comment]
What did you run to get this error?

**Comment by Brijeshlakkad** [comment]
I thought that `goog.isString is not a function` was caused due to this error, but after that, I came to know [this](https://github.com/google/closure-compiler/issues/3537#issuecomment-573283829). 
Thank you :)
