### ISSUE TITLE
NullPointerException on $jscomp.reflectProperty()

### ISSUE THREAD

**Issue by luisggpina** [google/closure-compiler#3540]
Input for `SIMPLE_OPTIMIZATIONS`:

```
$jscomp.reflectProperty()
```

Error output:

```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:582)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:348)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:93)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1588)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:269)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:250)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:462)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2418)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:799)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:826)
	at com.google.javascript.jscomp.Compiler.stage2Passes(Compiler.java:796)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:686)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:653)
```

Reproduce URL:  https://closure-compiler-debugger.appspot.com/#input0%3D%2524jscomp.reflectProperty()%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26ALIAS_ALL_STRINGS%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26COLLAPSE_VARIABLE_DECLARATIONS%3Dtrue%26COLLAPSE_ANONYMOUS_FUNCTIONS%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26COLLAPSE_OBJECT_LITERALS%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CROSS_CHUNK_CODE_MOTION%3Dtrue%26CROSS_CHUNK_METHOD_MOTION%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26LABEL_RENAMING%3Dtrue%26OPTIMIZE_CALLS%3Dtrue%26REMOVE_ABSTRACT_METHODS%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26REMOVE_UNUSED_CLASS_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3Dtrue%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26REWRITE_FUNCTION_EXPRESSIONS%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26USE_TYPES_FOR_LOCAL_OPTIMIZATION%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26MOVE_FUNCTION_DECLARATIONS%3Dtrue%26SYNTHETIC_BLOCK_MARKER%3Dtrue%26CHROME_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Compiler Options (default options)
```
==== CompilerOptions ====
CompilerOptions{aggressiveFusion=false,
 aliasableStrings=[],
 aliasAllStrings=false,
 aliasHandler=com.google.javascript.jscomp.CompilerOptions$NullAliasTransformationHandler@17f6480,
 aliasStringsBlacklist=,
 allowHotswapReplaceScript=false,
 ambiguateProperties=false,
 angularPass=false,
 anonymousFunctionNaming=OFF,
 assumeClosuresOnlyCaptureReferences=false,
 assumeGettersArePure=true,
 assumeStrictThis=false,
 browserResolverPrefixReplacements={},
 brokenClosureRequiresLevel=ERROR,
 checkDeterminism=false,
 checkGlobalNamesLevel=OFF,
 checkGlobalThisLevel=OFF,
 checkMissingGetCssNameLevel=OFF,
 checksOnly=false,
 checkSuspiciousCode=false,
 checkSymbols=false,
 checkTypes=false,
 closurePass=true,
 coalesceVariableNames=true,
 collapseAnonymousFunctions=false,
 collapseObjectLiterals=true,
 collapseProperties=NONE,
 collapseVariableDeclarations=true,
 colorizeErrorOutput=false,
 computeFunctionSideEffects=false,
 conformanceConfigs=[],
 conformanceRemoveRegexFromPath=Optional.of(^((.*/)?google3/)?((^/)?(blaze|bazel)-out/[^/]+/bin/)?),
 continueAfterErrors=false,
 convertToDottedProperties=true,
 crossChunkCodeMotion=false,
 crossChunkCodeMotionNoStubMethods=false,
 crossChunkMethodMotion=false,
 dartPass=false,
 deadAssignmentElimination=true,
 declaredGlobalExternsOnWindow=true,
 defineReplacements={},
 dependencyOptions=DependencyOptions{mode=SORT_ONLY,
 entryPoints=[]},
 devirtualizeMethods=false,
 devMode=OFF,
 disambiguatePrivateProperties=false,
 disambiguateProperties=false,
 enableModuleRewriting=true,
 enforceAccessControlCodingConventions=false,
 environment=BROWSER,
 errorFormat=SINGLELINE,
 es6ModuleTranspilation=COMPILE,
 exportLocalPropertyDefinitions=false,
 exportTestFunctions=false,
 externExports=false,
 extractPrototypeMemberDeclarations=OFF,
 extraSmartNameRemoval=false,
 filesToPrintAfterEachPassRegexList=[],
 flowSensitiveInlineVariables=false,
 foldConstants=true,
 forceLibraryInjection=[],
 gatherCssNames=false,
 generateExports=false,
 generatePseudoNames=false,
 generateTypedExterns=false,
 idGenerators={},
 incrementalCheckMode=OFF,
 inferConsts=true,
 inferTypes=false,
 inlineConstantVars=false,
 inlineFunctionsLevel=LOCAL_ONLY,
 inlineGetters=false,
 inlineLocalVariables=true,
 inlineProperties=false,
 inlineVariables=false,
 inputDelimiter=// Input %num%,
 inputSourceMaps={},
 instrumentForCoverage=false,
 instrumentForCoverageOnly=false,
 instrumentBranchCoverage=false,
 j2clMinifierEnabled=true,
 j2clPassMode=AUTO,
 labelRenaming=true,
 languageIn=ECMASCRIPT_2019,
 languageOutIsDefaultStrict=Optional.absent(),
 legacyCodeCompile=false,
 lineBreak=false,
 lineLengthThreshold=500,
 markAsCompiled=false,
 maxFunctionSizeAfterInlining=-1,
 moduleRoots=[./],
 chunksToPrintAfterEachPassRegexList=[],
 moveFunctionDeclarations=false,
 nameGenerator=com.google.javascript.jscomp.DefaultNameGenerator@29774679,
 optimizeArgumentsArray=true,
 optimizeCalls=false,
 outputFeatureSet=Optional.absent(),
 outputJs=NORMAL,
 outputJsStringUsage=false,
 parentChunkCanSeeSymbolsDeclaredInChildren=false,
 parseJsDocDocumentation=TYPES_ONLY,
 pathEscaper=ESCAPE,
 polymerExportPolicy=LEGACY,
 preferLineBreakAtEndOfFile=false,
 preferSingleQuotes=false,
 preferStableNames=false,
 preserveDetailedSourceInfo=false,
 preserveGoogProvidesAndRequires=false,
 preserveTypeAnnotations=false,
 prettyPrint=false,
 preventLibraryInjection=false,
 printConfig=true,
 printInputDelimiter=false,
 printSourceAfterEachPass=false,
 processCommonJSModules=false,
 propertyInvalidationErrors={},
 propertyRenaming=OFF,
 protectHiddenSideEffects=true,
 quoteKeywordProperties=false,
 removeAbstractMethods=false,
 removeClosureAsserts=false,
 removeJ2clAsserts=true,
 removeDeadCode=true,
 removeUnusedClassProperties=false,
 removeUnusedConstructorProperties=false,
 removeUnusedLocalVars=true,
 removeUnusedPrototypeProperties=false,
 removeUnusedPrototypePropertiesInExterns=false,
 removeUnusedVars=false,
 renamePrefixNamespaceAssumeCrossChunkNames=false,
 replaceIdGenerators=false,
 replaceMessagesWithChromeI18n=false,
 replaceStringsFunctionDescriptions=[],
 replaceStringsPlaceholderToken=,
 replaceStringsReservedStrings=[],
 reserveRawExports=false,
 rewriteFunctionExpressions=false,
 rewritePolyfills=false,
 runtimeTypeCheck=false,
 shadowVariables=true,
 rewriteModulesBeforeTypechecking=true,
 skipNonTranspilationPasses=false,
 smartNameRemoval=false,
 sourceMapDetailLevel=ALL,
 sourceMapFormat=DEFAULT,
 sourceMapLocationMappings=[],
 stripNamePrefixes=[],
 stripNameSuffixes=[],
 stripTypePrefixes=[],
 stripTypes=[],
 summaryDetailLevel=1,
 tracer=OFF,
 transformAMDToCJSModules=false,
 trustedStrings=false,
 tweakProcessing=OFF,
 tweakReplacements={},
 emitUseStrict=Optional.absent(),
 useTypesForLocalOptimization=false,
 variableRenaming=LOCAL,
 warningsGuard=DiagnosticGroup<checkVars>(OFF),
 DiagnosticGroup<es5Strict>(ERROR),
 DiagnosticGroup<boundedGenerics>(OFF),
 com.google.javascript.jscomp.DiagnosticGroup@3ffc5af1(OFF),
 wrapGoogModulesForWhitespaceOnly=true}
==== WarningsGuard ====
DiagnosticGroup<j2clIncomaptible>(OFF),
 com.google.javascript.jscomp.SuppressDocWarningsGuard@1e643faf,
 DiagnosticGroup<checkVars>(OFF),
 DiagnosticGroup<es5Strict>(ERROR),
 DiagnosticGroup<boundedGenerics>(OFF),
 com.google.javascript.jscomp.DiagnosticGroup@3ffc5af1(OFF)
```

Affects: v20190415 and current master (bbaf89641d92ed7527a87781a6a03b00ea957235)

**Comment by evmar** [comment]
Fixed internally, will sync out.
