### ISSUE TITLE
Compiler Crashes on Symbol with --inject_libraries false

### ISSUE THREAD

**Issue by sebmarkbage** [google/closure-compiler#3576]
If you reference a Symbol while compiling ES2015 to ES5 with the inject_libraries option turned off the compiler crashes.

```js
// test.js
let x = Symbol.for('test');
```
```
java -jar closure-compiler-v20200315.jar test.js --language_in ECMASCRIPT_2015 --language_out ECMASCRIPT5_STRICT --inject_libraries false
```
```
java.lang.NullPointerException: NAME $jscomp 1 [length: 27] [source_file: test.js]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:719)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:574)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:420)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseGetProp(RemoveUnusedCode.java:463)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:425)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:631)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:348)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1122)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:429)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:93)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1588)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:269)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:250)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:462)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2418)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:799)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I noticed this comment while digging into it. I'm not sure if it's related at all. https://github.com/google/closure-compiler/blob/88d22e50e4f54c7b25ce62af6affb6c0c1c0950b/src/com/google/javascript/jscomp/Es6InjectRuntimeLibraries.java#L132

For context, we use closure-compiler to compile the published React bundle to npm. We _never_ want to inject a runtime - we'd rather rewrite our code than have runtime injected. We feature test if Symbol exists and use a fallback strategy otherwise so we don't need the polyfill. Atm we have to workaround the compiler crashing on this option. See https://github.com/facebook/react/pull/18449

**Comment by sher53** [comment]
Please fix this someone hacked me and added all this stuff which I don’t know what it means

**Comment by rishipal** [comment]
This is fixed with the latest release. 
Thanks!
