### ISSUE TITLE
Travis build for head commit failing

### ISSUE THREAD

**Issue by christiantjl** [google/closure-compiler#3640]
[![Current build status](https://travis-ci.org/google/closure-compiler.svg?branch=master)](https://travis-ci.org/google/closure-compiler)

Opened a new issue per @brad4d's request in another issue, trying to organize all of the info we have so far.  Please edit as necessary.

From #2480: 

> <details><summary>The error when running  "travis_util/test_npm.sh" (click to expand)</summary>
> 
> ```
> gulp-google-closure-compiler: TypeError: Cannot read property 'b' of null
>     at l6b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8754:375)
>     at xxd (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8173:160)
>     at h2b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:6214:103)
>     at Z1b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8414:290)
>     at $1b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:6685:102)
>     at u7b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:7561:205)
>     at E6b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:9304:502)
>     at Q7b.R7b [as lj] (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:9599:205421)
>     at c8b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:5955:36)
>     at s7b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:2432:23)
>     at C6b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:8344:190)
>     at M7b.N7b [as lj] (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:9599:205206)
>     at c8b (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:5955:36)
>     at TYd (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:9248:94)
>     at DYd (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:9453:918)
>     at cS (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:2508:29)
>     at fS (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:4031:44)
>     at /home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler-js/jscomp.js:4293:46
>     at CompilerJS.run (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler/lib/node/closure-compiler-js.js:54:17)
>     at CompilerJS.value (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler/test/gulp.js:61:50)
>     at CompilationStream._flush (/home/travis/build/google/closure-compiler/node_modules/closure-compiler-npm/packages/google-closure-compiler/lib/gulp/index.js:159:20)
>     at CompilationStream.prefinish (_stream_transform.js:141:10)
>     at CompilationStream.emit (events.js:198:13)
>     at CompilationStream.EventEmitter.emit (domain.js:448:20)
>     at prefinish (_stream_writable.js:635:14)
>     at finishMaybe (_stream_writable.js:643:5)
>     at endWritable (_stream_writable.js:663:3)
>     at CompilationStream.Writable.end (_stream_writable.js:594:5)
>     at CompilationStream.onend (_stream_readable.js:672:10)
>     at Object.onceWrapper (events.js:286:20)
>     at CompilationStream.emit (events.js:198:13)
>     at CompilationStream.EventEmitter.emit (domain.js:448:20)
>     at endReadableNT (_stream_readable.js:1145:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> ```
> </details>
> 
> _Originally posted by @q2p in https://github.com/google/closure-compiler/issues/2480#issuecomment-656589719_

From #3631:

> I think we had two separate causes of the CI failing.
> 
> https://github.com/google/closure-compiler/pull/3627/files fixed the original cause of the broken CI, introduced when adding a J2CL build a few weeks ago.
> 
> While that PR was still in review, a change to source map lookup https://github.com/google/closure-compiler/commit/dac995ac563bfe3170280899112699845768e135 caused a different CI failure (the one Christian mentioned)
> 
> I compared the Travis builds [before](https://travis-ci.org/github/google/closure-compiler/builds/704072791) and [after](https://travis-ci.org/github/google/closure-compiler/builds/704117152) the source map change https://github.com/google/closure-compiler/commit/dac995ac563bfe3170280899112699845768e135. Both builds fail but the failure message changes.
> 
> That commit was actually attempt #2 at making the caching sourcemap lookup. I was [originally submitted in late May](https://github.com/google/closure-compiler/commit/939a7bb101ff60c1ba18dd6d7ff4f46d276d2014) then reverted in https://github.com/google/closure-compiler/commit/5f4e410752df4483c43e8b7e818bae32ab4c2a97 because of the CI failure. (The commit message does not specify that it's a rollback because of a quirk of how we scrub commits for GitHub). We probably didn't notice that the rollforward broke the CI again because it was already broken :(.
> 
> _Originally posted by @lauraharker in https://github.com/google/closure-compiler/issues/3631#issuecomment-658460005_

**Comment by christiantjl** [comment]
Oops, this is a dupe.
