### ISSUE TITLE
Re-export of default from commonjs module throws internal error

### ISSUE THREAD

**Issue by WearyMonkey** [google/closure-compiler#3657]
Affected compiler version:
20200101.0.0

Works in:
20191027.0.0

To reproduce:

```
// a.js 
import { kenobi } from './b.js';
console.log(kenobi);
```

```
// b.js
export { default as kenobi } from './c.js';
```

```
// c.js
module.exports = "hello there";
```

```
java -jar compiler.jar --process_common_js_modules --js a.js --js b.js --js c.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

unexpected qualified name: com.google.javascript.rhino.QualifiedName$GetpropQname@63eb9c8f
  Node(SCRIPT): b.js:1:0
export { default as kenobi } from './c.js';
  Parent(ROOT): [source unknown]

	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at com.google.javascript.jscomp.Es6RewriteModules.createExportsObject(Es6RewriteModules.java:628)
	at com.google.javascript.jscomp.Es6RewriteModules.visitScript(Es6RewriteModules.java:568)
	at com.google.javascript.jscomp.Es6RewriteModules.visit(Es6RewriteModules.java:394)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:844)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:445)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:456)
	at com.google.javascript.jscomp.Es6RewriteModules.process(Es6RewriteModules.java:172)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1054)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:855)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:785)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: unexpected qualified name: com.google.javascript.rhino.QualifiedName$GetpropQname@63eb9c8f
	... 21 more
```

**Comment by brad4d** [comment]
I didn't think we even supported importing JS common modules as if they were ES modules.

@ChadKillingsworth is this a use-case you care about supporting?

**Comment by WearyMonkey** [comment]
> I didn't think we even supported importing JS common modules.

It worked before, but if not a more meaningful error might be useful then.
