### ISSUE TITLE
JsCompiler crashes with `get` before class method

### ISSUE THREAD

**Issue by mbrukman** [google/closure-compiler#3687]
Minimized example (let's call it `get_fn.js`):

```js
/** @externs */

class Foo {
  get quux() { }
}
```

Let's try to compile it:

```
$ java -jar closure-compiler-v20200830.jar get_fn.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable $jscomp
  Node(NAME $jscomp): get_fn.js:3:0
class Foo {
  Parent(GETPROP): get_fn.js:3:0
class Foo {

	at com.google.javascript.jscomp.VarCheck.handleUndeclaredVariableRef(VarCheck.java:344)
	at com.google.javascript.jscomp.VarCheck.checkName(VarCheck.java:274)
	at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:209)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:909)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:443)
	at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:172)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2431)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:816)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unexpected variable $jscomp
	... 30 more
```

Interestingly enough, `get` specifically must be named that way, renaming it to another word causes JsCompiler to show a syntax error, e.g., if we have `bar_fn.js` as follows:

```js
/** @externs */

class Foo {
  bar quux() { }
}
```

JsCompiler reports a syntax error:

```
$ java -jar closure-compiler-v20200830.jar bar_fn.js
bar_fn.js:4:6: ERROR - [JSC_PARSE_ERROR] Parse error. '(' expected
  4|   bar quux() { }
           ^

1 error(s), 0 warning(s)
```

I've also tried other tokens there, and in all cases I tried, JsCompiler reported syntax errors. It appears there's some special handling for `get`, and it fails as described above.

Please let me know if you need any more information.

**Comment by blickly** [comment]
I can repro this, and in fact, I get a little more useful information as well:

```shell
get_fn.js:3:0: ERROR - [JSC_UNDEFINED_VARIABLE] variable $jscomp is undeclared
  3| class Foo {                                                                                                                                             
     ^^^^^^^^^^^                                                                                                                                             
  4|   get quux() { }                                                                                                                                        
     ^^^^^^^^^^^^^^^^                                                                                                                                        
  5| }                                                                                                                                                       
     ^                                                                       
                                                                                                                                                             
1 error(s), 0 warning(s)                                                                                                                                     
java.lang.RuntimeException: INTERNAL COMPILER ERROR.      
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).
                                                                              
Unexpected variable $jscomp                        
  Node(NAME $jscomp): /google/src/cloud/blickly/b168737776-rollbackConstantPropertySuppression/google3/get_fn.js:3:0
class Foo {
  Parent(GETPROP): /google/src/cloud/blickly/b168737776-rollbackConstantPropertySuppression/google3/get_fn.js:3:0
class Foo {

        at com.google.javascript.jscomp.VarCheck.handleUndeclaredVariableRef(VarCheck.java:344)
        at com.google.javascript.jscomp.VarCheck.checkName(VarCheck.java:274)
        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:209)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:909)
```

This looks like the `$jscomp` internal variable used for transpilation is being generated in externs where it is unexpected.
I confirmed that using `--langauge_out=ES_2015` or above avoids the crash.

I would guess that once we flip the switch to stop transpiling externs, this should go away.  Does that sound right to you, @brad4d?

**Comment by brad4d** [comment]
Yes, that sounds right to me.
At the moment all supported features are understood by all passes, so we really shouldn't need to transpile externs.
