### ISSUE TITLE
Update args4j version

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3693]
This repo uses version 2.0.26
https://github.com/google/closure-compiler/blob/801e3222c8c331fcb4b958e9495268a6369bb6bc/WORKSPACE.bazel#L20

The latest version (and the one used in the internal Google repo) is 2.33, which has a few new features I'd like to use.

I tried bumping the version in https://github.com/google/closure-compiler/commit/c335def8fd788900d43f86386b0a91722486079c but rolled it back in https://github.com/google/closure-compiler/commit/801e3222c8c331fcb4b958e9495268a6369bb6bc because of a failure in the NPM tests: https://github.com/google/closure-compiler/runs/1146472305?check_suite_focus=true.

```
Exception in thread "main" java.lang.IllegalArgumentException: class org.kohsuke.args4j.spi.PatternOptionHandler does not have the proper constructor
	at org.kohsuke.args4j.OptionHandlerRegistry.getConstructor(OptionHandlerRegistry.java:111)
	at org.kohsuke.args4j.OptionHandlerRegistry.access$000(OptionHandlerRegistry.java:43)
	at org.kohsuke.args4j.OptionHandlerRegistry$DefaultConstructorHandlerFactory.<init>(OptionHandlerRegistry.java:217)
	at org.kohsuke.args4j.OptionHandlerRegistry.registerHandler(OptionHandlerRegistry.java:138)
	at org.kohsuke.args4j.OptionHandlerRegistry.initHandlers(OptionHandlerRegistry.java:93)
	at org.kohsuke.args4j.OptionHandlerRegistry.<init>(OptionHandlerRegistry.java:67)
	at org.kohsuke.args4j.OptionHandlerRegistry.getRegistry(OptionHandlerRegistry.java:57)
	at org.kohsuke.args4j.CmdLineParser.createOptionHandler(CmdLineParser.java:178)
	at org.kohsuke.args4j.CmdLineParser.addOption(CmdLineParser.java:146)

```

**Comment by nreid260** [comment]
I think the solution is in updating this file https://github.com/google/closure-compiler-npm/blob/cda6bb7b56463ba388f2fb91f588f2ca6e36cd88/build-scripts/reflection-config.json
