### ISSUE TITLE
(Advance compilation) Destructuring assignment inside of a for-await condition causes INTERNAL COMPILER ERROR

### ISSUE THREAD

**Issue by TheCymaera** [google/closure-compiler#3725]
Command:
```
npx google-closure-compiler --compilation_level=ADVANCED --js=test.js --js_output_file=test.min.js 
```

The following causes an INTERNAL COMPILER ERROR. (Caused by: java.lang.NullPointerException)
```javascript
// test.js
window.onload = async function() {
	for await (const [key,value] of window["unknownAsyncIterable"]) console.log(key,value);
}
```

The following compiles successfully.
```javascript
// test.js
window.onload = async function() {
	for await (const entry of window["unknownAsyncIterable"]) {
		const [key,value] = entry;
		console.log(key,value);
	}
}
```

**Comment by rishipal** [comment]
The destructuring code crashes during type checking. 

Web-service Repro - [here.]( https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250A%252F%252F%2520test.js%250Awindow.onload%2520%253D%2520async%2520function()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520for%2520await%2520(const%2520%255Bkey%252Cvalue%255D%2520of%2520window%255B%2522unknownAsyncIterable%2522%255D)%2520console.log(key%252Cvalue)%253B%250A%257D)

Stack trace - 
```
23: java.lang.NullPointerException
	at com.google.javascript.jscomp.TypeCheck.getJSType(TypeCheck.java:3244)
	at com.google.javascript.jscomp.TypeCheck.visitVar(TypeCheck.java:2434)
	at com.google.javascript.jscomp.TypeCheck.visit(TypeCheck.java:668)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:909)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:902)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:948)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:854)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:880)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:842)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:877)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1037)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:905)
	at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:488)
	at com.google.javascript.jscomp.TypeCheck.check(TypeCheck.java:514)
	at com.google.javascript.jscomp.TypeCheck.process(TypeCheck.java:476)
	at com.google.javascript.jscomp.DefaultPassConfig$8.process(DefaultPassConfig.java:1816)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1045)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:845)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:775)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:833)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:773)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:691)
	at com.google.javascript.jscomp.webservice.backend.CompilerInvokerImpl.compile(CompilerInvokerImpl.java:44)
.....
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:781)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:744)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:714)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:900)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
```
