### ISSUE TITLE
Extending built-in ECMA externs

### ISSUE THREAD

**Issue by rendaw** [google/closure-compiler#3774]
I searched for existing issues, I'm fairly sure that no open issues are about this but there might have been a closed issue.

I'd like to extend ECMA externs for a project with new/experimental features: ClipboardItem, Intl.Segmenter, new fields in TextMetrics, etc.

Defining new classes is straightforward enough, but I don't think there's a way to add properties/methods to existing classes in an extern file.

I tried
```
Clipboard.write = function()...
```
which gave me
```
ERROR - assignment to property write of Clipboard
found   : function(string): ?
required: function(Array<(ClipboardItem|null)>): ?
Clipboard.write = function(/** !string */ text) {};
```

I tried `class Clipboard2 implements Clipboard` and the compiler crashed.

I defined `Clipboard2` as an unrelated class then tried to override the type of
```
/** @type {Clipboard2} */
Navigator.clipboard;
```
but this did nothing.

I ended up forcibly casting from `Clipboard` to `Clipboard2` and got my code to compile, but I don't know yet if it will run.

**Comment by concavelenz** [comment]
(1) Can you provide the stack trace for the crash? It certainly shouldn't crash.

(2) You should be able to add new properties but it seems you are trying to overwrite an existing one? Your new function definition needs to accept everything that the previous function definition did.

**Comment by rendaw** [comment]
Thanks for taking a look!

2. Sorry, my example above was kind of half-way through.  I tried assigning new functions, assigning new parameters, extending the class and replacing the type in Navigator, and replacing the type in Navigator.  The first gave an error, the last 3 didn't seem to do anything (still got errors about undefined properties).

Unfortunately I can't reproduce it now.  Actually, the build succeeds now even after deleting all my externs, so something's getting cached somewhere or else the definitions have been updated somehow on my system... I'll see what I can do.

1. Sure!  Adding `implements Clipboard` to
```
class Clipboard2 {
    write(/** !Array<ClipboardItem> */ items) {}

    writeText(/** !string */ text) {}

    /** @return {!Promise<DataTransfer>} */
    read() {}

    /** @return {!Promise<String>} */
    readText() {}
}
```
```
java.lang.RuntimeException: Exception parsing "bazel-out/k8-fastbuild/bin/.../editor.js.zip!/.../webview/compat/compatexterns.js"
	at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:155)
	at com.google.javascript.jscomp.JsAst.parse(JsAst.java:152)
	at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:55)
	at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:133)
	at com.google.javascript.jscomp.Compiler.hoistIfExtern(Compiler.java:1941)
	at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:1924)
	at com.google.javascript.jscomp.Compiler.orderInputs(Compiler.java:1800)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1701)
	at com.google.javascript.jscomp.Compiler.parseForCompilationInternal(Compiler.java:937)
	at com.google.javascript.jscomp.Compiler.lambda$parseForCompilation$4(Compiler.java:920)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:129)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:824)
	at com.google.javascript.jscomp.Compiler.parseForCompilation(Compiler.java:918)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:674)
	at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:255)
	at com.google.javascript.jscomp.JsChecker.access$300(JsChecker.java:63)
	at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:354)
	at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
	at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:69)
	at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
	at io.bazel.rules.closure.worker.PersistentWorker.runAsPersistentWorker(PersistentWorker.java:144)
	at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:84)
	at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.getEndOfArgCommentZones(IRFactory.java:1564)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processFormalParameterList(IRFactory.java:1712)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:3388)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:833)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processFunction(IRFactory.java:1666)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:3313)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:833)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processClassDeclaration(IRFactory.java:2671)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:3391)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:833)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1303)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:3351)
	at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:344)
	at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:144)
	... 22 more
```
My build is rather large so I'm afraid I don't know if this is a minimal example.

**Comment by rendaw** [comment]
Okay, sorry - on 1. I was assigning to `Clipboard` rather than `Clipboard.prototype`.  I'm not sure why the build works now, despite doing that incorrectly.  I was generally confused above I think, and trying it with a minimal example helped.

Thanks again!
