### ISSUE TITLE
GitHub CI is failing

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3795]
The first failure is shown here.

https://github.com/google/closure-compiler/runs/2281935888?check_suite_focus=true

The failing test is `NodeTest.java`.

The first commit to see the failure is "Combine Node::setLineno and Node::setCharno into a single method."

https://github.com/google/closure-compiler/commit/5d2e3696f4d6cd7b5976ed43b8d5a524f003bf0c

**Comment by brad4d** [comment]
I checked out head and ran `bazelisk test //:all` to reproduce the failure.
Then I ran `bazelisk //:test/com/google/javascript/rhino/NodeTest`

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test/com/google/javascript/rhino/NodeTest
-----------------------------------------------------------------------------
JUnit4 Test Runner
...............................E............
Time: 0.175
There was 1 failure:
1) testLinenoCharnoErroneous(com.google.javascript.rhino.NodeTest)
expected: -1
but was : 1048571
	at com.google.javascript.rhino.NodeTest.assertLinenoCharno(NodeTest.java:77)
	at com.google.javascript.rhino.NodeTest.testLinenoCharnoErroneous(NodeTest.java:65)

FAILURES!!!
Tests run: 43,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-04-07 16:06:02 --
```

**Comment by brad4d** [comment]
Looks like there's a bug that slipped through internally but was caught externally because of a difference in the size of `int`.

@nreid260 has already sent me a review for an internal change to fix it.

**Comment by brad4d** [comment]
Drat! I hit approve/submit on the change before I noticed it didn't reference this issue.
I'm just going to close this issue now, rather than risk forgetting to do so after the submission goes through.
