### ISSUE TITLE
Collapse Properties causing compiler crash

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3802]
Commit 15471d37ec0899504b34d3a6d58b06f187a18f11 is causing a compiler crash on my project. I'm still trying to figure out exactly why. Here's the stack trace.

```
  java.lang.IllegalStateException: Has no parent: GETPROP global 116:37  [length: 6] [source_file: node_modules/google-closure-library/closure/goog/base.js] : Color{singleton=SingletonColorFields{id=316231, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=316230, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=6139, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=6137, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=6136, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=c, debugInfo=DebugInfo{className=TOP_OBJECT, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[], invalidating=true, propertiesKeepOriginalName=false, constructor=false, ownProperties=[], nativeColorId=TOP_OBJECT, closureAssert=false}}], invalidating=false, propertiesKeepOriginalName=false, constructor=false, ownProperties=[addEventListener, dispatchEvent, removeEventListener], nativeColorId=null, closureAssert=false}}], invalidating=false, propertiesKeepOriginalName=false, constructor=false, ownProperties=[], nativeColorId=null, closureAssert=false}}, Color{singleton=SingletonColorFields{id=6138, debugInfo=DebugInfo{className=, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[Color{singleton=SingletonColorFields{id=c, debugInfo=DebugInfo{className=TOP_OBJECT, filename=}, prototype=null, instanceColor=null, disambiguationSupertypes=[], invalidating=true, propertiesKeepOriginalName=false, constructor=false, ownProperties=[], nativeColorId=TOP_OBJECT, closureAssert=false}}], invalidating=false, propertiesKeepOriginalName=false, constructor=false, ownProperties=[..lots of properties...], nativeColorId=null, closureAssert=false}}], invalidating=false, propertiesKeepOriginalName=false, constructor=false, ownProperties=[], nativeColorId=null, closureAssert=false}}], invalidating=false, propertiesKeepOriginalName=false, constructor=false, ownProperties=[...lots of properties...], nativeColorId=null, closureAssert=false}}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
        at com.google.javascript.rhino.Node.checkAttached(Node.java:901)
        at com.google.javascript.rhino.Node.replaceWith(Node.java:829)
        at com.google.javascript.jscomp.CollapseProperties.flattenNameRef(CollapseProperties.java:550)
        at com.google.javascript.jscomp.CollapseProperties.flattenReferencesTo(CollapseProperties.java:441)
        at com.google.javascript.jscomp.CollapseProperties.flattenReferencesToCollapsibleDescendantNames(CollapseProperties.java:352)
        at com.google.javascript.jscomp.CollapseProperties.flattenReferencesToCollapsibleDescendantNames(CollapseProperties.java:390)
        at com.google.javascript.jscomp.CollapseProperties.process(CollapseProperties.java:152)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2449)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:785)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ChadKillingsworth** [comment]
Nevermind - this appears to be a bazel problem. Once I did a full rebuild the problem no longer existed.
