### ISSUE TITLE
Internal compiler error with Collapse Properties and Webpack

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3808]
This looks to be a problem with the CollapseProperties changes I introduced.

```text
ERROR in closure-compiler: java.lang.RuntimeException: INTERNAL COMPILER ERROR.

Please report this problem.



com.google.javascript.rhino.Node cannot be cast to com.google.javascript.rhino.Node$StringNode
  Node(FUNCTION ): /****/workspace/platform-ux-pipeline_PR-10462/projects/shared/components/polymer3/jha/device-icon/jha-device-icon.js:3:46

__webpack_require__.e(/* import() */ 13).then(function() { return __webpack_require__.t(1536); });
  Parent(CALL): /****/workspace/platform-ux-pipeline_PR-10462/projects/shared/components/polymer3/jha/device-icon/jha-device-icon.js:3:0
__webpack_require__.e(/* import() */ 13).then(function() { return __webpack_require__.t(1536); });
	at com.google.javascript.rhino.Node.getString(Node.java:1085)
	at com.google.javascript.jscomp.ProcessCommonJSModules.getCommonJsImportPath(ProcessCommonJSModules.java:220)
        at com.google.javascript.jscomp.CollapseProperties$FindDynamicallyImportedModules.visit(CollapseProperties.java:1081)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:816)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:857)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1022)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:890)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1022)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:890)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1022)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:802)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:854)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1022)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:890)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:463)
	at com.google.javascript.jscomp.NodeTraversal.access$200(NodeTraversal.java:38)
	at com.google.javascript.jscomp.NodeTraversal$Builder.traverse(NodeTraversal.java:398)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:472)
	at com.google.javascript.jscomp.CollapseProperties.process(CollapseProperties.java:140)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2442)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:791)
	at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.ClassCastException: com.google.javascript.rhino.Node cannot be cast to com.google.javascript.rhino.Node$StringNode

	... 30 more
```

**Comment by brad4d** [comment]
@ChadKillingsworth was the PR we merged for you sufficient to fix this?

**Comment by ChadKillingsworth** [comment]
Yes - verified fixed.
