### ISSUE TITLE
Internal Compiler error when using ES6 destructuring

### ISSUE THREAD

**Issue by Wegi** [google/closure-compiler#3846]
When trying to compile bootstrap version 5 with the closure compiler the following error is thrown:

```
RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

LET 463:11  [length: 36] [source_file: node_modules/bootstrap/dist/js/bootstrap.js]
  Node(OBJECT_PATTERN): node_modules/bootstrap/dist/js/bootstrap.js:463:15
      for (let {
  Parent(DESTRUCTURING_LHS): node_modules/bootstrap/dist/js/bootstrap.js:463:15
      for (let {

        com.google.common.base.Preconditions.checkArgument (Preconditions.java:142)
        com.google.javascript.jscomp.Es6RewriteDestructuring.replacePattern (Es6RewriteDestructuring.java:357)
        com.google.javascript.jscomp.Es6RewriteDestructuring.visitPattern (Es6RewriteDestructuring.java:327)
        com.google.javascript.jscomp.Es6RewriteDestructuring.visit (Es6RewriteDestructuring.java:196)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:894)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:887)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:887)
        com.google.javascript.jscomp.NodeTraversal.traverseFunction (NodeTraversal.java:933)
        com.google.javascript.jscomp.NodeTraversal.handleFunction (NodeTraversal.java:814)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:857)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:887)
        com.google.javascript.jscomp.NodeTraversal.traverseFunction (NodeTraversal.java:933)
        com.google.javascript.jscomp.NodeTraversal.handleFunction (NodeTraversal.java:814)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:857)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:887)
        com.google.javascript.jscomp.NodeTraversal.traverseFunction (NodeTraversal.java:933)
        com.google.javascript.jscomp.NodeTraversal.handleFunction (NodeTraversal.java:814)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:857)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:887)
        com.google.javascript.jscomp.NodeTraversal.traverseFunction (NodeTraversal.java:933)
        com.google.javascript.jscomp.NodeTraversal.handleFunction (NodeTraversal.java:814)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:857)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:890)
        com.google.javascript.jscomp.NodeTraversal.traverseChildren (NodeTraversal.java:1022)
        com.google.javascript.jscomp.NodeTraversal.handleScript (NodeTraversal.java:802)
        com.google.javascript.jscomp.NodeTraversal.traverseBranch (NodeTraversal.java:854)
        com.google.javascript.jscomp.NodeTraversal.traverse (NodeTraversal.java:463)
        com.google.javascript.jscomp.NodeTraversal.access$200 (NodeTraversal.java:38)
        com.google.javascript.jscomp.NodeTraversal$Builder.traverse (NodeTraversal.java:398)
        com.google.javascript.jscomp.NodeTraversal.traverse (NodeTraversal.java:472)
        com.google.javascript.jscomp.TranspilationPasses.processTranspile (TranspilationPasses.java:448)
        com.google.javascript.jscomp.Es6RewriteDestructuring.process (Es6RewriteDestructuring.java:144)
        com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process (PhaseOptimizer.java:317)
        com.google.javascript.jscomp.PhaseOptimizer.process (PhaseOptimizer.java:232)
        com.google.javascript.jscomp.Compiler.check (Compiler.java:1030)
        com.google.javascript.jscomp.Compiler.performChecksAndTranspilation (Compiler.java:828)
        com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0 (Compiler.java:760)
        com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread (CompilerExecutor.java:127)
        com.google.javascript.jscomp.Compiler.runInCompilerThread (Compiler.java:816)
        com.google.javascript.jscomp.Compiler.stage1Passes (Compiler.java:758)
        com.google.javascript.jscomp.Compiler.compile (Compiler.java:675)
        sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
        sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke (Method.java:498)
        clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
        clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
        shadow.build.closure/convert-sources-simple*/fn--12677/fn--12678 (closure.clj:1929)
        shadow.build.closure/convert-sources-simple*/fn--12677 (closure.clj:1927)
        shadow.build.closure/convert-sources-simple* (closure.clj:1926)
        shadow.build.closure/convert-sources-simple* (closure.clj:1804)
        shadow.build.closure/convert-sources-simple (closure.clj:2098)
        shadow.build.closure/convert-sources-simple (closure.clj:2050)
        shadow.build.compiler/maybe-closure-convert (compiler.clj:1195)
        shadow.build.compiler/maybe-closure-convert (compiler.clj:1188)
        shadow.build.compiler/compile-all (compiler.clj:1440)
        shadow.build.compiler/compile-all (compiler.clj:1307)
        shadow.build.api/compile-sources (api.clj:261)
        shadow.build.api/compile-sources (api.clj:253)
        shadow.build/compile (build.clj:442)
        shadow.build/compile (build.clj:432)
        shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:363)
```

These are the line that are being referenced in the error message.

```
 for (let {
        target
      } = event; target && target !== this; target = target.parentNode) {
        for (let i = domElements.length; i--;) {
          if (domElements[i] === target) {
            event.delegateTarget = target;

            if (handler.oneOff) {
              // eslint-disable-next-line unicorn/consistent-destructuring
              EventHandler.off(element, event.type, selector, fn);
            }

            return fn.apply(target, [event]);
          }
        }
      } // To please ESLint
```

It seems that ES6 Style destructuring is not supported. Are there any plans to add it?

**Comment by mprobst** [comment]
In trying to come up with a minimal repro, I got this:

```
goog.module('main');

function x(
    /** !Event */ event, domElements, EventHandler, handler, selector, element,
    fn) {
  for (let {target} = event; target && target !== this;
       target = target.parentNode) {
    for (let i = domElements.length; i--;) {
      if (domElements[i] === target) {
        event.delegateTarget = target;

        if (handler.oneOff) {
          // eslint-disable-next-line unicorn/consistent-destructuring
          EventHandler.off(element, event.type, selector, fn);
        }

        return fn.apply(target, [event]);
      }
    }
  }  // To please ESLint
}
```

That repro's the crash, I believe:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

LET 6:7  [length: 20] [source_file: main.js]
  Node(OBJECT_PATTERN): main.js:6:11
  for (let {target} = event; target && target !== this;
  Parent(DESTRUCTURING_LHS): main.js:6:11
  for (let {target} = event; target && target !== this;

	at com.google.javascript.jscomp.JSCompiler.throwInternalError(JSCompiler.java:196)
	at com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException(NodeTraversal.java:442)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:462)
	at com.google.javascript.jscomp.NodeTraversal.traverse$ar$desugaring_accessor$dc56d17a_1(NodeTraversal.java)
	at com.google.javascript.jscomp.NodeTraversal$Builder.traverse(NodeTraversal.java:398)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:468)
	at com.google.javascript.jscomp.TranspilationPasses.processTranspile(TranspilationPasses.java:457)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.process(Es6RewriteDestructuring.java:147)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1221)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:1019)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$7(Compiler.java:930)
	at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalArgumentException: LET 6:7  [length: 20] [source_file: main.js]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:152)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.replacePattern(Es6RewriteDestructuring.java:352)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.visitPattern(Es6RewriteDestructuring.java:322)
	at com.google.javascript.jscomp.Es6RewriteDestructuring.visit(Es6RewriteDestructuring.java:191)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:888)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:879)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:879)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:879)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:879)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:927)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:792)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:835)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1016)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:780)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:832)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:459)
	... 15 more
```

**Comment by nreid260** [comment]
Should be fixed in the next release.
