### ISSUE TITLE
Errors when calling https://closure-compiler.appspot.com/compile

### ISSUE THREAD

**Issue by ScottHuston** [google/closure-compiler#3850]
For years we've been calling the RESTful API from a browser-based UI we created.  Today, I'm getting a CORS error.
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
```
```
sa_buildjs.asp:1 Access to XMLHttpRequest at 'https://closure-compiler.appspot.com/compile' from origin 
'https://xxx.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present 
on the requested resource.
```
From the response:
```
Referrer Policy: strict-origin-when-cross-origin
server: Google Frontend
x-cloud-trace-context: 00454f855d62f48c6407709c715d1b50
```
I'm not aware of any changes in our code that would affect this.  Here's the call we make:

```
var data = await $.ajax({
        method : "POST",
        url : "https://closure-compiler.appspot.com/compile",
        data : params.join("&"),
        dataType : "json",
        async : true,
        crossDomain : true,
        timeout : 90000
    });
```
Change to the service?

**Comment by ScottHuston** [comment]
Now it's returning a 404, even from the https://closure-compiler.appspot.com/compile (Hit Compile)

```
404: 
Original Post Data: 
output_format=json&output_info=compiled_code&output_info=warnings&output_info=errors&output_info=statistics&compilation_level=SIMPLE_OPTIMIZATIONS&warning_level=default&output_file_name=default.js&js_code=%2F%2F%20ADD%20YOUR%20CODE%20HERE%0Afunction%20hello(name)%20%7B%0A%20%20alert('Hello%2C%20'%20%2B%20name)%3B%0A%7D%0Ahello('New%20user')%3B
```

**Comment by lauraharker** [comment]
We deployed a new version around 11:30AM PST today. Looks like the /compile service has been emitting 404s since then.

Here's the stack trace I see in the logs:
```
java.io.IOException: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:56)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:595)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:474)
	at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.readResponse(Unknown Source)
	at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.queryMetadataAttribute(Unknown Source)
	at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.getProjectId(Unknown Source)
	at com.google.devtools.cdbg.debuglets.java.GcpHubClient.registerDebuggee(Unknown Source)
Caused by: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
	at com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:830)
	at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:103)
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:40)
	... 6 more
```

I just rolled back to the previous version (corresponding to the compiler release v20210601). It should be working now.

Assigned @h-joo as the current person on release rotation, although @blickly will take over tomorrow and might be the one to investigate.

**Comment by ScottHuston** [comment]
Thank you!

Please let me know if there's a better path to report errors with the REST api.

**Comment by brad4d** [comment]
I've had to make some changes to the method for deploying the webservice in order to properly support Java 11.
I've just pushed a fixed version of the service to users.

This version isn't an exact match to the external release we just did.
It includes a few changes made in the past few days.
However, it should work fine, and I'd like to know if it doesn't.
