### ISSUE TITLE
using 'undefinedNames' flag crashes v20210808

### ISSUE THREAD

**Issue by blq** [google/closure-compiler#3853]
Although v20210808 says the `--jscomp_*` `undefinedNames` option is deprecated and deleted I don't think it should lead to a compiler crash?

```
java.lang.NullPointerException: No warning class for name: undefinedNames
        at com.google.javascript.jscomp.jarjar.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:985)
        at com.google.javascript.jscomp.DiagnosticGroups.setWarningLevel(DiagnosticGroups.java:730)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.setWarningGuardOptions(AbstractCommandLineRunner.java:330)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.setRunOptions(AbstractCommandLineRunner.java:345)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1174)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:533)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2216)
```
Just ignoring it or preferably a more descriptive "unrecognized compiler option" would be the expected outcome for me.

**Comment by blickly** [comment]
I'd tend to agree with you that the "crash when the command line options are incorrect" approach does seem unnecessarily user-hostile.

That said, I'm not totally clear on if the infrastructure for creating real errors and warnings is accessible at the time `AbstractCommandLineRunner` is setting up these things, so it's not clear to me what the best way to fix it would be.

**Comment by blickly** [comment]
Actually, would crashing but with a better crash message be a reasonable alternative here?

If so, changing the message given at:
https://github.com/google/closure-compiler/blob/e8fed54882fd926580c150a319f3812887b26770/src/com/google/javascript/jscomp/DiagnosticGroups.java#L727
might be an easy way to improve the situation a bit.
