### ISSUE TITLE
Compiler not accurately tracking polyfill use of $jscomp.makeIterator

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#3890]
I'm using the Closure Compiler via the Java API in [shadow-cljs](https://github.com/thheller/shadow-cljs). I'm using it to process `npm` packages and polyfill when needed or configured to do so. Recently some code starting throwing at runtime with `$jscomp.makeIterator is not a function` errors. It appears that some code gets rewritten to use that but the (expected) `ensureLibraryInjected("es6/util/makeiterator")` never happens. This is also somewhat elusive to reproduce. As far as I can tell `es6/util/makeiterator` is referenced only by other polyfills so it'll sometimes be available if you happen to have other code that used those polyfills. If not however it'll just fail at runtime.

This call seems to create the rewrite:
https://github.com/google/closure-compiler/blob/c42989161269278a5c86683be70f4933f5f12333/src/com/google/javascript/jscomp/AstFactory.java#L1115

And it is used in two places
https://github.com/google/closure-compiler/blob/023718e521b4f1cb508ff7d177b3d8e50c0ad8d8/src/com/google/javascript/jscomp/Es6ForOfConverter.java#L88
https://github.com/google/closure-compiler/blob/524f612385c836730a194502b30c601090cface6/src/com/google/javascript/jscomp/Es6RewriteDestructuring.java#L626

Neither ensure that the polyfill is actually injected prior to using that.

I'm not entirely sure they are supposed and I have no small reproduction with only the Closure Compiler available as of now but it does happen reliably with my tool as shown in this [repro](https://github.com/svdo/shadow-cljs-948).

**Comment by lauraharker** [comment]
Right now these runtime libraries are meant to get injected by https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/InjectTranspilationRuntimeLibraries.java.

The reason for the indirection (i.e. why doesn't Es6ForOfConverter or Es6RewriteDestructuring inject them?) is that at one point, we wanted to do this library injection before the typechecking pass ran, but wanted to defer the actual transpilation passes until after typechecking to avoid mangling the AST.

In theory we could add a check in Es6ForOfConverter or Es6RewriteDestructuring to verify that yes, the InjectTranspilationRuntimeLibraries pass did actually inject these libraries like it was meant to. That would just make this a build-time error instead of a runtime error, though.

@thheller is there a way we could see the JS that's input to the compiler + the set of compiler options?

I was able to run the repro and see the error on `$jscomp.makeIterator`, but not sure how to debug further.

**Comment by thheller** [comment]
Unfortunately there currently is no option to dump the outputs and options that are fed to the compiler. Something I'll definitely add soon. In the meantime this file appears to be the problem case:

https://unpkg.com/react-bootstrap@2.0.2/cjs/Col.js

More specifically the desctruring around the `useCol(props)` call. The file is modified a little before compilation but nothing that should affect this issue. The compiler options are basically just using the OutputFeatureSet ES6 with SIMPLE optimizations.

**Comment by thheller** [comment]
I tried to reproduce with just the `npm` version and I get another error that I've also run into before. Just taking the `Col.js` from the link above I get

```
$ npx google-closure-compiler --js Col.js -O SIMPLE --language_out ECMASCRIPT_2015
java.lang.NullPointerException: NAME $jscomp 65:8  [length: 96] [source_file: Col.js]
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
        at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:895)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:751)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:571)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNormalOrOptChainGetProp(RemoveUnusedCode.java:629)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:577)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1305)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:807)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:498)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseDeclarationStatement(RemoveUnusedCode.java:1086)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:550)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1305)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseFunction(RemoveUnusedCode.java:1465)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:467)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1305)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:807)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:498)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseDeclarationStatement(RemoveUnusedCode.java:1086)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:550)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1305)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:581)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1305)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:581)
        at com.google.javascript.jscomp.RemoveUnusedCode.access$1200(RemoveUnusedCode.java:83)
        at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1829)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:412)
        at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:386)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:467)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
        at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2573)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$5(Compiler.java:939)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by lauraharker** [comment]
Thanks, that's very helpful.

This seems to happen with --language_out=ECMASCRIPT_2015 but not --language_out=ECMASCRIPT5. I suspect it's an issue with the combo of object spread (unsupported in ES 2015) and array destructuring (ok in ES 2015).

**Comment by brad4d** [comment]
I have a fix for this currently in review.
