### ISSUE TITLE
CI failure: Es6RewriteGeneratorsTest

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3903]
It appears the `Es6RewriteGeneratorsTest` is broken in our CI

http://go/gh/google/closure-compiler/actions/runs/1654975566

It seems to be broken by
http://go/gh/google/closure-compiler/commit/90cd9a9176a56ff5fd802d0e28e33001597a31f0

**Comment by brad4d** [comment]
Local run got these error messages

```
There were 2 failures:
1) testGeneratorForIn_withTypes(com.google.javascript.jscomp.Es6RewriteGeneratorsTest)
expected to contain: $jscomp.generator.Context.PropertyIterator
but was            : 
	at com.google.javascript.jscomp.Es6RewriteGeneratorsTest.testGeneratorForIn_withTypes(Es6RewriteGeneratorsTest.java:1419)
2) testYield_withTypes(com.google.javascript.jscomp.Es6RewriteGeneratorsTest)
expected to contain: $jscomp.generator.Context
but was            : 
	at com.google.javascript.jscomp.Es6RewriteGeneratorsTest.testYield_withTypes(Es6RewriteGeneratorsTest.java:1351)

FAILURES!!!
Tests run: 39,  Failures: 2
```

**Comment by brad4d** [comment]
A fix for this is currently being submitted.
