### ISSUE TITLE
Is it possible to install only native windows/linux/mac version of Closure Compiler, and skip Java version altogether?

### ISSUE THREAD

**Issue by juj** [google/closure-compiler#3926]
I find that when I perform a `npm install` of `google-closure-compiler`, I always get `google-closure-compiler-java` installed. That installation takes up 12.5MB of extra space on disk, and I would like to avoid this, and instead always use one of the native versions instead.

Is this kind of npm installation possible somehow?

**Comment by juj** [comment]
If I try to delete the directory `node_modules/google-closure-compiler-java` after the installation, that unfortunately does not work, but the JavaScript frontend fails to run.

```
E:\code\emsdk\emscripten\main>node_modules\.bin\google-closure-compiler --version
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'google-closure-compiler-java'
Require stack:
- E:\code\emsdk\emscripten\main\node_modules\google-closure-compiler\lib\node\closure-compiler.js
- E:\code\emsdk\emscripten\main\node_modules\google-closure-compiler\cli.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:93:18)←[39m
    at Object.<anonymous> (E:\code\emsdk\emscripten\main\node_modules\←[4mgoogle-closure-compiler←[24m\lib\node\closure-compiler.js:27:22)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'E:\\code\\emsdk\\emscripten\\main\\node_modules\\google-closure-compiler\\lib\\node\\closure-compiler.js'←[39m,
    ←[32m'E:\\code\\emsdk\\emscripten\\main\\node_modules\\google-closure-compiler\\cli.js'←[39m
  ]
}
```

**Comment by juj** [comment]
Changing line
```
const compilerPath = require('google-closure-compiler-java');
```
to
```
const compilerPath = '';
```
in `node_modules\google-closure-compiler\lib\node\closure-compiler.js` does seem to help here, and at least Emscripten closure test suite passes.

Would that be a safe thing to do? Would it be possible for Closure to officially support "Java-free" installation?
