### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read on arm64

### ISSUE THREAD

**Issue by strophy** [google/closure-compiler#3927]
I am trying to build [grpc/grpc-web](https://github.com/grpc/grpc-web) for arm64 architecture. This involves the following invocation triggered by `npm run build`:
```
/home/strophy/grpc-web/packages/grpc-web/node_modules/.bin/google-closure-compiler \
--js=exports.js --js=../../javascript --js=node_modules/google-closure-library \
--entry_point=grpc.web.Exports --externs=externs.js --dependency_mode=PRUNE \
--compilation_level=ADVANCED_OPTIMIZATIONS --generate_exports \
--export_local_property_definitions --js_output_file=index.js
```
This completes without any errors on x86_64. It throws the following error on arm64:
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at _Sd (/home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler-js/jscomp.js:7552:192)
    at YSd (/home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler-js/jscomp.js:9180:449)
    at sS (/home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler-js/jscomp.js:2442:29)
    at vS (/home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler-js/jscomp.js:3940:44)
    at /home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler-js/jscomp.js:4181:46
    at CompilerJS.run (/home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler/lib/node/closure-compiler-js.js:54:17)
    at /home/strophy/grpc-web/packages/grpc-web/node_modules/google-closure-compiler/cli.js:164:31 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
The JS files specified as directories like this `--js=../../javascript --js=node_modules/google-closure-library` is the cause of the error, removing these arguments results in an actual compiler error of `variable goog is undeclared`. Why is it not possible to declare `--js` arguments as directories on arm64? Or is this a syntax error in how the compiler is being invoked?

Version: 20200224.0.0
Node: 16.14.0

**Comment by strophy** [comment]
I was able to resolve this by updating to version 20220301.0.0.
