### ISSUE TITLE
`google-closure-compiler-linux` throwing Java exceptions.

### ISSUE THREAD

**Issue by robertfirek** [google/closure-compiler#3932]
Executing the following command:
```
npx google-closure-compiler target/resources/main/js/es6-bundle.js > target/resources/main/js/es5-bundle.js --language_in=ECMASCRIPT_2017 --language_out=ECMASCRIPT5 --compilation_level=SIMPLE_OPTIMIZATIONS --rewrite_polyfills=true --warning_level=QUIET --jscomp_off=checkVars --create_source_map target/resources/main/js/es5-bundle.js.map
```
produces the following error statement:
```
java.util.zip.ZipException: invalid entry CRC (expected 0x4e1f14a4 but got 0xb1e0eb5b)
        at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:410)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:199)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.getBuiltinExterns(AbstractCommandLineRunner.java:481)
        at com.google.javascript.jscomp.CommandLineRunner.createExterns(CommandLineRunner.java:2073)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1168)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:532)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2231)
```

I confirmed that the native compiler is executed in this case (from `google-closure-compiler-linux` package). Force refresh and reinstallation of modules doesn't fix the problem.

**Versions:**
"20220202.0.0", "20220405.0.0"

**Operating system:**
Linux 5.10.105-1-MANJARO x86_64

**Java version:**
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

**Comment by brad4d** [comment]
I've tried to reproduce this problem without success using a JS file I had hanging around.

```shell
npx google-closure-compiler \
    regex_test.js \
    --language_in=ECMASCRIPT_2017 \
    --language_out=ECMASCRIPT5 \
    --compilation_level=SIMPLE_OPTIMIZATIONS \
    --rewrite_polyfills=true \
    --warning_level=QUIET \
    --jscomp_off=checkVars \
    --create_source_map test.sourcemap
```

I got the output I expected.

Here's relevant version information 

```
$ npx --version
8.5.1

$ npx google-closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20220405

$ java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1, mixed mode, sharing)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux rodete
Release:	rodete
Codename:	rodete

$ uname -r
5.15.15-1rodete2-amd64
```

**Comment by noppa** [comment]
I also started running to this today. I'm not on computer right now so can't check all the specs for you yet, but what I do notice right away is that, like OP, I'm also using Manjaro

**Comment by lbguilherme** [comment]
I'm also having the exact same issue, on ArchLinux (inside WSL).

**Comment by brad4d** [comment]
Since I was unable to reproduce this problem with the latest release, and I doubt any of my coworkers can either.
I think we'll be dependent on folks in the OSS community to figure out what is happening here.

**Comment by lbguilherme** [comment]
Here is a single command that will reproduce the problem:

```
docker run --rm -ti archlinux bash -c "yes | pacman -Sy npm && \
npm i -g google-closure-compiler && google-closure-compiler --version && google-closure-compiler a.js; bash"
```

```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20220405
java.util.zip.ZipException: invalid entry CRC (expected 0x4e1f14a4 but got 0xb1e0eb5b)
        at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:410)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:199)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.getBuiltinExterns(AbstractCommandLineRunner.java:481)
        at com.google.javascript.jscomp.CommandLineRunner.createExterns(CommandLineRunner.java:2083)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1168)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:532)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2241)
```

**Comment by niloc132** [comment]
I've reproduced it also - you must specifically install `npx` for your platform and then run
```shell
$ npx google-closure-compiler
```
to get the issue. This immediately reproduces the problem, though doesn't make clear what the failure actually was. 

Next I downloaded the actual executable from npmjs.com
https://registry.npmjs.com/google-closure-compiler-java/-/google-closure-compiler-java-20220405.0.0.tgz

Untarred, this contains a file package/compiler.jar, which starts up correctly.

In the debug logs for the failure above, I also found a different link, which better matches the issue's title:
https://registry.npmjs.com/google-closure-compiler-linux/-/google-closure-compiler-linux-20220405.0.0.tgz

This apparently contains an x86 linux binary in package/compiler, according to https://www.npmjs.com/package/google-closure-compiler-linux this is a

> Linux native platform distribution of Closure Compiler.

Running this file is what results in the failure seen above. https://github.com/google/closure-compiler/#getting-started also references this binary distribution, as does https://www.npmjs.com/package/google-closure-compiler#user-content-native-binary-version.

I don't know how to build this distribution from the git repo with bazel, so I'm limited to stopping there and letting someone else take a look as to why the copy at npmjs.com might be corrupt somehow.
