### ISSUE TITLE
IllegalStateException: Expected a property access: ARRAY_PATTERN

### ISSUE THREAD

**Issue by ribrdb** [google/closure-compiler#3942]
This code compiles fine with --language_out=ECMASCRIPT5:

```js
    var Di = I(() => {
        function zv() {
            (e, [f] = (CN()))
        }
        function CN() {
            let t;
        }
    });
```

```
$ ./node_modules/.bin/google-closure-compiler \
    --language_out=ECMASCRIPT5 \
    --js_output_file=/tmp/out.js --js=test.js
WARNING - [JSC_UNKNOWN_DEFINE_WARNING] unknown @define variable goog.FEATURESET_YEAR

test.js:3:13: WARNING - [JSC_USELESS_CODE] Suspicious code. This code lacks side-effects. Is there a bug?
  3|             (e, [f] = (CN()))
                  ^

0 error(s), 2 warning(s)
```

But this crashes the compiler:
```
$ ./node_modules/.bin/google-closure-compiler \
    --browser_featureset_year=2020 \
    --js_output_file=/tmp/out.js \
    --js=test.js
java.lang.IllegalStateException: Expected a property access: ARRAY_PATTERN 3:16  [length: 2] [source_file: test.js]

        at com.google.javascript.jscomp.ExpressionDecomposer.exposeExpression(ExpressionDecomposer.java:230)
        at com.google.javascript.jscomp.ExpressionDecomposer.exposeExpression(ExpressionDecomposer.java:156)
        at com.google.javascript.jscomp.ExpressionDecomposer.maybeExposeExpression(ExpressionDecomposer.java:136)
        at com.google.javascript.jscomp.FunctionInjector$CallSiteType$6.prepare(FunctionInjector.java:476)
        at com.google.javascript.jscomp.FunctionInjector.maybePrepareCall(FunctionInjector.java:548)
        at com.google.javascript.jscomp.InlineFunctions.decomposeExpressions(InlineFunctions.java:789)
        at com.google.javascript.jscomp.InlineFunctions.process(InlineFunctions.java:147)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:267)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:405)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:186)
        at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2572)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$5(Compiler.java:936)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

I tried version 20220502.0.0 and 20220104.0.0

**Comment by ribrdb** [comment]
This switch statement looks suspicious:

```java
          switch (left.getToken()) {
            case GETELEM:
              decomposeSubExpressions(left.getLastChild(), null, state);
              // Fall through.
            case GETPROP:
              decomposeSubExpressions(left.getFirstChild(), null, state);
              break;
            default:
              throw new IllegalStateException("Expected a property access: " + left.toStringTree());
          }
```

Should that be something like
```java
          switch (left.getToken()) {
            case ARRAY_PATTERN:
            case GETELEM:
            case GETPROP:
              decomposeSubExpressions(left.getFirstChild(), null, state);
              break;
            default:
              throw new IllegalStateException("Expected a property access: " + left.toStringTree());
          }
```

**Comment by rishipal** [comment]
Able to reproduce at head.

**Comment by rishipal** [comment]
Fixed with 7bf4b5410ec4f5378e3dd4ddd9697ebad22634f5
