### ISSUE TITLE
IllegalArgumentException: Cannot read from TypedAST input stream

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#4067]
Problematic commit: 1f2cf2a5c57a232311925dd53109ea273f7a2694

```
$ echo "console.log(1);" | java -jar compiler_uberjar_deploy.jar`
The compiler is waiting for input via stdin.
java.lang.IllegalArgumentException: Cannot read from TypedAST input stream
	at com.google.javascript.jscomp.serialization.TypedAstDeserializer.deserializeTypedAsts(TypedAstDeserializer.java:417)
	at com.google.javascript.jscomp.serialization.TypedAstDeserializer.deserialize(TypedAstDeserializer.java:182)
	at com.google.javascript.jscomp.serialization.TypedAstDeserializer.deserializeRuntimeLibraries(TypedAstDeserializer.java:140)
	at com.google.javascript.jscomp.Compiler.initRuntimeLibraryTypedAsts(Compiler.java:645)
	at com.google.javascript.jscomp.serialization.ConvertTypesToColors.process(ConvertTypesToColors.java:116)
	at com.google.javascript.jscomp.DefaultPassConfig.lambda$new$83(DefaultPassConfig.java:2802)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:240)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:179)
	at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2917)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$6(Compiler.java:979)
	at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:100)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Unexpected field number 3 or wire type 7
	at com.google.javascript.jscomp.serialization.TypedAstDeserializer.deserializeTypedAsts(TypedAstDeserializer.java:408)
	... 14 more
```

**Comment by lauraharker** [comment]
I have a fix sent for internal code review
