### ISSUE TITLE
Internal Compiler Error for BigInt code

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#4078]
`test.js` compiling with `npx google-closure-compiler --js test.js`, using version `20230228.0.0`.
```
const q = 100n;
for (let o = q - 1n; o % 2n === 0n; o /= 2n) {
}
```

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(SHEQ): test.js:3:21
for (let o = q - 1n; o % 2n === 0n; o /= 2n) {
  Parent(FOR): test.js:3:0
for (let o = q - 1n; o % 2n === 0n; o /= 2n) {

        at com.google.javascript.jscomp.Compiler.throwInternalError(Compiler.java:3243)
        at com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException(NodeTraversal.java:509)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:529)
        at com.google.javascript.jscomp.NodeTraversal$Builder.traverse(NodeTraversal.java:465)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:535)
        at com.google.javascript.jscomp.NodeTraversal.traverseScopeRoots(NodeTraversal.java:735)
        at com.google.javascript.jscomp.PeepholeOptimizationsPass.process(PeepholeOptimizationsPass.java:67)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:240)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:378)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:179)
        at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2925)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$6(Compiler.java:979)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:100)
        at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.NullPointerException
        at com.google.javascript.jscomp.PeepholeFoldConstants.tryStrictEqualityComparison(PeepholeFoldConstants.java:1394)
        at com.google.javascript.jscomp.PeepholeFoldConstants.evaluateComparison(PeepholeFoldConstants.java:1423)
        at com.google.javascript.jscomp.PeepholeFoldConstants.tryFoldComparison(PeepholeFoldConstants.java:1167)
        at com.google.javascript.jscomp.PeepholeFoldConstants.tryFoldBinaryOperator(PeepholeFoldConstants.java:188)
        at com.google.javascript.jscomp.PeepholeFoldConstants.optimizeSubtree(PeepholeFoldConstants.java:104)
        at com.google.javascript.jscomp.PeepholeOptimizationsPass$PeepCallback.visit(PeepholeOptimizationsPass.java:82)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:963)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:953)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1131)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:847)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:902)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:953)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:526)
        ... 16 more
```

Encountered in the wild in npm package code from [this source](https://github.com/paulmillr/noble-curves/blob/19f04a4c1c85ac8c102f6f35c817855af3e0cc88/src/abstract/weierstrass.ts#LL1084C16-L1084C16). Trying to compile with shadow-cljs, yields a slightly different stacktrace but same error.

```
RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Cannot invoke "java.math.BigInteger.equals(Object)" because "lv" is null
  Node(SHEQ): node_modules/@noble/curves/abstract/weierstrass.js:916:25
    for (let o = q - 1n; o % 2n === 0n; o /= 2n)
  Parent(FOR): node_modules/@noble/curves/abstract/weierstrass.js:916:4
    for (let o = q - 1n; o % 2n === 0n; o /= 2n)

	com.google.javascript.jscomp.Compiler.throwInternalError (Compiler.java:3243)
	com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException (NodeTraversal.java:509)
	com.google.javascript.jscomp.NodeTraversal.traverse (NodeTraversal.java:529)
	com.google.javascript.jscomp.NodeTraversal$Builder.traverse (NodeTraversal.java:465)
	com.google.javascript.jscomp.NodeTraversal.traverse (NodeTraversal.java:535)
	com.google.javascript.jscomp.NodeTraversal.traverseScopeRoots (NodeTraversal.java:735)
	com.google.javascript.jscomp.PeepholeOptimizationsPass.process (PeepholeOptimizationsPass.java:67)
	com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process (PhaseOptimizer.java:240)
	com.google.javascript.jscomp.PhaseOptimizer$Loop.process (PhaseOptimizer.java:378)
	com.google.javascript.jscomp.PhaseOptimizer.process (PhaseOptimizer.java:179)
	com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations (Compiler.java:2925)
	com.google.javascript.jscomp.Compiler.lambda$stage2Passes$6 (Compiler.java:979)
	com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread (CompilerExecutor.java:126)
	com.google.javascript.jscomp.Compiler.runInCompilerThread (Compiler.java:1027)
	com.google.javascript.jscomp.Compiler.stage2Passes (Compiler.java:976)
	com.google.javascript.jscomp.Compiler.compile (Compiler.java:859)
	jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
	java.lang.reflect.Method.invoke (Method.java:578)
	clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
	clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
	shadow.build.closure/convert-sources-simple*/fn--13035/fn--13036 (closure.clj:2067)
	shadow.build.closure/convert-sources-simple*/fn--13035 (closure.clj:2065)
	shadow.build.closure/convert-sources-simple* (closure.clj:2064)
	shadow.build.closure/convert-sources-simple* (closure.clj:1928)
	shadow.build.closure/convert-sources-simple (closure.clj:2238)
	shadow.build.closure/convert-sources-simple (closure.clj:2188)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1244)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1237)
	shadow.build.compiler/compile-all (compiler.clj:1493)
	shadow.build.compiler/compile-all (compiler.clj:1356)
	shadow.build.api/compile-sources (api.clj:261)
	shadow.build.api/compile-sources (api.clj:253)
	shadow.build/compile (build.clj:512)
	shadow.build/compile (build.clj:493)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:368)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:349)
	shadow.cljs.devtools.server.worker.impl/fn--15470 (impl.clj:448)
	shadow.cljs.devtools.server.worker.impl/fn--15470 (impl.clj:437)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--15243/fn--15244/fn--15252 (util.clj:283)
	shadow.cljs.devtools.server.util/server-thread/fn--15243/fn--15244 (util.clj:282)
	shadow.cljs.devtools.server.util/server-thread/fn--15243 (util.clj:255)
	java.lang.Thread.run (Thread.java:1589)
Caused by:
NullPointerException: Cannot invoke "java.math.BigInteger.equals(Object)" because "lv" is null
	com.google.javascript.jscomp.PeepholeFoldConstants.tryStrictEqualityComparison (PeepholeFoldConstants.java:1394)
	com.google.javascript.jscomp.PeepholeFoldConstants.evaluateComparison (PeepholeFoldConstants.java:1423)
	com.google.javascript.jscomp.PeepholeFoldConstants.tryFoldComparison (PeepholeFoldConstants.java:1167)
	com.google.javascript.jscomp.PeepholeFoldConstants.tryFoldBinaryOperator (PeepholeFoldConstants.java:188)
	com.google.javascript.jscomp.PeepholeFoldConstants.optimizeSubtree (PeepholeFoldConstants.java:104)
	com.google.javascript.jscomp.PeepholeOptimizationsPass$PeepCallback.visit (PeepholeOptimizationsPass.java:82)
        ...
```

**Comment by nevedaren** [comment]
Thank you for the report. This is fixed with `20230502.0.0` release.
