### ISSUE TITLE
Duplicate declaration produces java.lang.IllegalStateException during inlining

### ISSUE THREAD

**Issue by katherine-hough** [google/closure-compiler#4096]
Duplicate declaration of x causes failure when attempt is made to inline x. I am not sure if the intended behavior for this input is to produce a compilation error indicating that the identifier was declared more than once or for the normalization pass to remove the duplicate declaration.

Closure Version:  v20230502
Command: `java -jar closure-compiler-v20230502.jar example.js --print_source_after_each_pass --compilation_level SIMPLE_OPTIMIZATIONS`
Input:
```
{
  var x;
  function x() {
  }
}
;
```

Output:
```
// parseInputs yields:
// ************************************
{var x;function x(){}};
// ************************************

// normalize yields:
// ************************************
{var x$jscomp$91;function x$jscomp$91(){}};
// ************************************
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

FUNCTION x$jscomp$91 3:2  [length: 18] [source_file: example.js] [change_time: 4567]
  Node(FUNCTION x$jscomp$91): example.js:3:2
  function x() {
  Parent(BLOCK): example.js:1:0
{

        at com.google.javascript.jscomp.Compiler.throwInternalError(Compiler.java:3233)
        at com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException(NodeTraversal.java:509)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:553)
        at com.google.javascript.jscomp.NodeTraversal$Builder.traverseRoots(NodeTraversal.java:473)
        at com.google.javascript.jscomp.ReferenceCollector.process(ReferenceCollector.java:103)
        at com.google.javascript.jscomp.InlineVariables.process(InlineVariables.java:103)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:240)
        at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:378)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:179)
        at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2933)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$6(Compiler.java:996)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:100)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: FUNCTION x$jscomp$91 3:2  [length: 18] [source_file: example.js] [change_time: 4567]
        at com.google.javascript.jscomp.jarjar.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior.removeDeclaration(InlineVariables.java:816)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior.inlineWellDefinedVariable(InlineVariables.java:796)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior$StandardVarExpert.lambda$createInlineWellDefinedVarAnalysis$2(InlineVariables.java:546)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior$PositiveInlineVarAnalysis.performInline(InlineVariables.java:630)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior.doInlinesForScope(InlineVariables.java:258)
        at com.google.javascript.jscomp.InlineVariables$InliningBehavior.afterExitScope(InlineVariables.java:226)
        at com.google.javascript.jscomp.ReferenceCollector$CollectorCallback.exitScope(ReferenceCollector.java:244)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:1183)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:1173)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:958)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1131)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:847)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:902)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:953)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:549)
        ... 13 more
```

**Comment by rahul-kamat** [comment]
This is invalid code anyway, and typescript throws an error message https://www.typescriptlang.org/play?#code/N4KABGBuCGBOYA8Dc4wDMCuA7AxgFwEsB7LRACgEoxQIBfEepIA

We should probably throw a better error message instead of making the compiler crash
