### ISSUE TITLE
Compiler crashes with dymamic improts (`IllegalStateException`)

### ISSUE THREAD

**Issue by corrideat** [google/closure-compiler#4126]
```
% echo 'const x = async () => { const buffer = await import(/** @type {string} */("buffer")); alert("1", buffer);}; x();' | google-closure-compiler -W QUIET --module_resolution WEBPACK -O ADVANCED
```

```
The compiler is waiting for input via stdin.
java.lang.IllegalStateException: AST should not contain Dynamic module import. Reference node:
DYNAMIC_IMPORT 1:45  [length: 39] [source_file: stdin]
    STRINGLIT buffer 1:74  [length: 8] [is_parenthesized: 1] [source_file: stdin]

 Parent node:
AWAIT 1:39  [length: 45] [source_file: stdin]
    DYNAMIC_IMPORT 1:45  [length: 39] [source_file: stdin]
        STRINGLIT buffer 1:74  [length: 8] [is_parenthesized: 1] [source_file: stdin]

        at com.google.javascript.jscomp.AstValidator$1.handleViolation(AstValidator.java:87)
        at com.google.javascript.jscomp.AstValidator.violation(AstValidator.java:2135)
        at com.google.javascript.jscomp.AstValidator.validateFeature(AstValidator.java:2214)
        at com.google.javascript.jscomp.AstValidator.validateExpression(AstValidator.java:456)
        at com.google.javascript.jscomp.AstValidator.validateAwait(AstValidator.java:635)
        at com.google.javascript.jscomp.AstValidator.validateExpression(AstValidator.java:452)
        at com.google.javascript.jscomp.AstValidator.validateNameDeclarationChild(AstValidator.java:1352)
        at com.google.javascript.jscomp.AstValidator.validateNameDeclarationHelper(AstValidator.java:1316)
        at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:210)
        at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:157)
        at com.google.javascript.jscomp.AstValidator.validateBlock(AstValidator.java:985)
        at com.google.javascript.jscomp.AstValidator.validateFunctionExpressionHelper(AstValidator.java:1103)
        at com.google.javascript.jscomp.AstValidator.validateFunctionExpression(AstValidator.java:1084)
        at com.google.javascript.jscomp.AstValidator.validateExpression(AstValidator.java:432)
        at com.google.javascript.jscomp.AstValidator.validateCall(AstValidator.java:1172)
        at com.google.javascript.jscomp.AstValidator.validateExpression(AstValidator.java:420)
        at com.google.javascript.jscomp.AstValidator.validateExprStmt(AstValidator.java:1561)
        at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:213)
        at com.google.javascript.jscomp.AstValidator.validateStatement(AstValidator.java:157)
        at com.google.javascript.jscomp.AstValidator.validateStatements(AstValidator.java:151)
        at com.google.javascript.jscomp.AstValidator.validateScript(AstValidator.java:140)
        at com.google.javascript.jscomp.AstValidator.validateCodeRoot(AstValidator.java:126)
        at com.google.javascript.jscomp.AstValidator.process(AstValidator.java:111)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:240)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:179)
        at com.google.javascript.jscomp.Compiler.performFinalizations(Compiler.java:2981)
        at com.google.javascript.jscomp.Compiler.lambda$stage3Passes$8(Compiler.java:1054)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:100)
        at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by frigus02** [comment]
Dynamic imports are only supported if the output chunk type is ES_MODULES. This works:

```
$ echo 'const x = async () => { const buffer = await import(/** @type {string} */("buffer")); alert("1", buffer);}; x();' | google-closure-compiler -W QUIET --module_resolution WEBPACK -O ADVANCED --chunk_output_type ES_MODULES
The compiler is waiting for input via stdin.
(async()=>{const a=await import("buffer");alert("1",a)})();export{};
```

The crash is not great, though. Would be nice if there was a good error message that mentioned the chunk type requirement.

**Comment by corrideat** [comment]
Thanks, I'll see if that works in my application.

> Dynamic imports are only supported if the output chunk type is ES_MODULES.

Hm, that may be a design decision you've made and I'm fine leaving it at that. However, dynamic imports are, in principle, allowed everywhere (providing support for `import`, of course). E.g., `<script>import('foo').finally(()=>alert("Yay!"))</script>` is perfectly valid, no need for `<script type="module">` there.

**Comment by hanguokai** [comment]
It works in `v20230502` and before, but it fails from `v20230802`. Hope this issue can be resolved soon.

**Comment by dasa** [comment]
> It works in `v20230502` and before, but it fails from `v20230802`.

Is this change a regression?

**Comment by emutime** [comment]
still report with google-clusure-compiler v20240317

out project has dozens of chunks

I'm export them from one js file named DynamicModules.js

it seem that if i list the chunk who includes DynamicModules.js,  it will report

```
// DynamicModules.js
export const Framework = async () => await import('Module/Basic/Framework');
export const ModuleBase = async () => await import('Module/Basic/ModuleBase'); // includes DynamicModules.js
... // dozens of
```
```
// B.js
import { Framework} from "DynamicModules";
async function test () {
    await Framework()
}
```

**Comment by repulsio** [comment]
Ironically, using the flag `--allow_dynamic_import` (with `--chunk_output_type=ES_MODULES`) still fails with the same error:

```
java.lang.IllegalStateException: AST should not contain Dynamic module import.
```

Any fix for this?

**Comment by ChadKillingsworth** [comment]
How this functions depends on the `language_out` level. Dynamic imports were not officially part of the language spec until 2021 even though browsers supported it many years prior. There is a `dynamic_import_alias` flag which is used to convert the `import()` statement into a function call in the AST so that it may be supported prior to a 2021 language level.

By specification, any JS file imported is considered a module. So if you import a JS script, that script is now semantically different than if you executed it without an import statement. The compiler has historically normalized outputs to be plain scripts expecting some sort of loader framework to dynamically add scripts to the output. The `--chunk_output_type ES_MODULES` flag tells the compiler to normalize all files to be considered modules whether they have module semantics or not. When code splitting, instead of normalizing references in other output chunks to global variables, the compiler will properly use `import` and `export` semantics and is much more modern.

I agree that the error message here is less than idea. I'll try to find time to work on an error message to instruct users how to rectify the issue.
