### ISSUE TITLE
Dataflow analysis appears to diverge around: WHILE 28288:118

### ISSUE THREAD

**Issue by 1vers1on** [google/closure-compiler#4160]
When using ADVANCED optimizations this happens.

```java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Dataflow analysis appears to diverge around: WHILE 28288:118  [length: 315922] [source_file: classes.js]
  Node(FUNCTION ESU): classes.js:28288:0
function ESU(a){var b,c,d,e,$p,$z;$p=0;if(Fi()){var $T=CZ();$p=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=C(6249);$p=1;case 1:CkL(b);if(B()){break _;}b=a.bhB;if(b!==null){$p=2;continue _;}c=a.X2;if(c!=(-1)){$p=3;continue _;}d=a.zy;if(d!=(-1)){$p=4;continue _;}d=a.Fl;if(d!=(-1)){$p=5;continue _;}d=a.zD;if(d!=(-1)){$p=6;continue _;}b=a.LZ;if(b!==null){$p=7;continue _;}d=a.p3;if(d!=(-1)){$p=8;continue _;}b=a.wY;if(b!==null){$p=9;continue _;}d=a.AW;if(d!=(-1)){$p=10;continue _;}b
  Parent(BLOCK): classes.js:2:311
(function(root,module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(root,exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){}else{module(root,root);}}(typeof self!=='undefined'?self:this,function($rt_globals,$rt_exports){var $rt_seed=2463534242;function $rt_nextId(){var x=$rt_seed;x^=x<<13;x^=x>>>17;x^=x<<5;$rt_seed=x;return x;}function $rt_compare(a,b){return a>b?1:a<b? -1:a===b?0:1;}function $rt_isInstance(obj,

        at com.google.javascript.jscomp.Compiler.throwInternalError(Compiler.java:3282)
        at com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException(NodeTraversal.java:516)
        at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:599)
        at com.google.javascript.jscomp.NodeTraversal$Builder.traverseWithScope(NodeTraversal.java:484)
        at com.google.javascript.jscomp.TypeInferencePass.inferAllScopes(TypeInferencePass.java:114)
        at com.google.javascript.jscomp.DefaultPassConfig.lambda$new$35(DefaultPassConfig.java:1836)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:240)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:179)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1297)
        at com.google.javascript.jscomp.Compiler.performChecks(Compiler.java:1085)
        at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$6(Compiler.java:994)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:100)
        at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
Caused by: java.lang.IllegalStateException: Dataflow analysis appears to diverge around: WHILE 28288:118  [length: 315922] [source_file: classes.js]
        at com.google.javascript.jscomp.DataFlowAnalysis.analyze(DataFlowAnalysis.java:220)
        at com.google.javascript.jscomp.TypeInferencePass.inferScope(TypeInferencePass.java:157)
        at com.google.javascript.jscomp.TypeInferencePass$SecondScopeBuildingCallback.enterScope(TypeInferencePass.java:195)
        at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:1153)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:990)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:857)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:903)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:951)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:1006)
        at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:857)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:903)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:951)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:951)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1134)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:845)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:900)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:951)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:951)
        at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:596)
        ... 15 more```

**Comment by dloyda** [comment]
Could you provide a way for us to reproduce this?
