### ISSUE TITLE
Trivial JS files throw java.lang.RuntimeException: INTERNAL COMPILER ERROR. in ECMASCRIPT6

### ISSUE THREAD

**Issue by gcirino42** [google/closure-compiler#581]
Thanks for the great tool!  Perhaps ES6 support isn't official yet, but some fairly trivial examples all threw fatal errors:

```bash
$ echo "" | java -jar ~/closure-compiler/compiler.jar --language_in ECMASCRIPT6
# or
$ echo "// just a comment" | java -jar ~/closure-compiler/compiler.jar --language_in ECMASCRIPT6
# or
$ echo "var x = 17 + 25; console.log(x);" | java -jar ~/closure-compiler/compiler.jar --language_in ECMASCRIPT6
```

They all return variants of:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.
null
  Node(BLOCK): externs.zip//es3.js:30:21
function Arguments() {}
  Parent(FUNCTION Arguments): externs.zip//es3.js:30:0
function Arguments() {}

        at com.google.common.base.Preconditions.checkState(Preconditions.java:161)
        at com.google.javascript.jscomp.FlowSensitiveInlineVariables.enterScope(FlowSensitiveInlineVariables.java:137)
        at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:652)
        at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:625)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:572)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:618)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:569)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:578)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:297)
        at com.google.javascript.jscomp.FlowSensitiveInlineVariables.process(FlowSensitiveInlineVariables.java:175)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1962)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:752)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:92)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:638)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:635)
        at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:682)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
        ... 24 more
```

Version info:
```bash
$ java -jar ~/closure-compiler/compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20140730
Built on: 2014/07/31 17:08
$ java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```

**Comment by Dominator008** [comment]
This has been fixed a while ago.
