### ISSUE TITLE
Chained object destructuring doesn't work

### ISSUE THREAD

**Issue by webbedspace** [google/closure-compiler#793]
Compiling the line `0,{a,b} = {c,d} = {a:1,b:2,c:3,d:4};` in ES6 mode results in this error:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected OBJECT_PATTERN parent: ASSIGN 3 [source_file: /var/folders/5s/dtrm6cxs7g7c9qfhvvg8pg9w0000gn/T/temp.js]
  Node(OBJECT_PATTERN): /var/folders/5s/dtrm6cxs7g7c9qfhvvg8pg9w0000gn/T/temp.js:3:2
0,{a,b} = {c,d} = {a:1,b:2,c:3,d:4};
  Parent(ASSIGN): /var/folders/5s/dtrm6cxs7g7c9qfhvvg8pg9w0000gn/T/temp.js:3:2
0,{a,b} = {c,d} = {a:1,b:2,c:3,d:4};

    at com.google.javascript.jscomp.Es6ToEs3Converter.visitObjectPattern(Es6ToEs3Converter.java:197)
    at com.google.javascript.jscomp.Es6ToEs3Converter.visit(Es6ToEs3Converter.java:173)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:587)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:630)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:575)
    at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:621)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:572)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:581)
    at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
    at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:538)
    at com.google.javascript.jscomp.Es6ToEs3Converter.process(Es6ToEs3Converter.java:86)
    at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
    at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
    at com.google.javascript.jscomp.Compiler.check(Compiler.java:850)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:763)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
    at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.IllegalStateException: Unexpected OBJECT_PATTERN parent: ASSIGN 3 [source_file: /var/folders/5s/dtrm6cxs7g7c9qfhvvg8pg9w0000gn/T/temp.js]
    ... 29 more
```

**Comment by lauraharker** [comment]
This seems to have been fixed (maybe in https://github.com/google/closure-compiler/commit/96ff5942cb7c28624c632c0104cbf48a5916fdeb)

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A0%252C%257Ba%252Cb%257D%2520%253D%2520%257Bc%252Cd%257D%2520%253D%2520%257Ba%253A1%252Cb%253A2%252Cc%253A3%252Cd%253A4%257D%253B%250A
