### ISSUE TITLE
ES6 Compilation - Internal Compiler Error

### ISSUE THREAD

**Issue by si-robertson** [google/closure-compiler#798]
I have been working on adding a new `--allow_es6_to_es6` flag (see #780), which went well, but the compiler is tripping over itself when it reaches a class constructor.

The console output is as follows:

````
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(EXPR_RESULT): test-es6-to-es6.js:5:4
    console.log('Foo');
  Parent(BLOCK): test-es6-to-es6.js:4:16
  constructor() {

        at com.google.javascript.jscomp.OptimizeArgumentsArray.tryReplaceArguments(OptimizeArguments Array.java:182)
        at com.google.javascript.jscomp.OptimizeArgumentsArray.exitScope(OptimizeArgumentsArray.java:127)
        at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:689)
````

**Comment by alexeagle** [comment]
This is the first of many issues with updating the optimization passes to work with es6 inputs. It's probably a good idea to add your flag to resolve #780 but it will only be useful to allow us to discover everything that is broken.

**Comment by MatrixFrog** [comment]
Right, NPEs like this are the reason I added the restriction in the first place :) Sorry, I probably should have been clearer about that.

**Comment by si-robertson** [comment]
Should I create a pull request for the new flag or wait until things have settled down a bit at your end?

**Comment by MatrixFrog** [comment]
The flag will be good to have, so we can find all the places where we don't
support ES6. The documentation for the flag should probably say "Note that
the compiler will probably crash if you use this flag" :)

**Comment by si-robertson** [comment]
Done.

**Comment by alexeagle** [comment]
Tyler: have a look at
https://github.com/alexeagle/closure-compiler/compare/allow_es6_to_es6?expand=1

for a first stab at disabling these broken passes when Si's flag is turned on.

**Comment by si-robertson** [comment]
I'm a bit stuck creating a new pull request at the moment because something somewhere keeps causing entire Java scripts to be flagged as modified by Git. I'm pretty sure it's a line-ending problem but I have no idea what's causing it. Git's autocrlf option is set to true. There's nothing in Eclipse that automatically modifies line-endings.

I will have to get this sorted out tomorrow.

**Comment by si-robertson** [comment]
Done.

**Comment by concavelenz** [comment]
es6-to-es6 should only work in whitespace only mode right now.  If it doesn't that should be readily fixable.
