### ISSUE TITLE
NPE when compiling ES6 -> ES6

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#799]
Synced to commit b0fa1d8860edb435545bc2c0b09993e8ec0a0982
with a local modification to bypass the prohibition against es6->es6 in CompilerOptionsPreprocessor

$ java -jar build/compiler.jar --language_in=ES6 --language_out=ES6 src/com/google/javascript/jscomp/js/runtime_type_check.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(RETURN): src/com/google/javascript/jscomp/js/runtime_type_check.js:55:4
    return expr;
  Parent(BLOCK): src/com/google/javascript/jscomp/js/runtime_type_check.js:54:41
  if ($jscomp.typecheck.suspendChecking) {

	at com.google.javascript.jscomp.OptimizeArgumentsArray.tryReplaceArguments(OptimizeArgumentsArray.java:182)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.exitScope(OptimizeArgumentsArray.java:127)
	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:689)
	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:680)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:633)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:622)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:574)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:291)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:540)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.process(OptimizeArgumentsArray.java:92)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1972)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	... 30 more

**Comment by alexeagle** [comment]
Dupe of #798
