### ISSUE TITLE
ES6->ES6: IllegalStateException in FlowSensitiveInlineVariables

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#801]
(Note: this is only reproducible if earlier broken passes are skipped)

$ java -jar build/compiler.jar --language_in=ES6 --language_out=ES6 src/com/google/javascript/jscomp/js/runtime_type_check.js

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(BLOCK): externs.zip//html5.js:1792:50
DataTransfer.prototype.getData = function(format) { return ''; };
  Parent(FUNCTION ): externs.zip//html5.js:1792:33
DataTransfer.prototype.getData = function(format) { return ''; };

	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at com.google.javascript.jscomp.FlowSensitiveInlineVariables.enterScope(FlowSensitiveInlineVariables.java:138)
	at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:656)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:629)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:622)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:574)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:318)
	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:299)
	at com.google.javascript.jscomp.FlowSensitiveInlineVariables.process(FlowSensitiveInlineVariables.java:176)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1972)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
	... 26 more

**Comment by dimvar** [comment]
Unless I'm missing sth, this is not an issue by itself.

It's part of the larger feature request to support ES6 in optimization passes, which will happen, but not for a while. Or are you thinking of sth else that I'm missing?

**Comment by alexeagle** [comment]
Talk to Tyler: this blocks any es6-out mode. No it won't be fixed for a
while but I have a workaround in-progress.
This issue is just to track remaining work.

**Comment by dimvar** [comment]
it shouldn't block any es6-out mode that we're currently interested in:
- when es6-to-es6 for whitespace only, optimizations shouldn't run
- when your pass is run, lang-in should be es5 and your pass runs after the optimizations, so they don't see es6

Anyway, since there has been no work to support es6 in optimizations, I think we should only have one issue for that, rather than one issue for every optimization pass.
(Note that if you don't see a crash with es6 in an optimization currently, it doesn't mean that the optimization is doing the right thing. It's probably doing some wrong transformation, but just doesn't crash.)

**Comment by alexeagle** [comment]
Note that I filed three bugs in addition to the original that Si filed, so you've only closed 1/4 that probably should all be treated the same.
Even with the Es6TypeDeclarations pass removed, this bug and the other three still prevent --language_out=es6 for any use case, including mine. (Even when my pass is on, it only attaches a property to Node's which no other code knows to read, so it's not a likely culprit.)
Perhaps there should be no es6 constructs in the inputs and therefore these passes ought to work with es6-out, but they currently don't.
