### ISSUE TITLE
ES6->ES6: IllegalStateException in DeadAssignmentsElimination

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#802]
Note: this is only reproducible if earlier broken passes are skipped.

$ java -jar build/compiler.jar --language_in=ES6 --language_out=ES6 src/com/google/javascript/jscomp/js/runtime_type_check.js

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(BLOCK): /Users/alexeagle/Projects/closure-compiler/src/com/google/javascript/jscomp/js/runtime_type_check.js:107:59
  if (typeof expr == 'object' && expr && expr.constructor) {
  Parent(IF): /Users/alexeagle/Projects/closure-compiler/src/com/google/javascript/jscomp/js/runtime_type_check.js:107:2
  if (typeof expr == 'object' && expr && expr.constructor) {

	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:351)
	at com.google.javascript.jscomp.NodeTraversal.traverseAtScope(NodeTraversal.java:387)
	at com.google.javascript.jscomp.DataFlowAnalysis.computeEscaped(DataFlowAnalysis.java:555)
	at com.google.javascript.jscomp.LiveVariablesAnalysis.<init>(LiveVariablesAnalysis.java:126)
	at com.google.javascript.jscomp.DeadAssignmentsElimination.enterScope(DeadAssignmentsElimination.java:103)
	at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:656)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:629)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:631)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:622)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:574)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:291)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:540)
	at com.google.javascript.jscomp.DeadAssignmentsElimination.process(DeadAssignmentsElimination.java:68)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:453)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1972)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
	... 34 more

**Comment by alexeagle** [comment]
Per @dimvar we won't keep separate issues open for each pass that isn't es6-ready.
