### ISSUE TITLE
I can't run closure compiler

### ISSUE THREAD

**Issue by j0101s** [google/closure-compiler#809]
Whenever I tried "java -jar compiler.jar", I got exception like below. Both windows 7 and ubuntu, it never worked.  How do I run it?

Environment: java version "1.6.0_20"

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.google.javascript.jscomp.CommandLineRunner. Program will exit.
```

**Comment by mprobst** [comment]
You need Java version 1.7 to run the compiler.jar that you downloaded.

**Comment by concavelenz** [comment]
This is in our FAQ: https://github.com/google/closure-compiler/wiki/FAQ#the-compiler-crashes-with-unsupportedclassversionerror-or-unsupported-majorminor-version-510

**Comment by j0101s** [comment]
yeah thanks. But if the msg is given out when java version is too low, that would be much helpful. Or in readme file.
