### ISSUE TITLE
Internal Compiler Error - Unexpected variable

### ISSUE THREAD

**Issue by kejloh** [google/closure-compiler#811]
I have a JS project with much automatically generated code.  It's working since many versions of my code and of closure compiler, but now I get an 'Internal Compiler Error' (in Line 741, see the end of this post).

The JS code defines many global string constants, and one of it, called $_$, seems to trigger the issue.  Curiously the same string constant is used several times above line 741 without errors.

```javascript
...
var $_$ = "";
...
function fnSetupGenRealtimeReference()
{
	fnSetupGenGroupBegin($_$);	// Line 741
	...
}
```

(How can I attach the complete JS code to this issue?)

I'm using this compiler: http://dl.google.com/closure-compiler/compiler-20150126.zip. When I go back to this version, the code compiles again without errors: http://dl.google.com/closure-compiler/compiler-20140110.zip.  All newer releases I found in the wiki at https://github.com/google/closure-compiler/wiki/Binary-Downloads show the same internal compiler error.

Here is the compiler-20150126's console output:

```code
>java -jar compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --js setup_10.js --js_output_file setup.js
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable $_$
  Node(NAME $_$): setup\generated\setup_10.js:741:22
        fnSetupGenGroupBegin($_$);
  Parent(CALL): setup\generated\setup_10.js:741:1
        fnSetupGenGroupBegin($_$);

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:198)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:588)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:622)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:574)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:318)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:140)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1972)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
        at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Unexpected variable $_$
        ... 23 more
```

**Comment by concavelenz** [comment]
@kejloh
This error means that the compiler has removed or renamed the definition but a reference remains (notice the VarCheck is during the optimize phase).  This is in fact an internal error.  Is it possible to provide a reproducible case that can be used to narrow down the problem?   Alternately, adding this option --dev_mode=EVERY_PASS should help narrow down where this problem is occurring during the optimization process.   Can you do that and report back?

**Comment by kejloh** [comment]
@MatrixFrog 
Here it is: http://dyn.jloh.de/closure-issue/closure-issue.zip

**Comment by concavelenz** [comment]
I thought with this enabled, we spit out the name of the pass before we checked them, maybe that was removed at some point, but having the code should allow someone to see where the value is being removed.

**Comment by kejloh** [comment]
@concavelenz 
Did you see the link to my test case?
http://dyn.jloh.de/closure-issue/closure-issue.zip

**Comment by MatrixFrog** [comment]
I managed to whittle that down to a much smaller repro:

    var x = "";
    
    foo(bar);
    
    function bar() {
      qux(x);
    }
    
    function bar() {
      qux(x);
    }

Obviously there's a duplicate definition of `bar` (less obvious in the full example, of course) but for some reason we crash instead of detecting that and reporting an error.

**Comment by MatrixFrog** [comment]
By the way `bar` in the real example is `fnSetupGenRealtimeLocalTimezone1`.

**Comment by kejloh** [comment]
Yes, you're absolutely right, thank you for figuring this out.  I think I have to fix a bug in my JS generation code.

Thanks a lot!

**Comment by MatrixFrog** [comment]
We should definitely fix this but in the meantime I would encourage you to turn on `--jscomp_error=checkVars` in which case you should get a clear error instead of a crash.

**Comment by kejloh** [comment]
Yes, it works for me, with my test case and with my real project, too.  Thanks!

**Comment by alex88** [comment]
Any update?
