### ISSUE TITLE
NPE when compiling with advanced optimisations

### ISSUE THREAD

**Issue by rightfold** [google/closure-compiler#870]
The following code:

    // ==ClosureCompiler==
    // @compilation_level ADVANCED_OPTIMIZATIONS
    // @output_file_name default.js
    // @formatting pretty_print
    // ==/ClosureCompiler==
    
    goog.provide("std");
    std.forcebool = function(x) {
        if (x === true || x === false) { return x; }
        throw "ouch";
    };
    std.unit = new (/** @constructor */ function() {})();
    
    goog.provide("std.io");
    std.io.writeln = function(value, __continue) {
        console.log(value);
        __continue(std.unit);
    };
    
    goog.provide("main");
    var __module = main;
    __module.main = function(__p0,  __continue) {
    var __camefrom;
    var __b1;
    var __b3;
    var __b4;
    var __b5;
    var __v2;
    var __v6;
    var __v7;
    var __v8;
    var __v9;
    var __v10;
    var __v11;
    var __v12;
    var __v13;
    var __v14;
    var __v15;
    var __v16;
    var __v17;
    var __v18;
    var __v19;
    var __v20;
    var __v21;
    var __v22;
    __b1 = function() {
    __v2 = std.unit;
    __v6 = __p0;
    __camefrom = 1;
    (std.forcebool(__v6) ? __b3 : __b4)();
    };
    __b3 = function() {
    __v8 = std.unit;
    __v9 = std.io;
    __v10 = __v9.writeln;
    __v11 = "Hello, world!";
    __v10(__v11,  function(__c12) {
    __v12 = __c12;
    __camefrom = 3;
    __b5();
    });
    };
    __b4 = function() {
    __v14 = std.unit;
    __v15 = std.io;
    __v16 = __v15.writeln;
    __v17 = "Byebye, world!";
    __v16(__v17,  function(__c18) {
    __v18 = __c18;
    __camefrom = 4;
    __b5();
    });
    };
    __b5 = function() {
    __v20 = {
        3: __v12,
        4: __v18
    }[__camefrom];
    __v21 = std.unit;
    __continue(__v21);
    };
    __b1();
    };
    
    main.main(true, function() {
        main.main(false, function() { });
    });

Results in the following error:

    23: java.lang.NullPointerException
    	at com.google.javascript.jscomp.NodeUtil.isNameDeclaration(NodeUtil.java:1840)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback$Reference.isDeclarationHelper(ReferenceCollectingCallback.java:655)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback$Reference.isDeclaration(ReferenceCollectingCallback.java:644)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback$Reference.isInitializingDeclaration(ReferenceCollectingCallback.java:695)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback$ReferenceCollection.getOneAndOnlyAssignment(ReferenceCollectingCallback.java:543)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback$ReferenceCollection.isAssignedOnceInLifetime(ReferenceCollectingCallback.java:513)
    	at com.google.javascript.jscomp.InlineVariables$InliningBehavior.collectAliasCandidates(InlineVariables.java:179)
    	at com.google.javascript.jscomp.InlineVariables$InliningBehavior.afterExitScope(InlineVariables.java:159)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback.exitScope(ReferenceCollectingCallback.java:251)
    	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:693)
    	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:684)
    	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:325)
    	at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:553)
    	at com.google.javascript.jscomp.ReferenceCollectingCallback.process(ReferenceCollectingCallback.java:117)
    	at com.google.javascript.jscomp.InlineVariables.process(InlineVariables.java:86)
    	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
    	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:453)
    	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
    	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1976)
    	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:771)
    	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
    	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
    	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
    	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:726)
    	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:654)
    	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:624)
    	at com.google.javascript.jscomp.webservice.backend.CompilerInvokerImpl.compile(CompilerInvokerImpl.java:47)
    	at com.google.javascript.jscomp.webservice.backend.ServerController.executeRequest(ServerController.java:177)
    	at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.serviceParsedRequest(CompilationRequestHandler.java:180)
    	at com.google.javascript.jscomp.webservice.backend.CompilationRequestHandler.service(CompilationRequestHandler.java:162)
    	at com.google.javascript.jscomp.webservice.frontend.CompilationServlet.doPost(CompilationServlet.java:83)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
    	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    	at org.mortbay.jetty.Server.handle(Server.java:326)
    	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
    	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
    	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    	at java.lang.Thread.run(Thread.java:724)
    
    Original Post Data: 
    output_format=json&output_info=compiled_code&output_info=warnings&output_info=errors&output_info=statistics&compilation_level=ADVANCED_OPTIMIZATIONS&warning_level=verbose&formatting=pretty_print&output_file_name=default.js&js_code=goog.provide(%22std%22)%3B%0Astd.forcebool%20%3D%20function(x)%20%7B%0A%20%20%20%20if%20(x%20%3D%3D%3D%20true%20%7C%7C%20x%20%3D%3D%3D%20false)%20%7B%20return%20x%3B%20%7D%0A%20%20%20%20throw%20%22fuck%22%3B%0A%7D%3B%0Astd.unit%20%3D%20new%20(%2F**%20%40constructor%20*%2F%20function()%20%7B%7D)()%3B%0A%0Agoog.provide(%22std.io%22)%3B%0Astd.io.writeln%20%3D%20function(value%2C%20__continue)%20%7B%0A%20%20%20%20console.log(value)%3B%0A%20%20%20%20__continue(std.unit)%3B%0A%7D%3B%0A%0Agoog.provide(%22main%22)%3B%0Avar%20__module%20%3D%20main%3B%0A__module.main%20%3D%20function(__p0%2C%20%20__continue)%20%7B%0Avar%20__camefrom%3B%0Avar%20__b1%3B%0Avar%20__b3%3B%0Avar%20__b4%3B%0Avar%20__b5%3B%0Avar%20__v2%3B%0Avar%20__v6%3B%0Avar%20__v7%3B%0Avar%20__v8%3B%0Avar%20__v9%3B%0Avar%20__v10%3B%0Avar%20__v11%3B%0Avar%20__v12%3B%0Avar%20__v13%3B%0Avar%20__v14%3B%0Avar%20__v15%3B%0Avar%20__v16%3B%0Avar%20__v17%3B%0Avar%20__v18%3B%0Avar%20__v19%3B%0Avar%20__v20%3B%0Avar%20__v21%3B%0Avar%20__v22%3B%0A__b1%20%3D%20function()%20%7B%0A__v2%20%3D%20std.unit%3B%0A__v6%20%3D%20__p0%3B%0A__camefrom%20%3D%201%3B%0A(std.forcebool(__v6)%20%3F%20__b3%20%3A%20__b4)()%3B%0A%7D%3B%0A__b3%20%3D%20function()%20%7B%0A__v8%20%3D%20std.unit%3B%0A__v9%20%3D%20std.io%3B%0A__v10%20%3D%20__v9.writeln%3B%0A__v11%20%3D%20%22Hello%2C%20world!%22%3B%0A__v10(__v11%2C%20%20function(__c12)%20%7B%0A__v12%20%3D%20__c12%3B%0A__camefrom%20%3D%203%3B%0A__b5()%3B%0A%7D)%3B%0A%7D%3B%0A__b4%20%3D%20function()%20%7B%0A__v14%20%3D%20std.unit%3B%0A__v15%20%3D%20std.io%3B%0A__v16%20%3D%20__v15.writeln%3B%0A__v17%20%3D%20%22Byebye%2C%20world!%22%3B%0A__v16(__v17%2C%20%20function(__c18)%20%7B%0A__v18%20%3D%20__c18%3B%0A__camefrom%20%3D%204%3B%0A__b5()%3B%0A%7D)%3B%0A%7D%3B%0A__b5%20%3D%20function()%20%7B%0A__v20%20%3D%20%7B%0A%20%20%20%203%3A%20__v12%2C%0A%20%20%20%204%3A%20__v18%0A%7D%5B__camefrom%5D%3B%0A__v21%20%3D%20std.unit%3B%0A__continue(__v21)%3B%0A%7D%3B%0A__b1()%3B%0A%7D%3B%0A%0Amain.main(true%2C%20function()%20%7B%0A%20%20%20%20main.main(false%2C%20function()%20%7B%20%7D)%3B%0A%7D)%3B

On the online compiler service (http://closure-compiler.appspot.com/home). I have no idea why. The code compiles and runs correctly with whitespace and simple optimisations.

**Comment by concavelenz** [comment]
Thanks for the report

**Comment by MatrixFrog** [comment]
Smaller repro:

    // ==ClosureCompiler==
    // @compilation_level ADVANCED_OPTIMIZATIONS
    // @output_file_name default.js
    // @formatting pretty_print
    // ==/ClosureCompiler==
    
    var std = {};
    
    std.unit = new (function() {})();
    
    var __module = main;
    __module.main = function() {
      var __v14;
    
      __b4 = function() {
        __v14 = std.unit;
      };
    };

**Comment by MatrixFrog** [comment]
I would recommend essentially the same workaround I suggested for #811 : Add `--jscomp_error=checkVars` to your flags and the compiler will fail with a clear error message before it gets to the pass that is crashing.

**Comment by Dominator008** [comment]
This seems to have been fixed now.
