### ISSUE TITLE
Internal Compiler Error When Compiling ES6 to ES6

### ISSUE THREAD

**Issue by TimFerrell** [google/closure-compiler#894]
Attached is the output; please let me know if you need anything further.

````
[timothyferrell:~/downloads/compiler-latest]$ java -jar compiler.jar --language_in=ECMASCRIPT6 --allow_es6_out ~/Desktop/inline-css/
/Users/timothyferrell/Desktop/inline-css/inline-animations.js:8: WARNING - unreachable code
    let body = document.getElementsByTagName("body")[0];
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:9: WARNING - unreachable code
    let container = document.createElement("div");
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:15: WARNING - unreachable code
    let domElem = document.createElement("div");
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:17: WARNING - unreachable code
    let domTitle = document.createElement("h2");
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:18: WARNING - unreachable code
    let domTitleTextNode = document.createTextNode(title);
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:21: WARNING - unreachable code
    let domMessage = document.createElement("p");
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:22: WARNING - unreachable code
    let domMessageTextNode = document.createTextNode(message);
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:25: WARNING - unreachable code
    let animateInStyle = buildEnterAnimationStyle(enterDuration,'linear');
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:26: WARNING - unreachable code
    let animateOutStyle = buildExitAnimationStyle(exitDuration,'linear');
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:34: WARNING - unreachable code
    let exitHandle = setTimeout(function () {
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:51: WARNING - unreachable code
    let style = "-webkit-animation: slideInLeft "+duration+"ms forwards";
        ^

/Users/timothyferrell/Desktop/inline-css/inline-animations.js:63: WARNING - unreachable code
    let style = "-webkit-animation: slideOutLeft "+duration+"ms forwards";
        ^

0 error(s), 12 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(EXPR_RESULT): /Users/timothyferrell/Desktop/inline-css/inline-animations.js:11:4
    body.appendChild(container);
  Parent(BLOCK): /Users/timothyferrell/Desktop/inline-css/inline-animations.js:7:17
(function init() {

	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.tryReplaceArguments(OptimizeArgumentsArray.java:182)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.exitScope(OptimizeArgumentsArray.java:127)
	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:677)
	at com.google.javascript.jscomp.NodeTraversal.popScope(NodeTraversal.java:668)
	at com.google.javascript.jscomp.NodeTraversal.traverseBlockScope(NodeTraversal.java:621)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:564)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:610)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:562)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:528)
	at com.google.javascript.jscomp.OptimizeArgumentsArray.process(OptimizeArgumentsArray.java:92)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1978)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:764)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
	... 28 more
````

**Comment by MatrixFrog** [comment]
Can you also post the code, or a small snippet of it that also shows the issue?

**Comment by TimFerrell** [comment]
Sure, see below.
Apologies for the bad code.

````
'use strict';

window.toastr = {};

(function init() {
    let body = document.getElementsByTagName("body")[0];
    let container = document.createElement("div");
    container.setAttribute("id","toastContainer");
    body.appendChild(container);
}());

function createToast(title,message,enterDuration,delay, exitDuration) {
    let domElem = document.createElement("div");

    let domTitle = document.createElement("h2");
    let domTitleTextNode = document.createTextNode(title);
    domTitle.appendChild(domTitleTextNode);

    let domMessage = document.createElement("p");
    let domMessageTextNode = document.createTextNode(message);
    domMessage.appendChild(domMessageTextNode);

    domElem.classList.add("toast");
    domElem.appendChild(domTitle);
    domElem.appendChild(domMessage);

    let duration = 200;

    var player = domElem.animate([
        {transform: 'translateX(' + -200 + 'px)'},
        {transform: 'translateX(' + 0 + 'px)'}
    ], {
        duration: duration,
        iterations: 1,
        delay: 0
    });

    document.getElementById("toastContainer").appendChild(domElem);

}


setInterval(function () {
    createToast('Toast Message','This is some content',250,5550,600);
},50);
````

**Comment by MatrixFrog** [comment]
--allow_es6_out is not supported yet. Crashes when using that flag are to be expected. https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L533-L534
