### ISSUE TITLE
java.lang.RuntimeException: INTERNAL COMPILER ERROR.

### ISSUE THREAD

**Issue by ihsoft** [google/closure-compiler#900]
Recently got error:

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

only implemented in ClosureCodingConvention
  Node(CALL): ..\js\google\base.js:113:8
    if (goog.isProvided_(name)) {
  Parent(IF): ..\js\google\base.js:113:4
    if (goog.isProvided_(name)) {

        at com.google.javascript.jscomp.CodingConventions$DefaultCodingConvention.extractClassNameIfRequire(CodingConven
tions.java:352)
        at com.google.javascript.jscomp.CodingConventions$Proxy.extractClassNameIfRequire(CodingConventions.java:136)
        at com.google.javascript.jscomp.CheckRequiresForConstructors$CheckRequiresForConstructorsCallback.visitCallNode(
CheckRequiresForConstructors.java:171)
        at com.google.javascript.jscomp.CheckRequiresForConstructors$CheckRequiresForConstructorsCallback.visit(CheckReq
uiresForConstructors.java:122)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:610)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:562)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:308)
        at com.google.javascript.jscomp.NodeTraversal.traverseRootsTyped(NodeTraversal.java:543)
        at com.google.javascript.jscomp.CheckRequiresForConstructors.process(CheckRequiresForConstructors.java:60)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
        at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: only implemented in ClosureCodingConvention
        ... 30 more
Compilation failed, release process aborts

I set all allowed classes for --jscomp_error beacuse I wanted to have a most strict code validation possible. The problem was in "--jscomp_error=missingRequire". Once deleted the JSC worked fine.

**Comment by ihsoft** [comment]
Another strange thing was that I got a lot of errors but return code pf the compiler still was 0. How an I check if the sources were compiled successfully then?

**Comment by dimvar** [comment]
Are you somehow turning off the closure pass? What flags are you calling the compiler with?

**Comment by MatrixFrog** [comment]
And, what version are you on? I made some changes in that check recently, which may be related.

**Comment by ihsoft** [comment]
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150315
Built on: 2015/03/17 14:18

I don't explicitly enable or disable closure pass.

Full list of the flags:
 --js=<my source files>^
 --js=..\js\google/base.js ^
 --js_output_file=...... ^
 --compilation_level=ADVANCED ^
 --process_jquery_primitives ^
 --charset UTF-8 ^
 --summary_detail_level 3 ^
 --warning_level=VERBOSE ^
 --externs=<some of my externs + jQuery extern file> ^
 --process_closure_primitives ^
 --define=<couple of my defines> ^
 --accept_const_keyword ^
 --use_types_for_optimization ^
 --jscomp_off=es5Strict ^
 --jscomp_error=accessControls ^
 --jscomp_error=ambiguousFunctionDecl ^
 --jscomp_error=checkEventfulObjectDisposal ^
 --jscomp_error=checkRegExp ^
 --jscomp_error=checkStructDictInheritance ^
 --jscomp_error=checkTypes ^
 --jscomp_error=checkVars ^
 --jscomp_error=conformanceViolations ^
 --jscomp_error=const ^
 --jscomp_error=constantProperty ^
 --jscomp_error=deprecated ^
 --jscomp_error=duplicateMessage ^
 --jscomp_error=externsValidation ^
 --jscomp_error=fileoverviewTags ^
 --jscomp_error=globalThis ^
 --jscomp_error=inferredConstCheck ^
 --jscomp_error=internetExplorerChecks ^
 --jscomp_error=invalidCasts ^
 --jscomp_error=misplacedTypeAnnotation ^
 --jscomp_error=missingGetCssName ^
 --jscomp_error=missingProperties ^
 --jscomp_error=missingProvide ^
 --jscomp_error=missingReturn ^
 --jscomp_error=newCheckTypes ^
 --jscomp_error=nonStandardJsDocs ^
 --jscomp_error=suspiciousCode ^
 --jscomp_error=strictModuleDepCheck ^
 --jscomp_error=typeInvalidation ^
 --jscomp_error=undefinedNames ^
 --jscomp_error=undefinedVars ^
 --jscomp_error=unknownDefines ^
 --jscomp_error=uselessCode ^
 --jscomp_error=useOfGoogBase ^
 --jscomp_error=visibility ^
 --jscomp_error=reportUnknownTypes

**Comment by ihsoft** [comment]
And a note which may be helpfull. Recently I discovered that I was using ```goog.provide``` incorrectly. Here is a snippet:
```javascript
goog.provide('BRTV');
goog.require('BrtvStorage');
var BRTV = {  // Namespace.
initialize: function() {
  // function body...
}
// more methods...
}; // Namespace.
```
I now realize that I should not have used ```goog.provide``` in this case since I make namespace in the module. Though, compiler never complained and code worked fine.

**Comment by MatrixFrog** [comment]
--process_jquery_primitives causes the compiler to use the JqueryCodingConvention instead of the Closure one. Maybe if both --process_jquery_primitives and --process_closure_primitives are set (which will often happen since the latter is true by default) then we should use a convention which merges those two.

**Comment by MatrixFrog** [comment]
Or the jQuery one can just extend the Closure one but that doesn't really make sense.

**Comment by MatrixFrog** [comment]
cf880aecdf94222367f20ffe807b0f343d967546 should at least make situations like this less likely, if not prevent them.

**Comment by Dominator008** [comment]
@ihsoft Is this crash still happening?
