### ISSUE TITLE
Is Java 8 supported? (.java.lang.NoClassDefFoundError: com/google/javascript/jscomp/newtypes/ObjsType)

### ISSUE THREAD

**Issue by adhintz** [google/closure-compiler#902]
When compiling our project with Sun's Java 8, @rcchan is getting an error with ObjsType. However the compilation works fine for me with OpenJDK 7.

More details are in https://github.com/google/end-to-end/issues/264

Here's the stack trace:

.java.lang.NoClassDefFoundError: com/google/javascript/jscomp/newtypes/ObjsType
    at com.google.javascript.jscomp.ClosureCodingConvention.getAssertionFunctions(ClosureCodingConvention.java:399)
    at com.google.javascript.jscomp.TypeInferencePass.<init>(TypeInferencePass.java:54)
    at com.google.javascript.jscomp.PassConfig.makeTypeInference(PassConfig.java:161)
    at com.google.javascript.jscomp.DefaultPassConfig$44$1.process(DefaultPassConfig.java:1417)
    at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
    at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
    at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
    at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.javascript.jscomp.newtypes.ObjsType
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 16 more

**Comment by MatrixFrog** [comment]
Java 8 is not officially supported, but we plan to support it soon, so thanks for bringing this to our attention! Generally the fix for a NoClassDefFoundError is to do an `ant clean` and then rebuild, because there may be an out of date class file somewhere. In this case it looks like you did that already, so I'll look into it.

**Comment by adhintz** [comment]
Thanks for looking at it. @rcchan was able to build https://github.com/google/end-to-end successfully by "Manually cding into /lib/closure-compiler and running ant clean && ant " so perhaps it's a problem with how we're using closure compiler.

**Comment by rcchan** [comment]
I was able to get it to build with `ant clean && ant` from the `closure-compiler` directory.
Since that works, I suspect it might have to do with the e2e installation of closure-compiler.

The other issue below still stands but was easy to identify + fix (present in both Java 7 and Java 8).
I think it has to do with using a different version of ant (1.7.1) which is not latest.
```diff
--- a/src/com/google/javascript/jscomp/ant/CompileTask.java
+++ b/src/com/google/javascript/jscomp/ant/CompileTask.java
@@ -613,7 +613,7 @@ public final class CompileTask
-FileResource fr = (FileResource) iter.next().as(FileResource.class);
+FileResource fr = (FileResource) iter.next();
```

**Comment by adhintz** [comment]
Cool. Want to submit a PR to https://github.com/google/closure-compiler/ for removing the .as(FileResource.class) ?

**Comment by MatrixFrog** [comment]
If you are a Googler, it's easier to submit patches using the internal systems rather than on Github.

**Comment by rcchan** [comment]
I made note of it here in case anyone else runs into the issue or if the maintainers feel that it's important for backward compatibility.
In general, it should work fine in the latest ant version (1.8.1).
The reason it breaks for me is because we have an older version of ant installed which doesn't have `.as()` defined for `Resource`.

**Comment by MatrixFrog** [comment]
Also it might be easier for e2e to just use the released compiler from http://dl.google.com/closure-compiler/compiler-latest.zip instead of building it yourself. But I haven't looked at your setup, maybe there's some reason that won't work.

**Comment by rcchan** [comment]
I'm not currently a Googler but it should be an easy (one line) patch if you want me to either PR or send in.  Is this a modification that we would want to make?

**Comment by MatrixFrog** [comment]
Okay, PR is fine then (you'll have to sign a CLA, see https://github.com/google/closure-compiler/#submitting-patches) and if it still works with whatever version of Ant we're using, then yes, that should be fine.

**Comment by rcchan** [comment]
I should already have a CLA signed for contributing to e2e
(Trying to sign it again gives me a message reaffirming that)

**Comment by rcchan** [comment]
Also, I think this issue can be closed as the PR does not address any sort of Java 8 issue and it seems to run fine on Java 8.
