### ISSUE TITLE
java.lang.NoSuchMethodError in CheckRegExp

### ISSUE THREAD

**Issue by ernestoalejo** [google/closure-compiler#906]
I will try to find the source file that it's triggering this error and add it to this issue.

Stacktrace:
```
java.lang.NoSuchMethodError: com.google.javascript.jscomp.Scope.getVar(Ljava/lang/String;)Lcom/google/javascript/jscomp/Scope$Var;
	at com.google.javascript.jscomp.CheckRegExp.visit(CheckRegExp.java:72)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:577)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:611)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:563)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:528)
	at com.google.javascript.jscomp.CheckRegExp.process(CheckRegExp.java:65)
	at com.google.javascript.jscomp.DefaultPassConfig$39$1.process(DefaultPassConfig.java:1366)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MatrixFrog** [comment]
`NoSuchMethodError` is usually fixed by doing an `ant clean`.

**Comment by ernestoalejo** [comment]
That was it. Thank you!
