### ISSUE TITLE
ICE when compiling with ECMASCRIPT6_TYPED and closure-library

### ISSUE THREAD

**Issue by sharvil** [google/closure-compiler#945]
```
INTERNAL COMPILER ERROR.
Please report this problem.

unexpected language mode: ECMASCRIPT6_TYPED
  Node(CALL): closure/goog/i18n/bidi.js:243:29
goog.i18n.bidi.rtlCharReg_ = new RegExp('[' + goog.i18n.bidi.rtlChars_ + ']');
  Parent(NAME goog$i18n$bidi$rtlCharReg_): closure/goog/i18n/bidi.js:243:0
goog.i18n.bidi.rtlCharReg_ = new RegExp('[' + goog.i18n.bidi.rtlChars_ + ']');

	at com.google.javascript.jscomp.Compiler.acceptEcmaScript5(Compiler.java:2120)
	at com.google.javascript.jscomp.AbstractPeepholeOptimization.isEcmaScript5OrGreater(AbstractPeepholeOptimization.java:137)
	at com.google.javascript.jscomp.PeepholeSubstituteAlternateSyntax.tryFoldRegularExpressionConstructor(PeepholeSubstituteAlternateSyntax.java:457)
	at com.google.javascript.jscomp.PeepholeSubstituteAlternateSyntax.tryFoldLiteralConstructor(PeepholeSubstituteAlternateSyntax.java:368)
	at com.google.javascript.jscomp.PeepholeSubstituteAlternateSyntax.optimizeSubtree(PeepholeSubstituteAlternateSyntax.java:84)
	at com.google.javascript.jscomp.PeepholeOptimizationsPass$PeepCallback.visit(PeepholeOptimizationsPass.java:82)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:577)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:528)
	at com.google.javascript.jscomp.PeepholeOptimizationsPass$1.visit(PeepholeOptimizationsPass.java:66)
	at com.google.javascript.jscomp.NodeTraversal$1.shouldTraverse(NodeTraversal.java:515)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:558)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverseChangedFunctions(NodeTraversal.java:520)
	at com.google.javascript.jscomp.PeepholeOptimizationsPass.process(PeepholeOptimizationsPass.java:58)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:458)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1979)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:94)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

unexpected language mode: ECMASCRIPT6_TYPED
  Node(CALL): closure/goog/i18n/bidi.js:243:29
goog.i18n.bidi.rtlCharReg_ = new RegExp('[' + goog.i18n.bidi.rtlChars_ + ']');
  Parent(NAME goog$i18n$bidi$rtlCharReg_): closure/goog/i18n/bidi.js:243:0
goog.i18n.bidi.rtlCharReg_ = new RegExp('[' + goog.i18n.bidi.rtlChars_ + ']');

	... 32 more
Caused by: java.lang.IllegalStateException: unexpected language mode: ECMASCRIPT6_TYPED
	... 32 more
```

**Comment by sharvil** [comment]
Code compiled with:

```
--warning_level=VERBOSE --compilation_level=ADVANCED_OPTIMIZATIONS --language_in=ECMASCRIPT6_TYPED --language_out=ECMASCRIPT5
```

**Comment by MatrixFrog** [comment]
I don't think ECMASCRIPT6_TYPED mode is being actively maintained at the moment.

**Comment by sharvil** [comment]
Thanks for the heads up. I'll leave this issue open in case someone decides to pick up support in the future.

**Comment by Dominator008** [comment]
@sharvil More work was done with ECMASCRIPT6_TYPED and I don't think this error is happening any more, closing this.
